<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<RootNamespace>OSDC.Drilling.Cluster.DBVersioningManager</RootNamespace>
    	<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
	</PropertyGroup>

	<ItemGroup>
    	<ProjectReference Include="..\ModelSharedOut\ModelSharedOut.csproj" />
  	</ItemGroup>
</Project>
