using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using DrillSim.PublicationGate;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace DrillingOperations.GeologicalPropertiesServiceTests;
[TestFixture,NonParallelizable]
public sealed partial class PublicationGeologicalPropertiesImportTests
{
 [Test]
 public async Task AuthoritativeImport_PreservesLargePetrophysicsAcrossRestart_AndRemainsReceiptGated()
 {
  string database=Path.Combine(Path.GetTempPath(),$"geology-publication-{Guid.NewGuid():N}.db");Guid scenario=Guid.NewGuid(),reveal=Guid.NewGuid(),id=Guid.NewGuid(),bore=Guid.NewGuid(),trajectory=Guid.NewGuid(),run=Guid.NewGuid(),curve=Guid.NewGuid();var receipt=new ReceiptHandler(scenario,reveal);double[] depths=Enumerable.Range(0,500).Select(x=>1000d+x*.5d).ToArray();double?[] values=depths.Select((_,i)=>(double?)(80d+i*.01d)).ToArray();var payload=new{metaInfo=new{id},name="scenario observable geology",description="authoritative read-back",creationDate="2000-01-01T00:00:00+00:00",lastModificationDate="2000-01-01T00:00:00+00:00",wellBoreID=bore,trajectoryID=trajectory,isPrognosed=false,geologicalPropertyTable=Array.Empty<object>(),petrophysics=new{provenance=new{datasetName="scenario logs",datasetVersion="synthetic-petrophysics-v2",classification=4,sourceArtifacts=new[]{new{id=Guid.NewGuid(),url="urn:artifact:sealed",license="test",attribution="DrillSim",sha256=new string('a',64)}}},temporal=new{validTimeStart="2025-01-02T00:00:00+00:00",transactionTimeStart="2025-01-02T01:00:00+00:00"},logRuns=new[]{new{id=run,name="LWD",tool="synthetic",depthAxis=new{reference=0,originalUnit="m",canonicalUnit="m",datum="MD",positiveDown=true},depthValues=depths,curves=new[]{new{id=curve,originalMnemonic="GR",canonicalMnemonic="GR",originalUnit="gAPI",canonicalUnit="gAPI",values,nullFlags=Enumerable.Repeat(false,500),qualityFlags=Enumerable.Repeat<string?>(null,500),classification=4}}}},formationTops=new[]{new{id=Guid.NewGuid(),formationName="Reservoir",depths=new[]{new{reference=0,originalValue=1100d,originalUnit="m",value=1100d,unit="m",datum="MD",positiveDown=true}},confidence=.9,method="observed",classification=1}},formationIntervals=Array.Empty<object>()}};
  await using(var first=new Factory(receipt,database)){using var client=first.CreateClient();using(var unauthorized=new HttpRequestMessage(HttpMethod.Post,"/geologicalproperties/api/internal/publication/GeologicalProperties"){Content=JsonContent.Create(payload)})Assert.That((await client.SendAsync(unauthorized)).StatusCode,Is.EqualTo(HttpStatusCode.Unauthorized));using(var stage=Request(HttpMethod.Put,$"/geologicalproperties/api/internal/publication/records/{id:D}/stage",new{scenarioId=scenario,revealId=reveal}))(await client.SendAsync(stage)).EnsureSuccessStatusCode();using(var import=Request(HttpMethod.Post,"/geologicalproperties/api/internal/publication/GeologicalProperties",payload))(await client.SendAsync(import)).EnsureSuccessStatusCode();Assert.That((await client.GetAsync($"/geologicalproperties/api/GeologicalProperties/{id:D}")).StatusCode,Is.EqualTo(HttpStatusCode.NotFound));Assert.That((await client.GetAsync($"/geologicalproperties/api/GeologicalProperties/ByWellBoreID?wellBoreId={bore:D}")).StatusCode,Is.EqualTo(HttpStatusCode.OK));using var hiddenByParent=JsonDocument.Parse(await (await client.GetAsync($"/geologicalproperties/api/GeologicalProperties/ByWellBoreID?wellBoreId={bore:D}")).Content.ReadAsStringAsync());Assert.That(hiddenByParent.RootElement.GetArrayLength(),Is.Zero);using var internalRead=Request(HttpMethod.Get,$"/geologicalproperties/api/GeologicalProperties/{id:D}");using var response=await client.SendAsync(internalRead);response.EnsureSuccessStatusCode();AssertPayload(await response.Content.ReadAsStringAsync(),id,bore,trajectory,500);using(var activate=Request(HttpMethod.Put,$"/geologicalproperties/api/internal/publication/records/{id:D}/activate"))(await client.SendAsync(activate)).EnsureSuccessStatusCode();}
  Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();
  await using(var restarted=new Factory(receipt,database)){using var client=restarted.CreateClient();Assert.That((await client.GetAsync($"/geologicalproperties/api/GeologicalProperties/{id:D}")).StatusCode,Is.EqualTo(HttpStatusCode.NotFound));using var internalRead=Request(HttpMethod.Get,$"/geologicalproperties/api/GeologicalProperties/{id:D}");AssertPayload(await (await client.SendAsync(internalRead)).Content.ReadAsStringAsync(),id,bore,trajectory,500);receipt.Committed=true;using var visible=await client.GetAsync($"/geologicalproperties/api/GeologicalProperties/{id:D}");visible.EnsureSuccessStatusCode();AssertPayload(await visible.Content.ReadAsStringAsync(),id,bore,trajectory,500);using var parent=JsonDocument.Parse(await (await client.GetAsync($"/geologicalproperties/api/GeologicalProperties/ByWellBoreID?wellBoreId={bore:D}")).Content.ReadAsStringAsync());Assert.That(parent.RootElement.GetArrayLength(),Is.EqualTo(1));}
 }
 static void AssertPayload(string json,Guid id,Guid bore,Guid trajectory,int sampleCount){using var document=JsonDocument.Parse(json);JsonElement root=document.RootElement;Assert.Multiple(()=>{Assert.That(P(P(root,"MetaInfo"),"ID").GetGuid(),Is.EqualTo(id));Assert.That(P(root,"WellBoreID").GetGuid(),Is.EqualTo(bore));Assert.That(P(root,"TrajectoryID").GetGuid(),Is.EqualTo(trajectory));Assert.That(P(P(root,"Petrophysics"),"LogRuns")[0].GetProperty("DepthValues").GetArrayLength(),Is.EqualTo(sampleCount));Assert.That(P(P(P(root,"Petrophysics"),"LogRuns")[0],"Curves")[0].GetProperty("Values").GetArrayLength(),Is.EqualTo(sampleCount));Assert.That(P(root,"CreationDate").GetDateTimeOffset(),Is.Not.EqualTo(DateTimeOffset.Parse("2000-01-01T00:00:00+00:00")));});}
 static JsonElement P(JsonElement value,string name)=>value.EnumerateObject().First(x=>x.Name.Equals(name,StringComparison.OrdinalIgnoreCase)).Value;
 static HttpRequestMessage Request(HttpMethod method,string path,object? body=null){var request=new HttpRequestMessage(method,path);request.Headers.Add("X-DrillSim-Publication-Key",Factory.Key);if(body is not null)request.Content=JsonContent.Create(body);return request;}
 sealed class Factory(ReceiptHandler receipt,string database):WebApplicationFactory<global::Program>{internal const string Key="geology-publication-test-key";protected override void ConfigureWebHost(IWebHostBuilder builder){builder.UseSetting("ConnectionStrings:Sqlite",$"Data Source={database}");builder.UseSetting("DRILLSIM_PUBLICATION_IMPORT_KEY",Key);builder.UseSetting("AnalysisApiUrl","http://analysis.test/");builder.ConfigureServices(services=>{services.RemoveAll<ScenarioPublicationGateStore>();services.AddSingleton(new ScenarioPublicationGateStore(ScenarioPublicationGateExtensions.DeriveGateConnection($"Data Source={database}"),new HttpClient(receipt){BaseAddress=new Uri("http://analysis.test/")}));});}protected override void Dispose(bool disposing){base.Dispose(disposing);Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();}}
 sealed class ReceiptHandler(Guid scenario,Guid reveal):HttpMessageHandler{internal bool Committed;protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct)=>Task.FromResult(new HttpResponseMessage(Committed?HttpStatusCode.OK:HttpStatusCode.NotFound){Content=JsonContent.Create(new{scenarioId=scenario,revealId=reveal,status="Revealed"})});}
}
