<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OSDC.Drilling.EarthMagneticField.ModelShared</RootNamespace>
    <Title>Auto-generation of the OSDC Earth Magnetic Field distributed shared model and API client</Title>
    <Authors>Eric Cayeux</Authors>
    <Company>NORCE Research</Company>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.31" />
    <PackageReference Include="NSwag.CodeGeneration.CSharp" Version="14.7.1" />
  </ItemGroup>
  <ItemGroup Condition="!Exists('EarthMagneticFieldMergedModel.cs')">
    <Compile Remove="PseudoConstructors.cs" />
  </ItemGroup>
</Project>
