apiVersion: v1
kind: Service
metadata:
  name: {{ include "norcedrillingsimulator4ndofservice.fullname" . }}
  labels:
    {{- include "norcedrillingsimulator4ndofservice.labels" . | nindent 4 }}  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "norcedrillingsimulator4ndofservice.selectorLabels" . | nindent 4 }}

