<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Energy Modelling and Automation group</Authors>
		<Company>NORCE</Company>
		<Title>Auto-generation of the API of the TplProjectName microservice (distributed shared model approach)</Title>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.31" />
		<PackageReference Include="NSwag.CodeGeneration.CSharp" Version="14.7.1" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0-1.final" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="PseudoConstructorsWriter.cs" />
	</ItemGroup>

</Project>
