replicaCount: 1
nameOverride: "osdcdrillingearthmagneticfieldservice"
fullnameOverride: osdcearthmagneticfieldservice
image:
  repository: docker.io/digiwells/osdcdrillingearthmagneticfieldservice
  tag: "stable"
  pullPolicy: Always
imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /EarthMagneticField/api/metrics
  prometheus.io/port: "8080"
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  annotations:
    description: "A stateless WMM2025 and IGRF14 geomagnetic-field evaluation microservice"
earthMagneticField:
  maximumSamplesPerRequest: 10000
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: true
  className: public
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: localhost
      paths:
        - path: /(?i)earthmagneticfield/api
          pathType: ImplementationSpecific
    - host: dev.digiwells.no
      paths:
        - path: /(?i)earthmagneticfield/api
          pathType: ImplementationSpecific
    - host: app.digiwells.no
      paths:
        - path: /(?i)earthmagneticfield/api
          pathType: ImplementationSpecific
    - host: awe.web.intra.norceresearch.no
      paths:
        - path: /(?i)earthmagneticfield/api
          pathType: ImplementationSpecific
  tls: []
probes:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
