<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OSDC.Drilling.EarthMagneticField.Model</RootNamespace>
    <Authors>Eric Cayeux</Authors>
    <Company>NORCE Research</Company>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GeographicLib.NET" Version="2.3.2" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\MagneticFieldModelFiles\**\*">
      <Link>MagneticFieldModelFiles\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
