apiVersion: v1
kind: Service
metadata:
  name: {{ include "earthgravitywebapp.fullname" . }}
  labels: {{- include "earthgravitywebapp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  selector: {{- include "earthgravitywebapp.selectorLabels" . | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
