<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Energy Modelling and Automation group</Authors>
		<Company>NORCE</Company>
		<Title>Auto-generation of the API of the GeodeticDatum microservice (distributed shared model approach)</Title>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.OpenApi" Version="2.7.5">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="NSwag.CodeGeneration.CSharp" Version="14.7.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="json-schemas\" />
	</ItemGroup>

</Project>
