replicaCount: 1
nameOverride: "osdcdrillingearthgravityservice"
fullnameOverride: osdcearthgravityservice
image:
  repository: docker.io/digiwells/osdcdrillingearthgravityservice
  tag: "stable"
  pullPolicy: Always
imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /EarthGravity/api/metrics
  prometheus.io/port: "8080"
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  annotations:
    description: "A stateless microservice for evaluating EGM96 Earth gravity"
earthGravity:
  maximumPositionsPerRequest: 10000
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: true
  className: public
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: localhost
      paths:
        - path: /(?i)earthgravity/api
          pathType: ImplementationSpecific
    - host: dev.digiwells.no
      paths:
        - path: /(?i)earthgravity/api
          pathType: ImplementationSpecific
    - host: app.digiwells.no
      paths:
        - path: /(?i)earthgravity/api
          pathType: ImplementationSpecific
    - host: awe.web.intra.norceresearch.no
      paths:
        - path: /(?i)earthgravity/api
          pathType: ImplementationSpecific
  tls: []
probes:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
