namespace DrillingOperations.Tests;
[TestFixture]
public sealed class LogObservationModelTests
{
 private static TruthSampleDto T(double md,double phi=.2,double ntg=1,double sw=.4,double so=.6,double sg=0,double pressure=20_000_000)=>new(md,md,0,1000,0,2000,phi,1e-13,ntg,true,pressure,so,sw,sg);
 private static LogObservationOptions Clean(double spacing=10,double resolution=.1)=>new(){SampleSpacingM=spacing,VerticalResolutionM=resolution,GrNoiseStdDevApi=0,RhobNoiseStdDevKgM3=0,NphiNoiseStdDevFraction=0,ResistivityNoiseStdDevOhmM=0,CaliperNoiseStdDevM=0,GrDriftPer1000M=0,RhobDriftPer1000M=0,NphiDriftPer1000M=0,ResistivityDriftPer1000M=0,MissingProbability=0,BadHoleProbability=0,MdtFailureProbability=0,MdtSuperchargeProbability=0,MdtGaugeNoiseStdDevPa=0};
 [Test] public void CleanForwardModel_HasClosedFormPhysicalLimits(){var o=Clean();CleanPetrophysics x=DeterministicLogObservationModel.ForwardClean(T(0),o);Assert.Multiple(()=>{Assert.That(x.GrApi,Is.EqualTo(20).Within(1e-10));Assert.That(x.RhobKgM3,Is.EqualTo(2298.4).Within(1e-10));Assert.That(x.NphiFraction,Is.EqualTo(.188).Within(1e-10));Assert.That(x.DeepResistivityOhmM,Is.EqualTo(12.5).Within(1e-10));Assert.That(x.CaliperM,Is.EqualTo(.216).Within(1e-10));});}
 [Test] public void IndependentInverse_RecoversPorosityAndWaterSaturation(){var o=Clean();TruthSampleDto truth=T(0,.27,1,.35,.65);CleanPetrophysics x=DeterministicLogObservationModel.ForwardClean(truth,o);double fluid=o.OilDensityKgM3*.65+o.WaterDensityKgM3*.35;double recoveredPhi=(o.SandMatrixDensityKgM3-x.RhobKgM3)/(o.SandMatrixDensityKgM3-fluid);double recoveredSw=Math.Pow(o.ArchieA*o.FormationWaterResistivityOhmM/(x.DeepResistivityOhmM*Math.Pow(recoveredPhi,o.ArchieM)),1/o.ArchieN);Assert.Multiple(()=>{Assert.That(recoveredPhi,Is.EqualTo(.27).Within(1e-10));Assert.That(recoveredSw,Is.EqualTo(.35).Within(1e-10));Assert.That(Math.Abs(recoveredPhi-.27),Is.LessThan(.01));Assert.That(Math.Abs(recoveredSw-.35),Is.LessThan(.02));});}
 [Test] public void Generate_IsDeterministic_ChangesWithCalibration_AndHandlesFivePoints(){TruthSampleDto[] truth=[T(0),T(25,.22,.9),T(50,.25,.7),T(75,.18,.5),T(100,.15,.3)];var o=new LogObservationOptions{SampleSpacingM=5,VerticalResolutionM=10};var a=DeterministicLogObservationModel.Generate("run-a",truth,o);var replay=DeterministicLogObservationModel.Generate("run-a",truth,o);var changed=DeterministicLogObservationModel.Generate("run-a",truth,new(){SampleSpacingM=5,VerticalResolutionM=10,CalibrationVersion="changed"});Assert.Multiple(()=>{Assert.That(CanonicalJson.Serialize(a.Samples),Is.EqualTo(CanonicalJson.Serialize(replay.Samples)));Assert.That(CanonicalJson.Serialize(a.Samples),Is.Not.EqualTo(CanonicalJson.Serialize(changed.Samples)));Assert.That(a.Samples.Count,Is.EqualTo(21));Assert.That(a.Samples.Count,Is.LessThanOrEqualTo(10000));Assert.That(a.Samples.Select(x=>x.MeasuredDepthM),Is.Ordered.Ascending);});}
 [Test] public void VerticalResolution_SmoothsBeforeCalibration(){TruthSampleDto[] truth=[T(0,ntg:1),T(10,ntg:1),T(20,ntg:0)];var x=DeterministicLogObservationModel.Generate("smooth",truth,Clean(10,20)).Samples;Assert.Multiple(()=>{Assert.That(x[1].GrApi,Is.EqualTo((20+20+120)/3d).Within(1e-10));Assert.That(x[1].GrApi,Is.GreaterThan(20));Assert.That(x[1].GrApi,Is.LessThan(120));});}
 [Test] public void ClippingMissingnessBadHoleAndMdtStates_AreExplicit(){TruthSampleDto[] truth=[T(0,ntg:0),T(100,ntg:0)];var clipped=DeterministicLogObservationModel.Generate("clip",truth,withLimits()).Samples[0];var missing=DeterministicLogObservationModel.Generate("missing",truth,new(){SampleSpacingM=10,MissingProbability=1,MdtFailureProbability=1,MdtSuperchargeProbability=0}).Samples;var bad=DeterministicLogObservationModel.Generate("bad",truth,new(){SampleSpacingM=10,MissingProbability=0,BadHoleProbability=1,MdtFailureProbability=1,MdtSuperchargeProbability=0,CaliperNoiseStdDevM=0}).Samples;var failed=DeterministicLogObservationModel.Generate("failed",truth,new(){SampleSpacingM=10,MdtFailureProbability=1,MdtSuperchargeProbability=0}).Pressures;var super=DeterministicLogObservationModel.Generate("super",truth,new(){SampleSpacingM=10,MdtFailureProbability=0,MdtSuperchargeProbability=1,MdtGaugeNoiseStdDevPa=0}).Pressures;Assert.Multiple(()=>{Assert.That(clipped.GrApi,Is.EqualTo(30));Assert.That(clipped.QcFlags,Does.Contain("GRClipped"));Assert.That(missing.All(x=>x.GrApi is null&&x.RhobKgM3 is null&&x.NphiFraction is null&&x.DeepResistivityOhmM is null&&x.CaliperM is null),Is.True);Assert.That(bad.All(x=>x.QcFlags.Contains("BadHole")&&x.CaliperM>.216),Is.True);Assert.That(failed.All(x=>x.PressurePa is null&&x.Qc=="Failed"),Is.True);Assert.That(super.All(x=>x.PressurePa==20_075_000&&x.Qc=="Supercharged"),Is.True);});LogObservationOptions withLimits()=>new(){SampleSpacingM=10,VerticalResolutionM=.1,GrNoiseStdDevApi=0,RhobNoiseStdDevKgM3=0,NphiNoiseStdDevFraction=0,ResistivityNoiseStdDevOhmM=0,CaliperNoiseStdDevM=0,GrDriftPer1000M=0,RhobDriftPer1000M=0,NphiDriftPer1000M=0,ResistivityDriftPer1000M=0,MissingProbability=0,BadHoleProbability=0,MdtFailureProbability=1,MdtSuperchargeProbability=0,GrClipMaxApi=30};}
 [Test] public void ContactTransition_IsObservableButNeverCopied(){TruthSampleDto[] truth=[T(0,sw:.1,so:.9),T(50,sw:.1,so:.9),T(100,sw:.9,so:.1),T(150,sw:.9,so:.1)];var output=DeterministicLogObservationModel.Generate("contact",truth,Clean(10,.1));double shallow=output.Samples.Where(x=>x.MeasuredDepthM<=50).Average(x=>x.DeepResistivityOhmM!.Value),deep=output.Samples.Where(x=>x.MeasuredDepthM>=100).Average(x=>x.DeepResistivityOhmM!.Value);string json=CanonicalJson.Serialize(output).ToLowerInvariant();Assert.Multiple(()=>{Assert.That(shallow,Is.GreaterThan(deep*20));Assert.That(json,Does.Not.Contain("saturation"));Assert.That(json,Does.Not.Contain("contact"));Assert.That(json,Does.Not.Contain("reservoirtop"));});}
 [Test] public void OptionsAndBounds_FailClosed(){Assert.Throws<Microsoft.Extensions.Options.OptionsValidationException>(()=>new LogObservationOptions{SampleSpacingM=0}.Validate());Assert.Throws<Microsoft.Extensions.Options.OptionsValidationException>(()=>new LogObservationOptions{MdtFailureProbability=.8,MdtSuperchargeProbability=.8}.Validate());TruthSampleDto[] truth=[T(0),T(10001)];Assert.Throws<RunStageFailureException>(()=>DeterministicLogObservationModel.Generate("cap",truth,Clean(.1,.1)));}
 [Test] public void SurveyMisalignment_AndTrajectoryRoles_AreExplicit(){DrilledPathStation[] p=[new(0,10,100,200),new(100,10,200,200)];var survey=DeterministicSurveyModel.Generate("survey",p,new(){StationSpacingM=100,EastBiasM=0,NorthBiasM=0,TvdBiasM=0,ScaleFactor=1,MisalignmentDegrees=10,RandomWalkStdDevM=0,NoiseStdDevM=0});Assert.Multiple(()=>{Assert.That(survey[1].ObservedEastingM,Is.EqualTo(100+100*Math.Cos(10*Math.PI/180)).Within(1e-9));Assert.That(survey[1].ObservedNorthingM,Is.EqualTo(200+100*Math.Sin(10*Math.PI/180)).Within(1e-9));Assert.Throws<Microsoft.Extensions.Options.OptionsValidationException>(()=>new SurveyObservationOptions{MisalignmentDegrees=16}.Validate());Assert.That(new MaterializedPlan("p","r","s","b","w","wb","t","c",[],"h","h",1,"h","h",DateTimeOffset.UtcNow).TrajectoryRole,Is.EqualTo("Planned"));Assert.That(new DrillingExecutionArtifact("e","r","p","m","o","c",[],[],0,0,"i","o",DateTimeOffset.UtcNow).TrajectoryRole,Is.EqualTo("AsDrilledTruth"));});}
}


