using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Logging.Abstractions;
namespace DrillingOperations.Tests;
[TestFixture,NonParallelizable]
public sealed class MigrationAndFailureAttributionTests
{
 [Test] public async Task LegacyTruthSchema_MigratesWithoutInventingProvenance_AndReadFailsSpecifically()
 {
  await using var fixture=new StoreFixture();await fixture.InitializeAsync();RunResponse run=await StoreFixture.BindAndCreateAsync(fixture.Store,suffix:"legacy");int auditBefore;
  await using(var connection=new SqliteConnection(fixture.ConnectionString)){await connection.OpenAsync();await using(var count=connection.CreateCommand()){count.CommandText="SELECT COUNT(*) FROM AuditEntries";auditBefore=Convert.ToInt32(await count.ExecuteScalarAsync());}await using var command=connection.CreateCommand();command.CommandText="DROP TRIGGER IF EXISTS TR_TruthSampleBatches_NoUpdate;DROP TRIGGER IF EXISTS TR_TruthSampleBatches_NoDelete;DROP TABLE TruthSampleBatches;CREATE TABLE TruthSampleBatches(BatchId TEXT PRIMARY KEY,RunId TEXT NOT NULL UNIQUE,WorldId TEXT NOT NULL,StageAPathBindingId TEXT NOT NULL,PropertySetVersion TEXT NOT NULL,SampleCount INTEGER NOT NULL,BindingHash TEXT NOT NULL,CanonicalBindingJson TEXT NOT NULL,BindingRequestHash TEXT NOT NULL,SamplingOptionsHash TEXT NOT NULL,CanonicalResponseJson TEXT NOT NULL,ResponseHash TEXT NOT NULL,CreatedUtc TEXT NOT NULL,FOREIGN KEY(RunId)REFERENCES Runs(RunId));INSERT INTO TruthSampleBatches(BatchId,RunId,WorldId,StageAPathBindingId,PropertySetVersion,SampleCount,BindingHash,CanonicalBindingJson,BindingRequestHash,SamplingOptionsHash,CanonicalResponseJson,ResponseHash,CreatedUtc)VALUES($batch,$run,$world,$binding,$version,1,$bindingHash,$bindingJson,$requestHash,$optionsHash,$response,$responseHash,$created);";command.Parameters.AddWithValue("$batch","legacy-batch");command.Parameters.AddWithValue("$run",run.RunId);command.Parameters.AddWithValue("$world","world-opaque-17");command.Parameters.AddWithValue("$binding","legacy-stage-a-binding");command.Parameters.AddWithValue("$version","stage-b-truth-v1");command.Parameters.AddWithValue("$bindingHash",TestData.HashA);command.Parameters.AddWithValue("$bindingJson","{}");command.Parameters.AddWithValue("$requestHash",TestData.HashB);command.Parameters.AddWithValue("$optionsHash",TestData.HashC);command.Parameters.AddWithValue("$response","{}");command.Parameters.AddWithValue("$responseHash",TestData.HashD);command.Parameters.AddWithValue("$created",DateTimeOffset.UtcNow.ToString("O"));await command.ExecuteNonQueryAsync();}
  var restarted=new DrillingOperationsStore(fixture.ConnectionString,TimeProvider.System);Assert.DoesNotThrowAsync(async()=>await restarted.InitializeAsync());
  await using(var connection=new SqliteConnection(fixture.ConnectionString)){await connection.OpenAsync();var columns=new HashSet<string>();await using(var schema=connection.CreateCommand()){schema.CommandText="PRAGMA table_info(TruthSampleBatches)";await using var reader=await schema.ExecuteReaderAsync();while(await reader.ReadAsync())columns.Add(reader.GetString(1));}await using var count=connection.CreateCommand();count.CommandText="SELECT COUNT(*) FROM AuditEntries";Assert.Multiple(()=>{Assert.That(columns,Does.Contain("ScenarioId"));Assert.That(columns,Does.Contain("CanonicalBindingRequestJson"));Assert.That(columns,Does.Contain("CanonicalSamplingOptionsJson"));Assert.That(Convert.ToInt32(count.ExecuteScalar()),Is.EqualTo(auditBefore));});}
  PersistenceIntegrityException error=Assert.ThrowsAsync<PersistenceIntegrityException>(async()=>await restarted.GetTruthSampleBatchAsync(run.RunId))!;Assert.That(error.Message,Does.Contain("predates required provenance").And.Contain("new scenario and run"));
 }
 [Test] public async Task Failure_IsAttributedToFirstIncompleteAttemptedStage_NotPreviousCurrentStage()
 {
  await using var fixture=new StoreFixture();await fixture.InitializeAsync();RunResponse run=await StoreFixture.BindAndCreateAsync(fixture.Store,suffix:"stage-attribution");await using(var connection=new SqliteConnection(fixture.ConnectionString)){await connection.OpenAsync();await using var command=connection.CreateCommand();command.CommandText="UPDATE RunStages SET Status=$completed WHERE RunId=$run AND Stage<=$s4;UPDATE Runs SET Status=$running,CurrentStage=$s4 WHERE RunId=$run;";command.Parameters.AddWithValue("$completed",StageStatus.Completed.ToString());command.Parameters.AddWithValue("$run",run.RunId);command.Parameters.AddWithValue("$s4",(int)RunStageKind.S4SampleGeology);command.Parameters.AddWithValue("$running",RunStatus.Running.ToString());await command.ExecuteNonQueryAsync();}
  var orchestrator=new RunOrchestrator(fixture.Store,new FailingCheckpointExecutor(),NullLogger<RunOrchestrator>.Instance);await orchestrator.ResumeAllAsync();RunResponse failed=(await fixture.Store.GetRunAsync(run.RunId))!;IReadOnlyList<StageResponse> stages=await fixture.Store.GetStagesAsync(run.RunId);Assert.Multiple(()=>{Assert.That(failed.Status,Is.EqualTo(RunStatus.Failed));Assert.That(failed.CurrentStage,Is.EqualTo(RunStageKind.S5GenerateLogs));Assert.That(stages.Single(x=>x.Stage==RunStageKind.S4SampleGeology).Status,Is.EqualTo(StageStatus.Completed));Assert.That(stages.Single(x=>x.Stage==RunStageKind.S5GenerateLogs).Status,Is.EqualTo(StageStatus.Failed));Assert.That(stages.Single(x=>x.Stage==RunStageKind.S5GenerateLogs).DiagnosticCode,Is.EqualTo("S5Poison"));});
 }
 private sealed class FailingCheckpointExecutor:IRunCheckpointExecutor{public Task<bool> AdvanceOneAsync(string runId,CancellationToken cancellationToken)=>throw new RunStageFailureException("S5Poison","Synthetic S5 failure.");}
}


