using System.Net;using System.Net.Http.Json;using System.Text.Json;using Microsoft.Extensions.DependencyInjection;using Microsoft.Data.Sqlite;using Microsoft.Extensions.Http.Resilience;using Microsoft.Extensions.Options;using Polly.Timeout;namespace DrillingOperations.Tests;
[TestFixture]public sealed class ProductionOptionsTests{
[Test]public void DefaultSchedule_IsContiguousFiveYearsAndHasShutInRestartAndControlChange(){var o=new ProductionExecutionOptions();o.Validate();Assert.Multiple(()=>{Assert.That(o.Schedule[0].StartTimeSeconds,Is.Zero);Assert.That(o.Schedule.Zip(o.Schedule.Skip(1),(a,b)=>a.StartTimeSeconds+a.DurationSeconds==b.StartTimeSeconds).All(x=>x),Is.True);Assert.That(o.Schedule.Sum(x=>x.DurationSeconds),Is.EqualTo(5*ProductionExecutionOptions.YearSeconds));Assert.That(o.Schedule.Any(x=>x.ShutIn),Is.True);Assert.That(o.Schedule.Zip(o.Schedule.Skip(1),(a,b)=>a.ControlMode!=b.ControlMode).Any(x=>x),Is.True);});}
[Test]public void DefaultV2CalibrationSchedule_IsExactFullGridGolden(){double y=ProductionExecutionOptions.YearSeconds,d=45*ProductionExecutionOptions.DaySeconds,r=ProductionExecutionOptions.CalibratedProductionRateM3PerSecond;var o=new ProductionExecutionOptions();ProductionScheduleSegment[] expected=[new(0,d,false,"Rate",-r,1e6,.1e6,50e6,r),new(d,y-d,true,"Rate",0,1e6,.1e6,50e6,r),new(y,d,false,"Bhp",0,1e6,.1e6,50e6,r),new(y+d,2*y-d,true,"Rate",0,1e6,.1e6,50e6,r),new(3*y,d,false,"Rate",-r,1e6,.1e6,50e6,r),new(3*y+d,2*y-d,true,"Rate",0,1e6,.1e6,50e6,r)];Assert.Multiple(()=>{Assert.That(o.CalibrationVersion,Is.EqualTo("production-calibration-default-v2"));Assert.That(o.ModelVersion,Is.EqualTo("completion-production-v1"));Assert.That(r,Is.EqualTo(8e-9));Assert.That(o.InitialTimeStepSeconds,Is.EqualTo(d));Assert.That(o.Solver.MaximumTimeStepSeconds,Is.EqualTo(y));Assert.That(o.Solver.CgRelativeTolerance,Is.EqualTo(1e-6));Assert.That(o.Solver.MaximumSamplesPerWell,Is.EqualTo(120));Assert.That(o.Schedule,Is.EqualTo(expected));});}
[Test]public void CalibratedMicroRateValidation_AllowsBoundedProductionAndRejectsZeroOrBelowFloor(){double y=ProductionExecutionOptions.YearSeconds;Assert.DoesNotThrow(()=>new ProductionExecutionOptions().Validate());Assert.Throws<Microsoft.Extensions.Options.OptionsValidationException>(()=>new ProductionExecutionOptions{Schedule=[new(0,y,false,"Rate",0,1e6,.1e6,50e6,8e-9),new(y,y,true,"Rate",0,1e6,.1e6,50e6,8e-9),new(2*y,y,false,"Bhp",0,1e6,.1e6,50e6,8e-9),new(3*y,2*y,true,"Rate",0,1e6,.1e6,50e6,8e-9)]}.Validate());Assert.Throws<Microsoft.Extensions.Options.OptionsValidationException>(()=>new ProductionExecutionOptions{Schedule=new ProductionExecutionOptions().Schedule.Select(x=>x with{MaximumAbsoluteRateM3PerSecond=1e-13}).ToArray()}.Validate());}
[Test]public void InvalidSchedulesAndBudgetsFail(){Assert.Throws<Microsoft.Extensions.Options.OptionsValidationException>(()=>new ProductionExecutionOptions{InitialTimeStepSeconds=0}.Validate());Assert.Throws<Microsoft.Extensions.Options.OptionsValidationException>(()=>new ProductionExecutionOptions{Schedule=[new(0,5*ProductionExecutionOptions.YearSeconds,false,"Rate",.01,20e6,5e6,50e6,.03)]}.Validate());}
[Test]public void CalibrationChangesOptionsHashButNotStageAWireContract(){var a=new ProductionExecutionOptions();var b=new ProductionExecutionOptions{CalibrationVersion="other-calibration"};Assert.Multiple(()=>{Assert.That(a.CanonicalJson(),Is.EqualTo(b.CanonicalJson()));Assert.That(a.Hash(),Is.Not.EqualTo(b.Hash()));Assert.That(a.CanonicalJson(),Does.Contain("productionModelVersion").And.Contain("initialTimeStepSeconds").And.Contain("solver"));});}}
[TestFixture,NonParallelizable]public sealed class ProductionTransportTests{[Test]public void ProductionClient_HasDedicatedFiveMinutePipeline_WhileOtherClientsKeepDefaults(){using var f=new ApiFactory();_ = f.CreateInternalClient();var options=f.Services.GetRequiredService<IOptionsMonitor<HttpStandardResilienceOptions>>();string production=nameof(ReservoirProductionClient)+"-standard",analysis=nameof(AnalysisVerificationClient)+"-standard";HttpStandardResilienceOptions p=options.Get(production),a=options.Get(analysis);HttpClient client=f.Services.GetRequiredService<IHttpClientFactory>().CreateClient(nameof(ReservoirProductionClient));Assert.Multiple(()=>{Assert.That(p.TotalRequestTimeout.Timeout,Is.EqualTo(TimeSpan.FromMinutes(5)));Assert.That(p.AttemptTimeout.Timeout,Is.EqualTo(TimeSpan.FromMinutes(5)));Assert.That(p.Retry.MaxRetryAttempts,Is.EqualTo(1));Assert.That(client.Timeout,Is.EqualTo(Timeout.InfiniteTimeSpan));Assert.That(a.TotalRequestTimeout.Timeout,Is.EqualTo(TimeSpan.FromSeconds(30)));Assert.That(a.AttemptTimeout.Timeout,Is.EqualTo(TimeSpan.FromSeconds(10)));});}}
[TestFixture]public sealed class ProductionClientTests{
[TestCase("world")][TestCase("binding")][TestCase("model")][TestCase("parent")][TestCase("time")][TestCase("balance")][TestCase("cumulative")][TestCase("negative")][TestCase("month")][TestCase("mode")]
public void StageAProduction_FailsClosedOnMismatch(string mode){var client=Client(mode);ProductionUpstreamException e=Assert.ThrowsAsync<ProductionUpstreamException>(async()=>await client.RunAsync(Binding(),Design(),new(),CancellationToken.None))!;Assert.That(e.DiagnosticCode,Is.EqualTo("ProductionValidationMismatch"));}
[TestCase(HttpStatusCode.BadGateway,502,"ProductionUnavailable")][TestCase(HttpStatusCode.ServiceUnavailable,503,"ProductionUnavailable")][TestCase(HttpStatusCode.Conflict,409,"ProductionRejected")]
public void StageAProduction_MapsStatusExactly(HttpStatusCode status,int expected,string code){var c=new ReservoirProductionClient(new HttpClient(new DelegateHandler(_=>TestData.Json(status,new{}))){BaseAddress=new Uri("http://stage-a/")});var e=Assert.ThrowsAsync<ProductionUpstreamException>(async()=>await c.RunAsync(Binding(),Design(),new(),CancellationToken.None))!;Assert.Multiple(()=>{Assert.That(e.StatusCode,Is.EqualTo(expected));Assert.That(e.DiagnosticCode,Is.EqualTo(code));});}
[Test]public void PollyTimeout_IsMappedButCallerCancellationPropagates(){var timed=new ReservoirProductionClient(new HttpClient(new DelegateHandler(_=>throw new TimeoutRejectedException())){BaseAddress=new Uri("http://stage-a/")});var timeout=Assert.ThrowsAsync<ProductionUpstreamException>(async()=>await timed.RunAsync(Binding(),Design(),new(),CancellationToken.None))!;var taskCanceledClient=new ReservoirProductionClient(new HttpClient(new DelegateHandler(_=>throw new TaskCanceledException())){BaseAddress=new Uri("http://stage-a/")});var taskTimeout=Assert.ThrowsAsync<ProductionUpstreamException>(async()=>await taskCanceledClient.RunAsync(Binding(),Design(),new(),CancellationToken.None))!;using var source=new CancellationTokenSource();source.Cancel();var canceled=new ReservoirProductionClient(new HttpClient(new DelegateHandler(_=>TestData.Json(HttpStatusCode.OK,new{}))){BaseAddress=new Uri("http://stage-a/")});Assert.Multiple(()=>{Assert.That(timeout.StatusCode,Is.EqualTo(503));Assert.That(timeout.DiagnosticCode,Is.EqualTo("ProductionTimeout"));Assert.That(taskTimeout.StatusCode,Is.EqualTo(503));Assert.That(taskTimeout.DiagnosticCode,Is.EqualTo("ProductionTimeout"));Assert.CatchAsync<OperationCanceledException>(async()=>await canceled.RunAsync(Binding(),Design(),new(),source.Token));});}
[Test]public async Task DefaultRequestFixture_MatchesExactSixSegmentStageAContract(){string? actual=null;var client=new ReservoirProductionClient(new HttpClient(new DelegateHandler(request=>{actual=request.Content!.ReadAsStringAsync().GetAwaiter().GetResult();return Response("ok");})){BaseAddress=new Uri("http://stage-a/")});await client.RunAsync(Binding(),Design(),new(),CancellationToken.None);double y=ProductionExecutionOptions.YearSeconds,d=45*ProductionExecutionOptions.DaySeconds,r=8e-9;var schedule=new[]{new{startTimeSeconds=0d,durationSeconds=d,shutIn=false,controlMode="Rate",targetRateM3PerSecond=-r,targetBottomHolePressurePa=1e6,minimumBottomHolePressurePa=.1e6,maximumBottomHolePressurePa=50e6,maximumAbsoluteRateM3PerSecond=r},new{startTimeSeconds=d,durationSeconds=y-d,shutIn=true,controlMode="Rate",targetRateM3PerSecond=0d,targetBottomHolePressurePa=1e6,minimumBottomHolePressurePa=.1e6,maximumBottomHolePressurePa=50e6,maximumAbsoluteRateM3PerSecond=r},new{startTimeSeconds=y,durationSeconds=d,shutIn=false,controlMode="Bhp",targetRateM3PerSecond=0d,targetBottomHolePressurePa=1e6,minimumBottomHolePressurePa=.1e6,maximumBottomHolePressurePa=50e6,maximumAbsoluteRateM3PerSecond=r},new{startTimeSeconds=y+d,durationSeconds=2*y-d,shutIn=true,controlMode="Rate",targetRateM3PerSecond=0d,targetBottomHolePressurePa=1e6,minimumBottomHolePressurePa=.1e6,maximumBottomHolePressurePa=50e6,maximumAbsoluteRateM3PerSecond=r},new{startTimeSeconds=3*y,durationSeconds=d,shutIn=false,controlMode="Rate",targetRateM3PerSecond=-r,targetBottomHolePressurePa=1e6,minimumBottomHolePressurePa=.1e6,maximumBottomHolePressurePa=50e6,maximumAbsoluteRateM3PerSecond=r},new{startTimeSeconds=3*y+d,durationSeconds=2*y-d,shutIn=true,controlMode="Rate",targetRateM3PerSecond=0d,targetBottomHolePressurePa=1e6,minimumBottomHolePressurePa=.1e6,maximumBottomHolePressurePa=50e6,maximumAbsoluteRateM3PerSecond=r}};string expected=CanonicalJson.Serialize(new{productionModelVersion="completion-production-v1",schedule,initialTimeStepSeconds=d,solver=new{minimumTimeStepSeconds=60d,maximumTimeStepSeconds=y,maximumSaturationChange=.05,growthSaturationChange=.005,timeStepGrowthFactor=1.5,timeStepShrinkFactor=.5,cgRelativeTolerance=1e-6,cgMaximumIterations=1000,maximumStepAttempts=10000,maximumSamplesPerWell=120}});Assert.That(actual,Is.EqualTo(expected));}
[Test]public async Task StageAProduction_AcceptsStrictSixtyMonthResponse(){var result=await Client("ok").RunAsync(Binding(),Design(),new(),CancellationToken.None);Assert.Multiple(()=>{Assert.That(result.Response.MonthlyTruth,Has.Count.EqualTo(60));Assert.That(result.Response.Checkpoints.Select(x=>x.Year),Is.EqualTo(new[]{1,3,5}));Assert.That(result.RequestHash,Is.EqualTo(DeterministicIdentity.Sha256(result.RequestJson)));});}
static ReservoirProductionClient Client(string mode)=>new(new HttpClient(new DelegateHandler(_=>Response(mode))){BaseAddress=new Uri("http://stage-a/")});
internal static HttpResponseMessage Response(string mode,string completionBindingId="completion-1"){var cp=new[]{new ProductionCheckpoint(1,mode=="time"?1:ProductionExecutionOptions.YearSeconds,"s1",null,new(100,20,5),mode=="balance"?.01:1e-8),new ProductionCheckpoint(3,3*ProductionExecutionOptions.YearSeconds,"s3",mode=="parent"?"bad":"s1",new(mode=="cumulative"?50:300,60,15),1e-8),new ProductionCheckpoint(5,5*ProductionExecutionOptions.YearSeconds,"s5","s3",new(500,100,25),1e-8)};var months=Enumerable.Range(1,60).Select(m=>new MonthlyProductionTruth(mode=="month"&&m==20?21:m,m*ProductionExecutionOptions.YearSeconds/12,mode=="negative"&&m==1?-.001:.001,.0002,.00005,m*10,m*2,m*.5,15e6,mode=="mode"?"Unknown":"Rate","None")).ToArray();return TestData.Json(HttpStatusCode.OK,new ProductionRunResponse("production-1",mode=="world"?"bad":"world-opaque-17",mode=="binding"?"bad":completionBindingId,mode=="model"?"bad":"completion-production-v1",cp,months));}
static TruthBindingResponse Binding()=>new("binding",TestData.ScenarioId,TestData.HashA,TestData.HashB,"world-opaque-17","world-v1","cal",TestData.HashC,DateTimeOffset.UtcNow);
static CompletionDesign Design()=>new("design","55555555-5555-4555-8555-555555555555",TestData.ScenarioId,"log","hash","R","observed-log-completion-v1","cal","{}",TestData.HashA,"{}",TestData.HashB,[],TestData.HashC,new("completion-1","world-opaque-17","path",Guid.Parse(TestData.ScenarioId),Guid.Parse("55555555-5555-4555-8555-555555555555"),"observed-log-completion-v1",1,2,TestData.HashD,DateTimeOffset.UtcNow),TestData.HashA,"Approved",DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,"actor");}
[TestFixture]public sealed class ProductionMeterTests{static MonthlyProductionTruth[] Truth()=>Enumerable.Range(1,60).Select(m=>new MonthlyProductionTruth(m,m,1,1,1,m*100,m*25,m*10,1,"Rate","None")).ToArray();
[Test]public void Meter_IsDeterministicBoundedAndContainsNoTruthContract(){var o=new ProductionMeterOptions{OilPrecisionFraction=0,WaterPrecisionFraction=0,GasPrecisionFraction=0,DowntimeProbability=0,MissingMonthProbability=0};var a=DeterministicProductionMeter.Generate("run",Truth(),o);var b=DeterministicProductionMeter.Generate("run",Truth(),o);string json=CanonicalJson.Serialize(a);Assert.Multiple(()=>{Assert.That(CanonicalJson.Serialize(a),Is.EqualTo(CanonicalJson.Serialize(b)));Assert.That(a.Item1,Has.Count.EqualTo(60));Assert.That(a.Item2.Select(x=>x.Label),Is.EqualTo(new[]{"Y1","Y3","Y5"}));Assert.That(a.Item1.Where(x=>x.CumulativeCorrectedOilM3.HasValue).Select(x=>x.CumulativeCorrectedOilM3),Is.Ordered);Assert.That(json,Does.Not.Contain("bottomHolePressure").And.Not.Contain("effectiveControlMode").And.Not.Contain("oilRate"));});}
[Test]public void BiasCorrectionBreakthroughAndCalibrationAreObservable(){var o=new ProductionMeterOptions{OilBiasFraction=.1,WaterBiasFraction=0,GasBiasFraction=0,OilPrecisionFraction=0,WaterPrecisionFraction=0,GasPrecisionFraction=0,OilSeparatorCorrection=.5,WaterSeparatorCorrection=1,GasSeparatorCorrection=1,DowntimeProbability=0,MissingMonthProbability=0,WaterBreakthroughFraction=.1,GasBreakthroughFraction=.01};var a=DeterministicProductionMeter.Generate("run",Truth(),o);Assert.Multiple(()=>{Assert.That(a.Item1[0].ReportedOilM3,Is.EqualTo(110).Within(1e-10));Assert.That(a.Item1[0].CorrectedOilM3,Is.EqualTo(55).Within(1e-10));Assert.That(a.Item3,Is.EqualTo(1));Assert.That(a.Item4,Is.EqualTo(1));var changed=DeterministicProductionMeter.Generate("run",Truth(),new ProductionMeterOptions{CalibrationVersion="changed"});Assert.That(CanonicalJson.Serialize(changed.Item1),Is.Not.EqualTo(CanonicalJson.Serialize(a.Item1)));});}
[Test]public void MissingAndDowntimeUseNullableValuesAndBoundedRuns(){var missing=DeterministicProductionMeter.Generate("r",Truth(),new ProductionMeterOptions{MissingMonthProbability=1,DowntimeProbability=0});var down=DeterministicProductionMeter.Generate("r",Truth(),new ProductionMeterOptions{MissingMonthProbability=0,DowntimeProbability=1,MaximumConsecutiveDowntimeMonths=2});Assert.Multiple(()=>{Assert.That(missing.Item1.All(x=>x.ReportedOilM3 is null&&x.Qc=="Missing"),Is.True);Assert.That(down.Item1.All(x=>x.Qc=="Downtime"&&x.ReportedOilM3==0),Is.True);Assert.That(down.Item5.DowntimeMonths,Is.EqualTo(60));});}}
[TestFixture,NonParallelizable]public sealed class ProductionWorkflowTests{
[Test]public async Task ApprovedRun_PersistsTruthAndObservableSeries_RestartsAndDoesNotLeak(){await using var f=new ApiFactory();using var c=f.CreateInternalClient();RunResponse run=await CreateAndApprove(c);await Wait(c,run.RunId,x=>x.Status==RunStatus.ReadyToReveal&&x.CurrentStage==RunStageKind.S7RunProduction);var store=f.Services.GetRequiredService<DrillingOperationsStore>();var series=(await store.GetProductionSeriesAsync(run.RunId))!;var noCallClient=new ReservoirProductionClient(new HttpClient(new DelegateHandler(_=>throw new AssertionException("Completed S7 called upstream."))){BaseAddress=new Uri("http://unused/")});Assert.That(await store.ExecuteProductionAsync(run.RunId,new(),new(),noCallClient),Is.False);Assert.Multiple(()=>{Assert.That(series.Months,Has.Count.EqualTo(60));Assert.That(series.Checkpoints.Select(x=>x.Label),Is.EqualTo(new[]{"Y1","Y3","Y5"}));Assert.That(store.GetProductionTruthAsync(run.RunId).Result,Is.Not.Null);});var restart=new DrillingOperationsStore($"Data Source={f.DatabasePath}",TimeProvider.System);await restart.InitializeAsync();Assert.That(CanonicalJson.Serialize(await restart.GetProductionSeriesAsync(run.RunId)),Is.EqualTo(CanonicalJson.Serialize(series)));string api=await c.GetStringAsync($"/drillingoperations/api/runs/{run.RunId}")+await c.GetStringAsync($"/drillingoperations/api/runs/{run.RunId}/events")+await c.GetStringAsync($"/drillingoperations/api/audit?scenarioId={TestData.ScenarioId}");var sideEffects=await store.GetSideEffectCountsAsync(run.RunId);Assert.Multiple(()=>{Assert.That(api,Does.Not.Contain("oilRateM3PerSecond").And.Not.Contain("bottomHolePressurePa").And.Not.Contain("reportedOilM3").And.Not.Contain("cumulativeCorrectedOilM3"));Assert.That(sideEffects,Is.EqualTo((0,0)));});await using var db=new SqliteConnection($"Data Source={f.DatabasePath}");await db.OpenAsync();await using(var immutable=db.CreateCommand()){immutable.CommandText="UPDATE ProductionSeries SET OptionsHash=$hash WHERE RunId=$run";immutable.Parameters.AddWithValue("$hash",TestData.HashA);immutable.Parameters.AddWithValue("$run",run.RunId);Assert.ThrowsAsync<SqliteException>(async()=>await immutable.ExecuteNonQueryAsync());}await using(var tamper=db.CreateCommand()){tamper.CommandText="DROP TRIGGER TR_ProductionSeries_NoUpdate;UPDATE ProductionSeries SET OptionsHash=$hash WHERE RunId=$run;DROP TRIGGER TR_ProductionTruth_NoUpdate;UPDATE ProductionTruthArtifacts SET RequestHash=$hash WHERE RunId=$run";tamper.Parameters.AddWithValue("$hash",TestData.HashA);tamper.Parameters.AddWithValue("$run",run.RunId);await tamper.ExecuteNonQueryAsync();}Assert.Multiple(()=>{Assert.ThrowsAsync<PersistenceIntegrityException>(async()=>await restart.GetProductionSeriesAsync(run.RunId));Assert.ThrowsAsync<PersistenceIntegrityException>(async()=>await restart.GetProductionTruthAsync(run.RunId));});}
[Test]public async Task UnavailableProduction_ResumesWithoutDuplicateArtifacts(){int calls=0;Func<HttpRequestMessage,HttpResponseMessage> responder=_=>calls++==0?TestData.Json(HttpStatusCode.ServiceUnavailable,new{}):ProductionClientTests.Response("ok","completion-binding-1");await using var f=new ApiFactory(productionResponder:responder);using var c=f.CreateInternalClient();RunResponse run=await CreateAndApprove(c);await Wait(c,run.RunId,x=>x.Status==RunStatus.AwaitingDependency&&x.CurrentStage==RunStageKind.S7RunProduction);using var resume=new HttpRequestMessage(HttpMethod.Post,$"/drillingoperations/api/runs/{run.RunId}/resume");resume.Headers.Add("Idempotency-Key","resume-production");Assert.That((await c.SendAsync(resume)).StatusCode,Is.EqualTo(HttpStatusCode.Accepted));await Wait(c,run.RunId,x=>x.Status==RunStatus.ReadyToReveal&&x.CurrentStage==RunStageKind.S7RunProduction);await using var db=new SqliteConnection($"Data Source={f.DatabasePath}");await db.OpenAsync();await using var count=db.CreateCommand();count.CommandText="SELECT (SELECT COUNT(*) FROM ProductionTruthArtifacts WHERE RunId=$run),(SELECT COUNT(*) FROM ProductionSeries WHERE RunId=$run)";count.Parameters.AddWithValue("$run",run.RunId);await using var reader=await count.ExecuteReaderAsync();await reader.ReadAsync();Assert.Multiple(()=>{Assert.That(reader.GetInt32(0),Is.EqualTo(1));Assert.That(reader.GetInt32(1),Is.EqualTo(1));Assert.That(calls,Is.EqualTo(2));});}[TestCase("unavailable",RunStatus.AwaitingDependency)][TestCase("malformed",RunStatus.Failed)]public async Task UpstreamFailuresRemainAtS7AndDoNotPublish(string mode,RunStatus expected){Func<HttpRequestMessage,HttpResponseMessage> responder=_=>mode=="unavailable"?TestData.Json(HttpStatusCode.ServiceUnavailable,new{}):new(HttpStatusCode.OK){Content=new StringContent("{")};await using var f=new ApiFactory(productionResponder:responder);using var c=f.CreateInternalClient();RunResponse run=await CreateAndApprove(c);RunResponse final=await Wait(c,run.RunId,x=>x.Status==expected&&x.CurrentStage==RunStageKind.S7RunProduction);Assert.That(final.CurrentStage,Is.EqualTo(RunStageKind.S7RunProduction));Assert.That(await f.Services.GetRequiredService<DrillingOperationsStore>().GetSideEffectCountsAsync(run.RunId),Is.EqualTo((0,0)));}
static async Task<RunResponse>CreateAndApprove(HttpClient c){using var bind=new HttpRequestMessage(HttpMethod.Post,$"/drillingoperations/api/scenarios/{TestData.ScenarioId}/bind"){Content=JsonContent.Create(TestData.Binding())};bind.Headers.Add("Idempotency-Key",Guid.NewGuid().ToString());(await c.SendAsync(bind)).EnsureSuccessStatusCode();using var create=new HttpRequestMessage(HttpMethod.Post,"/drillingoperations/api/runs"){Content=JsonContent.Create(TestData.Run())};create.Headers.Add("Idempotency-Key",Guid.NewGuid().ToString());var response=await c.SendAsync(create);var run=JsonSerializer.Deserialize<RunResponse>(await response.Content.ReadAsStringAsync(),CanonicalJson.SerializerOptions)!;await Wait(c,run.RunId,x=>x.Status==RunStatus.AwaitingApproval);using var approve=new HttpRequestMessage(HttpMethod.Post,$"/drillingoperations/api/runs/{run.RunId}/completion/approve");approve.Headers.Add("Idempotency-Key",Guid.NewGuid().ToString());approve.Headers.Add("X-DrillSim-Human-Actor","production-test");(await c.SendAsync(approve)).EnsureSuccessStatusCode();return run;}static async Task<RunResponse>Wait(HttpClient c,string id,Func<RunResponse,bool> done){for(int i=0;i<400;i++){var x=(await c.GetFromJsonAsync<RunResponse>($"/drillingoperations/api/runs/{id}",CanonicalJson.SerializerOptions))!;if(done(x))return x;await Task.Delay(20);}throw new AssertionException("Run timeout.");}}














