using System.Collections.Concurrent;
using System.Net;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace DrillingOperations.Tests;

internal sealed class PublicationFakeHandler : HttpMessageHandler
{
 readonly ConcurrentDictionary<string,string> _entities=new(StringComparer.OrdinalIgnoreCase);
 readonly ConcurrentDictionary<string,(Guid ScenarioId,Guid RevealId)> _markers=new(StringComparer.OrdinalIgnoreCase);
 internal HttpStatusCode WriteFailureStatus=HttpStatusCode.ServiceUnavailable;
 internal Func<HttpRequestMessage,HttpResponseMessage?>? RecoveryReadOverride;
 internal Func<AnalysisScorecardRequest,HttpResponseMessage>? CorrectedScorecardResponder {get;set;}
 internal HttpStatusCode? ScorecardRejectStatus {get;set;}
 string? _scorecardReceipt;
 readonly AnalysisPackageDocument _source;
 internal int CallbackCount;internal int PrepareCount;internal int FinalizeCount;internal int BackfillCount;internal int ScorecardCount;internal int StageCount;internal int PackageReadCount;internal int ExistingWriteConflictCount;internal int TrajectoryReadWithoutStationsCount;internal int WriteCount;internal int ActivationCount;internal JsonElement? CallbackBody;internal string? CallbackKey;internal int? FailWriteSequence;internal int? FailActivationSequence;internal bool CallbackUnavailable;internal bool FinalizeUnavailable;internal bool FinalizeMismatch;internal bool CallbackMismatch;internal bool ReadBackMismatch;internal bool ScenarioWellMismatch;internal bool SourceUnavailable;internal bool PreflightIdentityConflict;internal bool ScorecardUnavailable;internal bool ScorecardMismatch;internal bool ReconciliationMismatch;internal bool RemoveScenarioGeologyOnReconciliation;internal bool RemoveFieldOnReconciliation;internal JsonElement? ScorecardBody;bool _finalized;
 internal PublicationFakeHandler()
 {
  AnalysisPackageDocument source=BuildSource();
  JsonObject field=(JsonObject)JsonNode.Parse(source.Field.GetRawText())!;
  JsonObject origin=(JsonObject)field.First(x=>x.Key.Equals("ReferencePoint",StringComparison.OrdinalIgnoreCase)).Value!;
  origin["RiemannianNorth"]=6700000d;origin["RiemannianEast"]=480000d;
  _source=source with {Field=JsonSerializer.SerializeToElement(field,CanonicalJson.SerializerOptions)};
 }
 internal AnalysisPackageDocument Source=>_source;internal IReadOnlyCollection<string> PublishedPayloads=>_entities.Values.ToArray();internal bool RecordsPublic=>_finalized;internal void NormalizeStoredFieldCoordinates(){string key=_entities.Keys.Single(x=>x.StartsWith("/field/api/Field/",StringComparison.OrdinalIgnoreCase));JsonNode node=JsonNode.Parse(_entities[key])!;Normalize(node);_entities[key]=CanonicalJson.Canonicalize(JsonDocument.Parse(node.ToJsonString()).RootElement);static void Normalize(JsonNode? value){if(value is JsonObject obj)foreach(var pair in obj.ToArray()){if(pair.Key.Equals("Latitude",StringComparison.OrdinalIgnoreCase))obj[pair.Key]=1.063747450603627d;else if(pair.Key.Equals("Longitude",StringComparison.OrdinalIgnoreCase))obj[pair.Key]=-0.124567890123457d;else Normalize(pair.Value);}else if(value is JsonArray array)foreach(var item in array)Normalize(item);}}
 internal int GeologicalPropertiesCount=>_entities.Keys.Count(x=>x.StartsWith("/geologicalproperties/api/GeologicalProperties/",StringComparison.OrdinalIgnoreCase));
 internal int WellCount=>_entities.Keys.Count(x=>x.StartsWith("/well/api/Well/",StringComparison.OrdinalIgnoreCase));
 internal int WellBoreCount=>_entities.Keys.Count(x=>x.StartsWith("/wellbore/api/WellBore/",StringComparison.OrdinalIgnoreCase));
 internal void RemoveScenarioGeology(){string key=_entities.Single(x=>x.Key.StartsWith("/geologicalproperties/api/GeologicalProperties/",StringComparison.OrdinalIgnoreCase)&&x.Value.Contains("Petrophysics",StringComparison.OrdinalIgnoreCase)).Key;_entities.TryRemove(key,out _);}
 internal void RemovePublishedField(){string key=_entities.Keys.Single(x=>x.StartsWith("/field/api/Field/",StringComparison.OrdinalIgnoreCase));_entities.TryRemove(key,out _);}
 internal void CorruptScenarioGeology(){string key=_entities.Single(x=>x.Key.StartsWith("/geologicalproperties/api/GeologicalProperties/",StringComparison.OrdinalIgnoreCase)&&x.Value.Contains("Petrophysics",StringComparison.OrdinalIgnoreCase)).Key;JsonObject value=(JsonObject)JsonNode.Parse(_entities[key])!;value["UnexpectedNonNull"]="material";_entities[key]=CanonicalJson.Canonicalize(JsonDocument.Parse(value.ToJsonString()).RootElement);}
 internal void NormalizeStoredScenarioWell(){string key=_entities.Single(x=>x.Key.StartsWith("/well/api/Well/",StringComparison.OrdinalIgnoreCase)&&IsScenarioWell(x.Value)).Key;JsonObject well=(JsonObject)JsonNode.Parse(_entities[key])!;JsonObject dataset=(JsonObject)well.First(x=>x.Key.Equals("Dataset",StringComparison.OrdinalIgnoreCase)).Value!;foreach(JsonObject lifecycle in ((JsonArray)dataset.First(x=>x.Key.Equals("LifecycleEvents",StringComparison.OrdinalIgnoreCase)).Value!).OfType<JsonObject>()){Offset(lifecycle,"EffectiveAt");Offset(lifecycle,"FirstSeenAt");lifecycle["SourceArtifactID"]=null;}foreach(JsonObject month in ((JsonArray)dataset.First(x=>x.Key.Equals("MonthlyProduction",StringComparison.OrdinalIgnoreCase)).Value!).OfType<JsonObject>())month["SourceArtifactID"]=null;_entities[key]=CanonicalJson.Canonicalize(JsonDocument.Parse(well.ToJsonString()).RootElement);static void Offset(JsonObject value,string name){string? key=value.Select(x=>x.Key).FirstOrDefault(x=>x.Equals(name,StringComparison.OrdinalIgnoreCase));if(key is null||value[key]?.GetValue<string>() is not string text)return;value[key]=DateTimeOffset.Parse(text,System.Globalization.CultureInfo.InvariantCulture).ToOffset(TimeSpan.FromHours(-5)).ToString("yyyy-MM-dd'T'HH:mm:sszzz",System.Globalization.CultureInfo.InvariantCulture);}}
 static bool IsScenarioWell(string json){using var document=JsonDocument.Parse(json);return PublicationJson.TryProperty(document.RootElement,"Dataset",out var dataset)&&PublicationJson.TryProperty(dataset,"MonthlyProduction",out var months)&&months.ValueKind==JsonValueKind.Array&&months.GetArrayLength()==60;}
 protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct)
 {
  string path=request.RequestUri!.AbsolutePath;
  if(request.Method==HttpMethod.Get&&RecoveryReadOverride?.Invoke(request) is { } overridden)return overridden;
  if(request.Method==HttpMethod.Get&&path==$"/api/scenarios/{TestData.ScenarioId}")return TestData.Json(HttpStatusCode.OK,new{scenarioId=TestData.ScenarioId,status=_finalized?"Revealed":"HumanApproved",initialAsOfUtc=DateTimeOffset.Parse("2025-01-01T00:00:00Z"),asOfUtc=_finalized?CallbackBody!.Value.GetProperty("validTimeUtc").GetDateTimeOffset():DateTimeOffset.Parse("2025-01-01T00:00:00Z"),clonedFieldId=_finalized?CallbackBody!.Value.GetProperty("clonedFieldId").GetGuid():(Guid?)null,scoringModelVersion=ScoreArtifactIntegrity.ModelVersion});
  if(request.Method==HttpMethod.Get&&path==$"/api/scenarios/{TestData.ScenarioId}/scorecard")return _scorecardReceipt is null?new(HttpStatusCode.NotFound):new(HttpStatusCode.OK){Content=new StringContent(_scorecardReceipt,System.Text.Encoding.UTF8,"application/json")};
  if(request.Method==HttpMethod.Post&&path.EndsWith("/scorecard",StringComparison.Ordinal))
  {
   string requestJson=await request.Content!.ReadAsStringAsync(ct);
   var card=JsonSerializer.Deserialize<AnalysisScorecardRequest>(requestJson,CanonicalJson.SerializerOptions)!;
   if(card.Correction is null&&ScorecardRejectStatus is { } rejectedStatus)
   {
    ScorecardCount++;ScorecardBody=JsonDocument.Parse(requestJson).RootElement.Clone();
    return new(rejectedStatus);
   }
   if(card.Correction is not null)
   {
    ScorecardCount++;ScorecardBody=JsonDocument.Parse(requestJson).RootElement.Clone();
    if(CorrectedScorecardResponder is not null)return CorrectedScorecardResponder(card);
    if(ScorecardUnavailable)return new(HttpStatusCode.ServiceUnavailable);
    ScoreMetricContract.ValidateForPublication(card.Metrics);
    var receipt=new AnalysisScorecardReceipt(Guid.Parse(TestData.ScenarioId),Guid.Parse(card.ScorecardId),Guid.Parse(card.RevealId),
     card.ScoringModelVersion,card.InputSha256,card.HeadlineMetric,card.Metrics,card.CreatedValidTimeUtc,null,TestData.HashC){Correction=card.Correction};
    _scorecardReceipt=CanonicalJson.Serialize(receipt);
    return new(HttpStatusCode.OK){Content=new StringContent(_scorecardReceipt,System.Text.Encoding.UTF8,"application/json")};
   }
  }
  if(request.Method==HttpMethod.Get&&path.Contains("/reveal/",StringComparison.Ordinal)&&path.EndsWith("/status",StringComparison.Ordinal))return PrepareCount==0?new(HttpStatusCode.NotFound):Receipt(_finalized?"Revealed":"Prepared",false);
  if(request.Method==HttpMethod.Get&&path.Contains("/internal/publication/records/",StringComparison.Ordinal)){string id=path.Split('/').Last();return _markers.TryGetValue(id,out var marker)?TestData.Json(HttpStatusCode.OK,new{entityId=Guid.Parse(id),marker.ScenarioId,marker.RevealId,state=ActivationCount==0?"Staged":"Activated"}):new(HttpStatusCode.NotFound);}
  if(request.Method==HttpMethod.Put&&path.Contains("/internal/publication/records/",StringComparison.Ordinal)&&path.EndsWith("/stage",StringComparison.Ordinal)){StageCount++;using var document=JsonDocument.Parse(await request.Content!.ReadAsStringAsync(ct));_markers[path.Split('/')[^2]]=(document.RootElement.GetProperty("scenarioId").GetGuid(),document.RootElement.GetProperty("revealId").GetGuid());return TestData.Json(HttpStatusCode.OK,new{});}
  if(request.Method==HttpMethod.Put&&path.Contains("/internal/publication/records/",StringComparison.Ordinal)&&path.EndsWith("/activate",StringComparison.Ordinal)){ActivationCount++;if(FailActivationSequence is int failAt&&ActivationCount>=failAt)return TestData.Json(HttpStatusCode.ServiceUnavailable,new{});return TestData.Json(HttpStatusCode.OK,new{});}
  if(request.Method==HttpMethod.Get&&path==$"/api/fields/{TestData.FieldId:D}/package")return SourceUnavailable?TestData.Json(HttpStatusCode.ServiceUnavailable,new{}):TestData.Json(HttpStatusCode.OK,_source);
  if(request.Method==HttpMethod.Get&&path.StartsWith("/api/fields/",StringComparison.Ordinal)&&path.EndsWith("/package",StringComparison.Ordinal)){PackageReadCount++;if(FinalizeCount==0)return TestData.Json(HttpStatusCode.NotFound,new{});Guid field=Guid.Parse(path.Split('/')[3]);return TestData.Json(HttpStatusCode.OK,BuildClone(field));}
  if(request.Method==HttpMethod.Post&&path.EndsWith("/scorecard",StringComparison.Ordinal)){ScorecardCount++;ScorecardBody=JsonDocument.Parse(await request.Content!.ReadAsStringAsync(ct)).RootElement.Clone();if(ScorecardUnavailable)return TestData.Json(HttpStatusCode.ServiceUnavailable,new{});JsonElement body=ScorecardBody.Value;foreach(JsonElement metric in body.GetProperty("metrics").EnumerateArray()){string? status=metric.GetProperty("status").GetString();bool limitation=metric.TryGetProperty("limitation",out JsonElement limit)&&limit.ValueKind!=JsonValueKind.Null;if(status=="Scored"&&(!metric.TryGetProperty("value",out JsonElement metricValue)||metricValue.ValueKind!=JsonValueKind.Number||!metric.TryGetProperty("unit",out JsonElement metricUnit)||metricUnit.ValueKind!=JsonValueKind.String||string.IsNullOrWhiteSpace(metricUnit.GetString())||limitation))return TestData.Json(HttpStatusCode.Conflict,new{});if(status=="Unavailable"&&!limitation)return TestData.Json(HttpStatusCode.Conflict,new{});}Guid scorecard=body.GetProperty("scorecardId").GetGuid();return TestData.Json(HttpStatusCode.OK,new{scenarioId=Guid.Parse(TestData.ScenarioId),scorecardId=ScorecardMismatch?Guid.NewGuid():scorecard,revealId=body.GetProperty("revealId").GetGuid(),scoringModelVersion=body.GetProperty("scoringModelVersion").GetString(),inputSha256=body.GetProperty("inputSha256").GetString(),headlineMetric=body.GetProperty("headlineMetric").GetString(),metrics=body.GetProperty("metrics"),createdValidTimeUtc=body.GetProperty("createdValidTimeUtc").GetDateTimeOffset(),limitation=(string?)null,contentSha256=TestData.HashC});}
  if(request.Method==HttpMethod.Post&&path.EndsWith("/reveal/prepare",StringComparison.Ordinal)){CallbackCount++;PrepareCount++;CallbackKey=request.Headers.TryGetValues("X-DrillSim-Internal-Key",out var keys)?keys.Single():null;CallbackBody=JsonDocument.Parse(await request.Content!.ReadAsStringAsync(ct)).RootElement.Clone();if(CallbackUnavailable)return TestData.Json(HttpStatusCode.ServiceUnavailable,new{});if(CallbackBody.Value.GetProperty("observationModelVersion").GetString()!="observation-model-v1")return TestData.Json(HttpStatusCode.Conflict,new{});return Receipt("Prepared",CallbackMismatch);}
  if(request.Method==HttpMethod.Post&&path.EndsWith("/reveal/finalize",StringComparison.Ordinal)){FinalizeCount++;if(FinalizeUnavailable)return TestData.Json(HttpStatusCode.ServiceUnavailable,new{});using JsonDocument finalize=JsonDocument.Parse(await request.Content!.ReadAsStringAsync(ct));if(CallbackBody is null||finalize.RootElement.GetProperty("revealId").GetGuid()!=CallbackBody.Value.GetProperty("revealId").GetGuid()||finalize.RootElement.GetProperty("manifestSha256").GetString()!=CallbackBody.Value.GetProperty("manifestSha256").GetString())return TestData.Json(HttpStatusCode.Conflict,new{});if(!FinalizeMismatch)_finalized=true;return Receipt("Revealed",FinalizeMismatch);}
  if(request.Method==HttpMethod.Post&&path.EndsWith("/reveal/snapshot/backfill",StringComparison.Ordinal)){BackfillCount++;CallbackBody=JsonDocument.Parse(await request.Content!.ReadAsStringAsync(ct)).RootElement.Clone();return Receipt("Revealed",false);}
  if(request.Method==HttpMethod.Get&&PreflightIdentityConflict&&!path.EndsWith("/package",StringComparison.Ordinal))return TestData.Json(HttpStatusCode.OK,new{});
  if(request.Method==HttpMethod.Post){WriteCount++;if(FailWriteSequence is int failAt&&WriteCount>=failAt)return TestData.Json(WriteFailureStatus,new{});string json=await request.Content!.ReadAsStringAsync(ct);JsonNode node=JsonNode.Parse(json)!;if(node is JsonObject entity){Set(entity,"CreationDate","2026-01-01T00:00:00+00:00");Set(entity,"LastModificationDate","2026-01-01T00:00:01+00:00");}using var doc=JsonDocument.Parse(node.ToJsonString());Guid id=Id(doc.RootElement);string route=path.Contains("/internal/publication/Trajectory",StringComparison.Ordinal)?"/trajectory/api/Trajectory":path.Contains("/internal/publication/GeologicalProperties",StringComparison.Ordinal)?"/geologicalproperties/api/GeologicalProperties":path.TrimEnd('/'),key=route+"/"+id.ToString("D");if(!_entities.TryAdd(key,CanonicalJson.Canonicalize(doc.RootElement))){ExistingWriteConflictCount++;return TestData.Json(HttpStatusCode.Conflict,new{});}return TestData.Json(HttpStatusCode.OK,new{});}
  if(request.Method==HttpMethod.Get){if(ActivationCount>=_entities.Count&&_entities.Count>0&&RemoveScenarioGeologyOnReconciliation){RemoveScenarioGeology();RemoveScenarioGeologyOnReconciliation=false;}if(ActivationCount>=_entities.Count&&_entities.Count>0&&RemoveFieldOnReconciliation){RemovePublishedField();RemoveFieldOnReconciliation=false;}if(_entities.TryGetValue(path,out var value)){if(ReadBackMismatch)return TestData.Json(HttpStatusCode.OK,new{});if(ScenarioWellMismatch&&IsScenarioWell(value)){JsonObject mismatch=(JsonObject)JsonNode.Parse(value)!;mismatch["UnexpectedNonNull"]="material";return new(HttpStatusCode.OK){Content=new StringContent(mismatch.ToJsonString(),System.Text.Encoding.UTF8,"application/json")};}if(ReconciliationMismatch&&ActivationCount>=_entities.Count&&_entities.Count>0&&path.StartsWith("/geologicalproperties/api/GeologicalProperties/",StringComparison.OrdinalIgnoreCase)&&value.Contains("Petrophysics",StringComparison.OrdinalIgnoreCase)){JsonObject mismatch=(JsonObject)JsonNode.Parse(value)!;mismatch["UnexpectedNonNull"]="material";return new(HttpStatusCode.OK){Content=new StringContent(mismatch.ToJsonString(),System.Text.Encoding.UTF8,"application/json")};}if(path.StartsWith("/trajectory/api/Trajectory/",StringComparison.OrdinalIgnoreCase)&&!request.RequestUri.Query.Contains("includeCalculatedStations=true",StringComparison.OrdinalIgnoreCase)){TrajectoryReadWithoutStationsCount++;JsonObject trajectory=(JsonObject)JsonNode.Parse(value)!;string? stations=trajectory.Select(x=>x.Key).FirstOrDefault(x=>x.Equals("SurveyStationList",StringComparison.OrdinalIgnoreCase));if(stations is not null)trajectory[stations]=null;value=trajectory.ToJsonString();}return new(HttpStatusCode.OK){Content=new StringContent(value,System.Text.Encoding.UTF8,"application/json")};}}
  return TestData.Json(HttpStatusCode.NotFound,new{});
 }
 HttpResponseMessage Receipt(string status,bool mismatch){JsonElement body=CallbackBody!.Value;return TestData.Json(HttpStatusCode.OK,new{scenarioId=Guid.Parse(TestData.ScenarioId),revealId=body.GetProperty("revealId").GetGuid(),clonedFieldId=body.GetProperty("clonedFieldId").GetGuid(),asOfUtc=body.GetProperty("validTimeUtc").GetDateTimeOffset(),status,manifestSha256=mismatch?TestData.HashC:body.GetProperty("manifestSha256").GetString(),evidenceCount=body.GetProperty("evidence").GetArrayLength(),productionSeriesId=body.GetProperty("productionSeries").GetProperty("seriesId").GetGuid()});}
 AnalysisPackageDocument BuildClone(Guid field){JsonElement One(string prefix)=>Parse(_entities.Single(x=>x.Key.StartsWith(prefix,StringComparison.OrdinalIgnoreCase)&&Id(JsonDocument.Parse(x.Value).RootElement)==field).Value);JsonElement[] Many(string prefix)=>_entities.Where(x=>x.Key.StartsWith(prefix,StringComparison.OrdinalIgnoreCase)).OrderBy(x=>x.Key).Select(x=>Parse(x.Value)).ToArray();var f=One("/field/api/Field/");var c=Many("/cluster/api/Cluster/");var w=Many("/well/api/Well/");var b=Many("/wellbore/api/WellBore/");var a=Many("/wellborearchitecture/api/WellBoreArchitecture/");var t=Many("/trajectory/api/Trajectory/");var g=Many("/geologicalproperties/api/GeologicalProperties/");return new(DateTimeOffset.Parse("2025-01-02T00:00:00Z"),field,f,c,w,b,a,t,g,new(1,c.Length,w.Length,b.Length,a.Length,t.Length,g.Length),["37 wellbores have no trajectory","38 wellbores have no architecture","1 wellbore has no geology"],TestData.HashA);}
 static AnalysisPackageDocument BuildSource(){Guid field=TestData.FieldId,cluster=G("cluster",0);JsonElement Obj(object x)=>JsonSerializer.SerializeToElement(x,CanonicalJson.SerializerOptions);var wells=Enumerable.Range(0,29).Select(i=>Obj(new{MetaInfo=new{ID=G("well",i)},Name=$"Source well {i}",ClusterID=cluster,IsSingleWell=false})).ToArray();var bores=Enumerable.Range(0,46).Select(i=>Obj(new{MetaInfo=new{ID=G("bore",i)},Name=$"Source bore {i}",WellID=G("well",i%29),IsSidetrack=false})).ToArray();var architectures=Enumerable.Range(0,46).Select(i=>Obj(new{MetaInfo=new{ID=G("architecture",i)},Name=$"Source architecture {i}",WellBoreID=G("bore",i),WellHead=new{},FluidsAboveGroundLevel=Array.Empty<object>(),SurfaceSections=Array.Empty<object>(),CasingSections=Array.Empty<object>()})).ToArray();var trajectories=Enumerable.Range(0,46).Select(i=>Obj(new{MetaInfo=new{ID=G("trajectory",i)},Name=$"Source trajectory {i}",FieldID=field,ClusterID=cluster,WellID=G("well",i%29),WellBoreID=G("bore",i),TrajectoryType="Actual",IsDefinitive=true,CalculationState="Completed",CalculationProgress=1d,SurveyStationList=new[]{new{Abscissa=0d,MD=0d,X=0d,Y=0d,TVD=0d,Inclination=0d,Azimuth=0d},new{Abscissa=10d,MD=10d,X=0d,Y=0d,TVD=10d,Inclination=0d,Azimuth=0d},new{Abscissa=20d,MD=20d,X=0d,Y=0d,TVD=20d,Inclination=0d,Azimuth=0d}},MDStep=10d})).ToArray();var geology=Enumerable.Range(0,46).Select(i=>Obj(new{MetaInfo=new{ID=G("geology",i)},Name=$"Source geology {i}",WellBoreID=G("bore",i),GeologicalPropertyTable=Array.Empty<object>()})).ToArray();return new(DateTimeOffset.Parse("2025-01-01T00:00:00Z"),field,Obj(new{MetaInfo=new{ID=field},Name="Source field",ReferencePoint=new{Latitude=1.0637474506036269m,Longitude=-0.1245678901234569m}}),[Obj(new{MetaInfo=new{ID=cluster},Name="Source cluster",FieldID=field})],wells,bores,architectures,trajectories,geology,new(1,1,29,46,46,46,46),[],TestData.HashB);}
 static void Set(JsonObject value,string name,string text){string? key=value.Select(x=>x.Key).FirstOrDefault(x=>x.Equals(name,StringComparison.OrdinalIgnoreCase));value[key??name]=text;}
 static Guid G(string kind,int i)=>Guid.Parse(DeterministicIdentity.Create("source",kind,i.ToString()));static Guid Id(JsonElement x){PublicationJson.TryProperty(x,"MetaInfo",out var m);PublicationJson.TryProperty(m,"ID",out var id);return id.GetGuid();}static JsonElement Parse(string json)=>JsonDocument.Parse(json).RootElement.Clone();
}
