import { useId, useMemo } from 'react'
import { buildProvenance, provenanceExport } from '../provenance'
import type { FieldPackage } from '../types'
import { JsonDownload } from './JsonDownload'
import './DataSources.css'

const explanations: Record<string, string> = {
  Observed: 'Measurements supplied by the original data provider.',
  'Human interpreted': 'Geological interpretation supplied with the dataset.',
  Derived: 'Calculated or processed from other data. See the preparation details below.',
  'Model estimated': 'Values estimated by a model.',
  Synthetic: 'Data generated by a simulation.',
  Unclassified: 'The provider has not classified this data.',
}

export function DataSources({ pkg, onWell }: { pkg: FieldPackage; onWell: (id: string) => void }) {
  const { groups, sources } = useMemo(() => buildProvenance(pkg), [pkg])
  const prefix = useId()
  return <details className="data-sources">
    <summary>Data sources</summary>
    <p>{pkg.geologicalProperties.length} geology records from {groups.length} data groups.
      Shared source files are listed once below.</p>
    <div className="task-actions">
      <JsonDownload value={provenanceExport(pkg)} filename={`field-${pkg.fieldId}-source-metadata.json`}>
        Download source metadata JSON
      </JsonDownload>
    </div>
    {!groups.length && <p>No geology source information is available.</p>}
    <div className="provenance-groups">
      {groups.map((group, groupIndex) => <section className="provenance-group" key={groupIndex}>
        <h4>{group.dataset}</h4>
        <p><strong>{group.classification}</strong> · {group.entries.length} geology records · {new Set(group.entries.map(entry => entry.boreId).filter(Boolean)).size} identified wellbores</p>
        <p>{explanations[group.classification] ?? 'Classification as supplied by the provider.'}</p>
        <p><strong>Preparation / version:</strong> {group.version}</p>
        <details>
          <summary>Affected wellbores ({group.entries.length} records)</summary>
          <div className="task-table-scroll" role="region" aria-label={`Wellbores in data group ${groupIndex + 1}`} tabIndex={0}>
            <table className="scenario-table">
              <thead><tr><th scope="col">Wellbore</th><th scope="col">Source references</th><th scope="col">Record</th></tr></thead>
              <tbody>{group.entries.map((entry, index) => <tr key={`${entry.id}:${index}`}>
                <th scope="row">{entry.canSelectBore
                  ? <button type="button" onClick={() => onWell(entry.boreId)}>{entry.boreName}</button> : entry.boreName}</th>
                <td>{entry.sourceIndexes.length ? entry.sourceIndexes.map(source => <a key={source} href={`#${prefix}-source-${source}`}>Source {source + 1} </a>) : 'No source references supplied'}
                  {entry.warning && <p>{entry.warning}</p>}</td>
                <td><JsonDownload value={{ geologyId: entry.id, wellBoreId: entry.boreId, provenance: entry.raw }}
                  filename={`geology-${entry.id || index}-source-metadata.json`}>Download JSON</JsonDownload></td>
              </tr>)}</tbody>
            </table>
          </div>
        </details>
      </section>)}
    </div>
    <section className="provenance-sources" aria-label="Source files and licenses">
      <h4>Source files and licenses ({sources.length})</h4>
      {!sources.length && <p>No source files have been supplied.</p>}
      {sources.map((source, index) => <article id={`${prefix}-source-${index}`} className="provenance-source" key={index}>
        <h5>Source {index + 1} · {source.href
          ? <a href={source.href} target="_blank" rel="noreferrer">{source.title}</a>
          : source.title}</h5>
        <p><strong>{source.license}</strong> · Used by {source.records.length} geology records</p>
        {!source.href && <p>No supported web link is available for this source.</p>}
        <details><summary>Attribution and file details</summary>
          <p>{source.attribution}</p>
          <p><strong>SHA-256 checksum:</strong> <code>{source.sha256}</code></p>
          <JsonDownload value={source.raw} filename={`source-${index + 1}.json`}>Download source JSON</JsonDownload>
        </details>
      </article>)}
    </section>
  </details>
}
