using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Options;
namespace DrillingOperations;

public static class TrajectoryMetadata
{
 public const string Planned="Planned"; public const string AsDrilledTruth="AsDrilledTruth"; public const string DefinitiveSyntheticSurvey="DefinitiveSyntheticSurvey"; public const string VerticalDirection="PositiveDown"; public const string ReferenceFrame="BindingWorldProjectedCoordinatesMetres";
}

public sealed class LogObservationOptions
{
 public const string SectionName="LogObservation"; public const string CurrentModelVersion="synthetic-petrophysics-v2";
 public string ModelVersion{get;init;}=CurrentModelVersion; public string CalibrationVersion{get;init;}="petrophysics-calibration-default-v1";
 public double SampleSpacingM{get;init;}=2; public double VerticalResolutionM{get;init;}=4;
 public double SandMatrixDensityKgM3{get;init;}=2650; public double ShaleMatrixDensityKgM3{get;init;}=2720; public double GrSandApi{get;init;}=20; public double GrShaleApi{get;init;}=120;
 public double OilDensityKgM3{get;init;}=800; public double WaterDensityKgM3{get;init;}=1030; public double GasDensityKgM3{get;init;}=150;
 public double OilHydrogenIndex{get;init;}=.9; public double WaterHydrogenIndex{get;init;}=1; public double GasHydrogenIndex{get;init;}=.15; public double ShaleNeutronResponse{get;init;}=.08;
 public double ArchieA{get;init;}=1; public double ArchieM{get;init;}=2; public double ArchieN{get;init;}=2; public double FormationWaterResistivityOhmM{get;init;}=.08;
 public double BoreholeDiameterM{get;init;}=.216; public double WashoutSensitivityM{get;init;}=.05;
 public double GrBiasApi{get;init;}=0; public double GrNoiseStdDevApi{get;init;}=1.5; public double GrDriftPer1000M{get;init;}=.5; public double GrClipMinApi{get;init;}=0; public double GrClipMaxApi{get;init;}=200;
 public double RhobBiasKgM3{get;init;}=0; public double RhobNoiseStdDevKgM3{get;init;}=8; public double RhobDriftPer1000M{get;init;}=3; public double RhobClipMinKgM3{get;init;}=800; public double RhobClipMaxKgM3{get;init;}=3200;
 public double NphiBiasFraction{get;init;}=0; public double NphiNoiseStdDevFraction{get;init;}=.008; public double NphiDriftPer1000M{get;init;}=.003; public double NphiClipMinFraction{get;init;}=-.15; public double NphiClipMaxFraction{get;init;}=.8;
 public double ResistivityBiasOhmM{get;init;}=0; public double ResistivityNoiseStdDevOhmM{get;init;}=.05; public double ResistivityDriftPer1000M{get;init;}=.02; public double ResistivityClipMinOhmM{get;init;}=.01; public double ResistivityClipMaxOhmM{get;init;}=10000;
 public double CaliperBiasM{get;init;}=0; public double CaliperNoiseStdDevM{get;init;}=.002; public double CaliperDriftPer1000M{get;init;}=0; public double CaliperClipMinM{get;init;}=.05; public double CaliperClipMaxM{get;init;}=.8;
 public double MissingProbability{get;init;}=.01; public int MissingIntervalMaxSamples{get;init;}=4; public double BadHoleProbability{get;init;}=.03;
 public double MdtSpacingM{get;init;}=100; public double MdtGaugeNoiseStdDevPa{get;init;}=15000; public double MdtGaugeUncertaintyPa{get;init;}=30000; public double MdtSuperchargePa{get;init;}=75000; public double MdtFailureProbability{get;init;}=.08; public double MdtSuperchargeProbability{get;init;}=.12;
 public int MaximumSamples{get;init;}=10000;
 public void Validate(){Token(ModelVersion);Token(CalibrationVersion);if(ModelVersion!=CurrentModelVersion)Fail("Unsupported log observation model version.");Between(SampleSpacingM,.1,500);Between(VerticalResolutionM,.1,1000);Between(SandMatrixDensityKgM3,1000,4000);Between(ShaleMatrixDensityKgM3,1000,4000);Between(GrSandApi,0,300);Between(GrShaleApi,0,300);if(GrSandApi>=GrShaleApi)Fail("GR endpoints must increase.");Between(OilDensityKgM3,50,2000);Between(WaterDensityKgM3,500,2000);Between(GasDensityKgM3,1,1000);Between(OilHydrogenIndex,0,1.5);Between(WaterHydrogenIndex,0,1.5);Between(GasHydrogenIndex,0,1.5);Between(ShaleNeutronResponse,0,1);Between(ArchieA,.1,10);Between(ArchieM,.5,5);Between(ArchieN,.5,5);Between(FormationWaterResistivityOhmM,.001,10);Between(BoreholeDiameterM,.05,1);Between(WashoutSensitivityM,0,.5);Between(MissingProbability,0,1);Between(BadHoleProbability,0,1);Between(MdtFailureProbability,0,1);Between(MdtSuperchargeProbability,0,1);if(MdtFailureProbability+MdtSuperchargeProbability>1)Fail("MDT probabilities exceed one.");Between(MdtSpacingM,1,1000);Between(MdtGaugeNoiseStdDevPa,0,1e7);Between(MdtGaugeUncertaintyPa,0,1e7);Between(MdtSuperchargePa,0,1e8);if(MissingIntervalMaxSamples<1||MissingIntervalMaxSamples>100||MaximumSamples<1||MaximumSamples>10000)Fail("Sample limits are invalid.");CheckCurve(GrClipMinApi,GrClipMaxApi,GrBiasApi,GrNoiseStdDevApi,GrDriftPer1000M);CheckCurve(RhobClipMinKgM3,RhobClipMaxKgM3,RhobBiasKgM3,RhobNoiseStdDevKgM3,RhobDriftPer1000M);CheckCurve(NphiClipMinFraction,NphiClipMaxFraction,NphiBiasFraction,NphiNoiseStdDevFraction,NphiDriftPer1000M);CheckCurve(ResistivityClipMinOhmM,ResistivityClipMaxOhmM,ResistivityBiasOhmM,ResistivityNoiseStdDevOhmM,ResistivityDriftPer1000M);CheckCurve(CaliperClipMinM,CaliperClipMaxM,CaliperBiasM,CaliperNoiseStdDevM,CaliperDriftPer1000M);}
 public string Hash(){Validate();return DeterministicIdentity.Sha256(CanonicalJson.Serialize(this));}
 private static void CheckCurve(double min,double max,double bias,double noise,double drift){double span=max-min,scale=Math.Max(Math.Abs(min),Math.Abs(max));if(!double.IsFinite(min)||!double.IsFinite(max)||min>=max||!double.IsFinite(bias)||Math.Abs(bias)>Math.Max(1,scale*2)||!double.IsFinite(noise)||noise<0||noise>span*2||!double.IsFinite(drift)||Math.Abs(drift)>span*2)Fail("Curve calibration is invalid.");}private static void Between(double x,double min,double max){if(!double.IsFinite(x)||x<min||x>max)Fail("Option outside validated bounds.");}private static void Token(string x){if(string.IsNullOrWhiteSpace(x)||x.Length>128||x.Any(c=>!(char.IsAsciiLetterOrDigit(c)||"-_.:".Contains(c))))Fail("Version token is invalid.");}private static void Fail(string m)=>throw new OptionsValidationException(nameof(LogObservationOptions),typeof(LogObservationOptions),[m]);
}
public sealed record CleanPetrophysics(double GrApi,double RhobKgM3,double NphiFraction,double DeepResistivityOhmM,double CaliperM);
public sealed record LogCurveDefinition(string Mnemonic,string Unit,double Minimum,double Maximum,double StandardUncertainty);
public sealed record LogObservationSample(double MeasuredDepthM,double? GrApi,double? RhobKgM3,double? NphiFraction,double? DeepResistivityOhmM,double? CaliperM,IReadOnlyList<string> QcFlags);
public sealed record PressureObservation(double MeasuredDepthM,double? PressurePa,double GaugeUncertaintyPa,string Qc);
public sealed record LogQcSummary(int MissingValueCount,int BadHoleSampleCount,int PressureValidCount,int PressureFailedCount,int PressureSuperchargedCount);
public sealed record LogObservationArtifact(string ObservationBatchId,string RunId,string ScenarioId,string SourcePathBindingId,string ObservationModelVersion,string CalibrationVersion,string OptionsHash,IReadOnlyList<LogCurveDefinition> Curves,IReadOnlyList<LogObservationSample> Samples,IReadOnlyList<PressureObservation> PressureTests,LogQcSummary QcSummary,string InputHash,string OutputHash,DateTimeOffset CreatedUtc);

public static class DeterministicLogObservationModel
{
 public static IReadOnlyList<LogCurveDefinition> CurveDefinitions(LogObservationOptions o)=>[new("GR","API",o.GrClipMinApi,o.GrClipMaxApi,o.GrNoiseStdDevApi),new("RHOB","kg/m3",o.RhobClipMinKgM3,o.RhobClipMaxKgM3,o.RhobNoiseStdDevKgM3),new("NPHI","fraction",o.NphiClipMinFraction,o.NphiClipMaxFraction,o.NphiNoiseStdDevFraction),new("RT_DEEP","ohm.m",o.ResistivityClipMinOhmM,o.ResistivityClipMaxOhmM,o.ResistivityNoiseStdDevOhmM),new("CALI","m",o.CaliperClipMinM,o.CaliperClipMaxM,o.CaliperNoiseStdDevM)];
 public static CleanPetrophysics ForwardClean(TruthSampleDto x,LogObservationOptions o){o.Validate();double shale=1-x.NetToGross,matrix=o.SandMatrixDensityKgM3*x.NetToGross+o.ShaleMatrixDensityKgM3*shale,fluid=o.OilDensityKgM3*x.OilSaturation+o.WaterDensityKgM3*x.WaterSaturation+o.GasDensityKgM3*x.GasSaturation;double gr=o.GrSandApi*x.NetToGross+o.GrShaleApi*shale,rhob=matrix*(1-x.Porosity)+fluid*x.Porosity,nphi=x.Porosity*(o.OilHydrogenIndex*x.OilSaturation+o.WaterHydrogenIndex*x.WaterSaturation+o.GasHydrogenIndex*x.GasSaturation)+shale*o.ShaleNeutronResponse;double sw=Math.Max(x.WaterSaturation,1e-6),phi=Math.Max(x.Porosity,1e-6),rt=o.ArchieA*o.FormationWaterResistivityOhmM/(Math.Pow(phi,o.ArchieM)*Math.Pow(sw,o.ArchieN));return new(gr,rhob,nphi,rt,o.BoreholeDiameterM);}
 public static (IReadOnlyList<LogObservationSample> Samples,IReadOnlyList<PressureObservation> Pressures,LogQcSummary Summary) Generate(string runId,IReadOnlyList<TruthSampleDto> truth,LogObservationOptions o){o.Validate();ValidateTruth(truth);double first=truth[0].MeasuredDepthM,last=truth[^1].MeasuredDepthM;int count=(int)Math.Floor((last-first)/o.SampleSpacingM)+1;if(last>first+(count-1)*o.SampleSpacingM+1e-9)count++;if(count<1||count>o.MaximumSamples)throw new RunStageFailureException("LogSampleLimitExceeded","Log series exceeds configured limit.");double[] md=Enumerable.Range(0,count).Select(i=>i==count-1?last:first+i*o.SampleSpacingM).ToArray();CleanPetrophysics[] raw=md.Select(x=>ForwardClean(Interpolate(truth,x),o)).ToArray(),smooth=new CleanPetrophysics[count];double radius=o.VerticalResolutionM/2;for(int i=0;i<count;i++){int[] window=Enumerable.Range(0,count).Where(j=>Math.Abs(md[j]-md[i])<=radius+1e-9).ToArray();smooth[i]=new(window.Average(j=>raw[j].GrApi),window.Average(j=>raw[j].RhobKgM3),window.Average(j=>raw[j].NphiFraction),window.Average(j=>raw[j].DeepResistivityOhmM),window.Average(j=>raw[j].CaliperM));}var rng=new HashRandom(runId+"\n"+o.Hash());var samples=new List<LogObservationSample>(count);int missing=0,badCount=0,missingRemaining=0;for(int i=0;i<count;i++){var q=new List<string>();bool bad=rng.Uniform()<o.BadHoleProbability;if(bad){q.Add("BadHole");badCount++;}if(missingRemaining==0&&rng.Uniform()<o.MissingProbability)missingRemaining=1+(int)(rng.Uniform()*o.MissingIntervalMaxSamples);bool miss=missingRemaining>0;if(miss){missingRemaining--;q.Add("MissingInterval");missing+=5;samples.Add(new(md[i],null,null,null,null,null,q));continue;}double drift=md[i]/1000;var x=smooth[i];double gr=Clip(x.GrApi+o.GrBiasApi+o.GrDriftPer1000M*drift+rng.Normal()*o.GrNoiseStdDevApi,o.GrClipMinApi,o.GrClipMaxApi,q,"GR");double rhob=Clip(x.RhobKgM3+o.RhobBiasKgM3+o.RhobDriftPer1000M*drift+rng.Normal()*o.RhobNoiseStdDevKgM3,o.RhobClipMinKgM3,o.RhobClipMaxKgM3,q,"RHOB");double nphi=Clip(x.NphiFraction+o.NphiBiasFraction+o.NphiDriftPer1000M*drift+rng.Normal()*o.NphiNoiseStdDevFraction,o.NphiClipMinFraction,o.NphiClipMaxFraction,q,"NPHI");double rt=Clip(x.DeepResistivityOhmM+o.ResistivityBiasOhmM+o.ResistivityDriftPer1000M*drift+rng.Normal()*o.ResistivityNoiseStdDevOhmM,o.ResistivityClipMinOhmM,o.ResistivityClipMaxOhmM,q,"RT_DEEP");double cal=x.CaliperM+o.CaliperBiasM+o.CaliperDriftPer1000M*drift+rng.Normal()*o.CaliperNoiseStdDevM+(bad?o.WashoutSensitivityM*(.5+rng.Uniform()):0);cal=Clip(cal,o.CaliperClipMinM,o.CaliperClipMaxM,q,"CALI");if(q.Count==0)q.Add("Valid");samples.Add(new(md[i],gr,rhob,nphi,rt,cal,q));}
 int pressureCapacity=(int)Math.Floor((last-first)/o.MdtSpacingM)+1;if(pressureCapacity>10000)throw new RunStageFailureException("PressureTestLimitExceeded","Pressure test series exceeds 10000 points.");var pressures=new List<PressureObservation>(pressureCapacity);int valid=0,failed=0,super=0;for(double x=first;x<=last+1e-9;x+=o.MdtSpacingM){double at=Math.Min(x,last),u=rng.Uniform();TruthSampleDto t=Interpolate(truth,at);if(u<o.MdtFailureProbability){pressures.Add(new(at,null,o.MdtGaugeUncertaintyPa,"Failed"));failed++;}else if(u<o.MdtFailureProbability+o.MdtSuperchargeProbability){pressures.Add(new(at,t.PressurePa+o.MdtSuperchargePa+rng.Normal()*o.MdtGaugeNoiseStdDevPa,o.MdtGaugeUncertaintyPa,"Supercharged"));super++;}else{pressures.Add(new(at,t.PressurePa+rng.Normal()*o.MdtGaugeNoiseStdDevPa,o.MdtGaugeUncertaintyPa,"Valid"));valid++;}if(at==last)break;}return(samples,pressures,new(missing,badCount,valid,failed,super));}
 private static double Clip(double x,double min,double max,List<string> q,string curve){double y=Math.Clamp(x,min,max);if(y!=x)q.Add(curve+"Clipped");return y;}private static void ValidateTruth(IReadOnlyList<TruthSampleDto> x){if(x.Count is<1 or>10000)throw new RunStageFailureException("TruthCoverageInvalid","Truth coverage is invalid.");double prior=-1;foreach(var t in x){if(t.MeasuredDepthM<=prior||!ReservoirSamplingClient.IsPhysicallyValid(t))throw new RunStageFailureException("TruthCoverageInvalid","Truth MD must increase.");prior=t.MeasuredDepthM;}}
 private static TruthSampleDto Interpolate(IReadOnlyList<TruthSampleDto> p,double md){int i=1;while(i<p.Count&&p[i].MeasuredDepthM<md)i++;if(i>=p.Count)return p[^1];var a=p[i-1];var b=p[i];double f=(md-a.MeasuredDepthM)/(b.MeasuredDepthM-a.MeasuredDepthM);return new(md,L(a.EastingM,b.EastingM),L(a.NorthingM,b.NorthingM),L(a.TrueVerticalDepthM,b.TrueVerticalDepthM),L(a.ReservoirTopDepthM,b.ReservoirTopDepthM),L(a.ReservoirBaseDepthM,b.ReservoirBaseDepthM),L(a.Porosity,b.Porosity),L(a.PermeabilityM2,b.PermeabilityM2),L(a.NetToGross,b.NetToGross),f<.5?a.IsReservoirQuality:b.IsReservoirQuality,L(a.PressurePa,b.PressurePa),L(a.OilSaturation,b.OilSaturation),L(a.WaterSaturation,b.WaterSaturation),L(a.GasSaturation,b.GasSaturation));double L(double x,double y)=>x+(y-x)*f;}
 private sealed class HashRandom(string seed){long n;public double Uniform(){byte[] h=SHA256.HashData(Encoding.UTF8.GetBytes(seed+"\n"+(n++).ToString(System.Globalization.CultureInfo.InvariantCulture)));return (BitConverter.ToUInt64(h,0)+1d)/(ulong.MaxValue+2d);}public double Normal(){double a=Uniform(),b=Uniform();return Math.Sqrt(-2*Math.Log(a))*Math.Cos(Math.Tau*b);}}
}






