using Microsoft.Data.Sqlite;
using System.Text.Json;
namespace DrillingOperations;
public sealed partial class DrillingOperationsStore
{
 private async Task InitializeLogSchemaAsync(SqliteConnection c,CancellationToken ct){await using var q=c.CreateCommand();q.CommandText=LogSchema;await q.ExecuteNonQueryAsync(ct);}
 public Task<bool> GenerateLogsAsync(string runId,LogObservationOptions options,CancellationToken ct=default)=>GenerateLogsAsync(runId,options,new DrillingObservationOptions(),ct);
 public async Task<bool> GenerateLogsAsync(string runId,LogObservationOptions options,DrillingObservationOptions drillingOptions,CancellationToken ct=default)
 {
  options.Validate();drillingOptions.Validate();TruthSampleBatch truth=await GetTruthSampleBatchAsync(runId,ct)??throw new RunStageFailureException("TruthSampleBatchMissing","Verified truth batch is missing.");SurveyArtifact survey=await GetSurveyArtifactAsync(runId,ct)??throw new RunStageFailureException("SurveyArtifactMissing","Verified survey is missing.");DrillingExecutionArtifact execution=await GetDrillingExecutionAsync(runId,ct)??throw new RunStageFailureException("DrillingExecutionMissing","Verified drilling execution is missing.");StageATruthResultDto hidden=JsonSerializer.Deserialize<StageATruthResultDto>(truth.CanonicalResponseJson,CanonicalJson.SerializerOptions)??throw new PersistenceIntegrityException("Truth response is invalid.");
  await using SqliteConnection c=await OpenAsync(ct);await using SqliteTransaction tx=c.BeginTransaction(false);RunResponse run=await ReadRunAsync(c,tx,runId,ct)??throw new RunStageFailureException("RunMissing","Run missing.");TruthBindingResponse binding=await ReadBindingAsync(c,tx,run.ScenarioId,ct)??throw new RunStageFailureException("BindingMissing","Binding missing.");var stages=await ReadStagesAsync(c,tx,runId,ct);if(stages.Single(x=>x.Stage==RunStageKind.S4SampleGeology).Status!=StageStatus.Completed)throw new RunStageFailureException("IllegalStageProgression","S4 is incomplete.");if(stages.Single(x=>x.Stage==RunStageKind.S5GenerateLogs).Status==StageStatus.Completed){await tx.CommitAsync(ct);return false;}
  string optionsJson=CanonicalJson.Serialize(options),optionsHash=DeterministicIdentity.Sha256(optionsJson);string logInput=CanonicalJson.Serialize(new{runId,scenarioId=run.ScenarioId,binding.BindingId,truthBatchId=truth.BatchId,truth.ResponseHash,surveyArtifactId=survey.SurveyArtifactId,survey.OutputHash,optionsHash});string inputHash=DeterministicIdentity.Sha256(logInput),id=DeterministicIdentity.Create("log-observation-batch-v1",runId,inputHash);var generated=DeterministicLogObservationModel.Generate(runId,hidden.Samples,options);DateTimeOffset now=timeProvider.GetUtcNow();var artifact=new LogObservationArtifact(id,runId,run.ScenarioId,truth.StageAPathBindingId,options.ModelVersion,options.CalibrationVersion,optionsHash,DeterministicLogObservationModel.CurveDefinitions(options),generated.Samples,generated.Pressures,generated.Summary,inputHash,string.Empty,now);string output=CanonicalJson.Serialize(artifact),outputHash=DeterministicIdentity.Sha256(output),logContentHash=ComputeLogObservationContentHash(artifact);
  await using SqliteCommand q=Command(c,tx,"INSERT INTO ObservationBatches(ObservationBatchId,RunId,Stage,ObservationModelVersion,CanonicalInputJson,InputHash,CanonicalOutputJson,OutputHash,Status,CreatedUtc,CompletedUtc)VALUES($id,$run,$stage,$model,$input,$inputHash,$output,$outputHash,$status,$created,$completed);");Add(q,"$id",id);Add(q,"$run",runId);Add(q,"$stage",(int)RunStageKind.S5GenerateLogs);Add(q,"$model",options.ModelVersion);Add(q,"$input",logInput);Add(q,"$inputHash",inputHash);Add(q,"$output",output);Add(q,"$outputHash",outputHash);Add(q,"$status","Completed");Add(q,"$created",Format(now));Add(q,"$completed",Format(now));await q.ExecuteNonQueryAsync(ct);
  await using SqliteCommand d=Command(c,tx,"INSERT INTO LogObservationDetails(ObservationBatchId,ScenarioId,CalibrationVersion,CanonicalOptionsJson,OptionsHash,CurveDefinitionsJson,SampleCount,PressureTestCount,QcSummaryJson)VALUES($id,$scenario,$calibration,$options,$optionsHash,$curves,$samples,$pressures,$summary);");Add(d,"$id",id);Add(d,"$scenario",run.ScenarioId);Add(d,"$calibration",options.CalibrationVersion);Add(d,"$options",optionsJson);Add(d,"$optionsHash",optionsHash);Add(d,"$curves",CanonicalJson.Serialize(artifact.Curves));Add(d,"$samples",artifact.Samples.Count);Add(d,"$pressures",artifact.PressureTests.Count);Add(d,"$summary",CanonicalJson.Serialize(artifact.QcSummary));await d.ExecuteNonQueryAsync(ct);
  DrillingObservationArtifact drilling=await PersistDrillingObservationsAsync(c,tx,run,execution,survey,artifact,outputHash,logContentHash,drillingOptions,now,ct);string stageInput=CanonicalJson.Serialize(new{contractVersion=CombinedS5ObservationContractVersion,logObservation=new{observationBatchId=id,inputHash,contentHash=logContentHash},drillingObservation=new{artifactId=drilling.ArtifactId,drilling.InputHash,artifactHash=drilling.OutputHash}});string summary=CanonicalJson.Serialize(new{contractVersion=CombinedS5ObservationContractVersion,logObservation=new{observationBatchId=id,contentHash=logContentHash,sampleCount=artifact.Samples.Count,pressureTestCount=artifact.PressureTests.Count,observationModelVersion=options.ModelVersion,qcSummary=artifact.QcSummary},drillingObservation=new{artifactId=drilling.ArtifactId,artifactHash=drilling.OutputHash,modelVersion=drilling.ModelVersion,calibrationVersion=drilling.CalibrationVersion,drilling.Summary}});string combinedHash=DeterministicIdentity.Sha256(summary);await AppendAuditAsync(c,tx,run.ScenarioId,"logs.generated",id,CanonicalJson.Serialize(new{observationBatchId=id,artifactHash=outputHash,sampleCount=artifact.Samples.Count,pressureTestCount=artifact.PressureTests.Count,observationModelVersion=options.ModelVersion,qcSummary=artifact.QcSummary}),ct);await AppendAuditAsync(c,tx,run.ScenarioId,"drilling-observations.generated",drilling.ArtifactId,CanonicalJson.Serialize(new{drilling.ArtifactId,artifactHash=drilling.OutputHash,drilling.ModelVersion,drilling.CalibrationVersion,drilling.Summary}),ct);await CompleteStageAsync(c,tx,run,RunStageKind.S5GenerateLogs,stageInput,summary,combinedHash,now,ct);await tx.CommitAsync(ct);return true;
 }
 public async Task<LogObservationArtifact?> GetLogObservationBatchAsync(string runId,CancellationToken ct=default)
 {
  await using SqliteConnection c=await OpenAsync(ct);await using SqliteCommand q=c.CreateCommand();q.CommandText="SELECT o.ObservationBatchId,o.RunId,o.ObservationModelVersion,o.CanonicalInputJson,o.InputHash,o.CanonicalOutputJson,o.OutputHash,o.Status,o.CreatedUtc,d.ScenarioId,d.CalibrationVersion,d.CanonicalOptionsJson,d.OptionsHash,d.CurveDefinitionsJson,d.SampleCount,d.PressureTestCount,d.QcSummaryJson,r.ScenarioId FROM ObservationBatches o JOIN LogObservationDetails d ON d.ObservationBatchId=o.ObservationBatchId JOIN Runs r ON r.RunId=o.RunId WHERE o.RunId=$run AND o.Stage=$stage;";Add(q,"$run",runId);Add(q,"$stage",(int)RunStageKind.S5GenerateLogs);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;string storedModelVersion=r.GetString(2);if(storedModelVersion=="synthetic-petrophysics-v1")throw new PersistenceIntegrityException("synthetic-petrophysics-v1 is incompatible with S6 provenance; a new scenario and run are required.");if(storedModelVersion!=LogObservationOptions.CurrentModelVersion)throw new PersistenceIntegrityException($"Unsupported log observation model version {storedModelVersion}; a new scenario and run are required.");LogObservationArtifact artifact=JsonSerializer.Deserialize<LogObservationArtifact>(r.GetString(5),CanonicalJson.SerializerOptions)??throw new PersistenceIntegrityException("Log batch JSON invalid.");LogObservationOptions options=JsonSerializer.Deserialize<LogObservationOptions>(r.GetString(11),CanonicalJson.SerializerOptions)??throw new PersistenceIntegrityException("Log options JSON invalid.");options.Validate();string inputHash=DeterministicIdentity.Sha256(r.GetString(3)),outputHash=DeterministicIdentity.Sha256(r.GetString(5)),optionsHash=DeterministicIdentity.Sha256(r.GetString(11)),expectedId=DeterministicIdentity.Create("log-observation-batch-v1",runId,inputHash);bool invalid=r.GetString(0)!=expectedId||r.GetString(1)!=runId||r.GetString(4)!=inputHash||r.GetString(6)!=outputHash||r.GetString(7)!="Completed"||r.GetString(9)!=r.GetString(17)||r.GetString(2)!=artifact.ObservationModelVersion||r.GetString(10)!=artifact.CalibrationVersion||r.GetString(12)!=optionsHash||artifact.OptionsHash!=optionsHash||artifact.ObservationBatchId!=r.GetString(0)||artifact.RunId!=runId||artifact.ScenarioId!=r.GetString(9)||string.IsNullOrWhiteSpace(artifact.SourcePathBindingId)||artifact.SourcePathBindingId.Length>200||artifact.InputHash!=inputHash||artifact.OutputHash!=string.Empty||CanonicalJson.Serialize(artifact)!=r.GetString(5)||CanonicalJson.Serialize(options)!=r.GetString(11)||CanonicalJson.Serialize(artifact.Curves)!=r.GetString(13)||artifact.Samples.Count!=r.GetInt32(14)||artifact.PressureTests.Count!=r.GetInt32(15)||CanonicalJson.Serialize(artifact.QcSummary)!=r.GetString(16);if(invalid)throw new PersistenceIntegrityException("Log observation integrity failure.");return artifact with{OutputHash=outputHash};
 }
 public static string ComputeLogObservationContentHash(LogObservationArtifact artifact)=>DeterministicIdentity.Sha256(CanonicalJson.Serialize(new{artifact.ObservationBatchId,artifact.RunId,artifact.ScenarioId,artifact.SourcePathBindingId,artifact.ObservationModelVersion,artifact.CalibrationVersion,artifact.OptionsHash,artifact.Curves,artifact.Samples,artifact.PressureTests,artifact.QcSummary,artifact.InputHash}));
 private const string LogSchema="""
 CREATE TABLE IF NOT EXISTS LogObservationDetails(ObservationBatchId TEXT PRIMARY KEY,ScenarioId TEXT NOT NULL,CalibrationVersion TEXT NOT NULL,CanonicalOptionsJson TEXT NOT NULL,OptionsHash TEXT NOT NULL,CurveDefinitionsJson TEXT NOT NULL,SampleCount INTEGER NOT NULL,PressureTestCount INTEGER NOT NULL,QcSummaryJson TEXT NOT NULL,FOREIGN KEY(ObservationBatchId)REFERENCES ObservationBatches(ObservationBatchId));
 CREATE TRIGGER IF NOT EXISTS TR_ObservationBatches_NoUpdate BEFORE UPDATE ON ObservationBatches BEGIN SELECT RAISE(ABORT,'Observation batches are immutable');END;CREATE TRIGGER IF NOT EXISTS TR_ObservationBatches_NoDelete BEFORE DELETE ON ObservationBatches BEGIN SELECT RAISE(ABORT,'Observation batches are immutable');END;
 CREATE TRIGGER IF NOT EXISTS TR_LogObservationDetails_NoUpdate BEFORE UPDATE ON LogObservationDetails BEGIN SELECT RAISE(ABORT,'Log details are immutable');END;CREATE TRIGGER IF NOT EXISTS TR_LogObservationDetails_NoDelete BEFORE DELETE ON LogObservationDetails BEGIN SELECT RAISE(ABORT,'Log details are immutable');END;
 """;
}




