using System.Net;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace DrillingOperations;

public sealed record PublicationEvidence(string EvidenceId,string RecordKind,string ContentSha256);
public sealed record PublicationProductionSeries(string SeriesId,string ModelVersion,string ContentSha256,int MonthCount,IReadOnlyList<int> CheckpointYears);
public sealed record AnalysisRevealRequest(Guid RevealId,Guid RunId,Guid ClonedFieldId,DateTimeOffset ValidTimeUtc,string ObservationModelVersion,string ManifestSha256,IReadOnlyList<PublicationEvidence> Evidence,PublicationProductionSeries ProductionSeries,AnalysisPackageDocument ClonePackage);
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record AnalysisRevealReceipt(Guid ScenarioId,Guid RevealId,Guid ClonedFieldId,DateTimeOffset AsOfUtc,string Status,string ManifestSha256,int EvidenceCount,Guid ProductionSeriesId);
public sealed record RevealSummary(string RevealId,string RunId,string ClonedFieldId,string ManifestSha256,int EvidenceCount,int OperationCount,int VerifiedOperationCount,int ProductionMonthCount,string ObservationModelVersion,string? ProductionContentSha256,string Status,DateTimeOffset ValidTimeUtc,string? ReceiptHash);
public sealed record PublicationWriteOperation(int Sequence,string OperationId,string TargetService,string Route,string ReadRoute,string EntityId,string RecordKind,string CanonicalPayloadJson,string PayloadHash);
public sealed record PublicationWriteReceipt(string BusinessContentHash,string? ProductionRepresentationHash,string CanonicalBusinessJson);
public sealed record PublicationReconciliationOperation(PublicationWriteOperation Operation,string ResultHash,string ResultBusinessJson);
public enum PublicationReconciliationOutcome { Present, Missing, Mismatch }
public sealed record PublicationReconciliationReceipt(PublicationReconciliationOutcome Outcome,string? ActualHash=null);
public sealed record PublicationVerifiedContent(string EntityId,string RecordKind,string ContentSha256,string CanonicalBusinessJson);
public sealed record PublicationStaging(string PublicationPlanId,string RevealId,string RunId,string ScenarioId,string ClonedFieldId,string ObservationBatchId,string ObservationModelVersion,DateTimeOffset ValidTimeUtc,IReadOnlyList<PublicationWriteOperation> Operations,IReadOnlyList<PublicationEvidence> Evidence,string ManifestJson,string ManifestHash,string ProductionEntityId,string ProductionSeriesId,string ProductionModelVersion,string ProductionHash){public IReadOnlyList<PublicationVerifiedContent> VerifiedContents{get;init;}=[];}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record AnalysisPackageDocument(DateTimeOffset GeneratedAt,Guid FieldId,JsonElement Field,IReadOnlyList<JsonElement> Clusters,IReadOnlyList<JsonElement> Wells,IReadOnlyList<JsonElement> WellBores,IReadOnlyList<JsonElement> WellBoreArchitectures,IReadOnlyList<JsonElement> Trajectories,IReadOnlyList<JsonElement> GeologicalProperties,AnalysisPackageCounts SourceCounts,IReadOnlyList<string> DataGaps,string Sha256);
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record AnalysisPackageCounts(int Fields,int Clusters,int Wells,int WellBores,int WellBoreArchitectures,int Trajectories,int GeologicalProperties);

public sealed class PublicationUpstreamException(int statusCode,string code,string message,Exception? inner=null):Exception(message,inner){public int StatusCode{get;}=statusCode;public string DiagnosticCode{get;}=code;}

public sealed class AnalysisPublicationClient(HttpClient client)
{
 public async Task<AnalysisPackageDocument> GetPackageAsync(Guid fieldId,CancellationToken ct)
 {
  try{using var response=await client.GetAsync($"api/fields/{fieldId:D}/package",ct);if(!response.IsSuccessStatusCode)Throw(response.StatusCode,"PublicationPackageUnavailable","Analysis package read failed.");return await response.Content.ReadFromJsonAsync<AnalysisPackageDocument>(CanonicalJson.SerializerOptions,ct)??throw new PublicationUpstreamException(502,"PublicationPackageMalformed","Analysis package was empty.");}
  catch(PublicationUpstreamException){throw;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){throw new PublicationUpstreamException(503,"PublicationPackageTimeout","Analysis package read timed out.");}catch(JsonException e){throw new PublicationUpstreamException(409,"PublicationPackageMalformed","Analysis package JSON was malformed.",e);}catch(HttpRequestException e){throw new PublicationUpstreamException(503,"PublicationPackageUnavailable","Analysis package is unavailable.",e);}
 }
 static void Throw(HttpStatusCode status,string code,string message)=>throw new PublicationUpstreamException((int)status>=500?503:409,code,message);
}
public sealed record AnalysisFinalizeRequest(Guid RevealId,string ManifestSha256);
public sealed partial class AnalysisRevealClient(HttpClient client)
{
 public Task<string> PrepareAsync(string scenarioId,AnalysisRevealRequest request,CancellationToken ct)=>SendAsync($"internal/scenarios/{Uri.EscapeDataString(scenarioId)}/reveal/prepare",request,scenarioId,request,"Prepared",ct);
 public Task<string> FinalizeAsync(string scenarioId,AnalysisRevealRequest expected,CancellationToken ct)=>SendAsync($"internal/scenarios/{Uri.EscapeDataString(scenarioId)}/reveal/finalize",new AnalysisFinalizeRequest(expected.RevealId,expected.ManifestSha256),scenarioId,expected,"Revealed",ct);
 public Task<string> BackfillSnapshotAsync(string scenarioId,AnalysisRevealRequest request,CancellationToken ct)=>SendAsync($"internal/scenarios/{Uri.EscapeDataString(scenarioId)}/reveal/snapshot/backfill",request,scenarioId,request,"Revealed",ct);
 async Task<string> SendAsync<T>(string route,T body,string scenarioId,AnalysisRevealRequest expected,string expectedStatus,CancellationToken ct)
 {
  try{using var response=await client.PostAsJsonAsync(route,body,CanonicalJson.SerializerOptions,ct);string json=await response.Content.ReadAsStringAsync(ct);if(!response.IsSuccessStatusCode)throw new PublicationUpstreamException((int)response.StatusCode is 502 or 503?503:409,(int)response.StatusCode is 502 or 503?"RevealCallbackUnavailable":"RevealCallbackMismatch",$"Analysis reveal {expectedStatus.ToLowerInvariant()} rejected publication: {ProblemDetail(json)}");AnalysisRevealReceipt receipt=JsonSerializer.Deserialize<AnalysisRevealReceipt>(json,CanonicalJson.SerializerOptions)??throw new PublicationUpstreamException(409,"RevealReceiptMalformed","Analysis reveal receipt was empty.");if(receipt.ScenarioId.ToString("D")!=scenarioId||receipt.RevealId!=expected.RevealId||receipt.ClonedFieldId!=expected.ClonedFieldId||receipt.AsOfUtc!=expected.ValidTimeUtc||!receipt.Status.Equals(expectedStatus,StringComparison.Ordinal)||receipt.ManifestSha256!=expected.ManifestSha256||receipt.EvidenceCount!=expected.Evidence.Count||receipt.ProductionSeriesId!=Guid.Parse(expected.ProductionSeries.SeriesId))throw new PublicationUpstreamException(409,"RevealReceiptMismatch","Analysis reveal receipt identity or content did not match the request.");using JsonDocument document=JsonDocument.Parse(json);if(PublicationJson.ContainsForbiddenProperty(document.RootElement))throw new PublicationUpstreamException(409,"RevealReceiptMalformed","Analysis reveal receipt contained unsafe data.");return CanonicalJson.Canonicalize(document.RootElement);}
  catch(PublicationUpstreamException){throw;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){throw new PublicationUpstreamException(503,"RevealCallbackTimeout","Analysis reveal callback timed out.");}catch(JsonException e){throw new PublicationUpstreamException(409,"RevealReceiptMalformed","Analysis reveal receipt was malformed.",e);}catch(HttpRequestException e){throw new PublicationUpstreamException(503,"RevealCallbackUnavailable","Analysis reveal callback is unavailable.",e);}
 }
 static string ProblemDetail(string json){try{using JsonDocument document=JsonDocument.Parse(json);if(document.RootElement.TryGetProperty("detail",out JsonElement detail)&&detail.ValueKind==JsonValueKind.String)return (detail.GetString()??"No detail.")[..Math.Min(detail.GetString()?.Length??0,500)];}catch(JsonException){}return "No safe detail was returned.";}
}
public sealed partial class OntologyPublicationClient(IHttpClientFactory clients)
{
 public async Task<PublicationWriteReceipt> WriteAndVerifyAsync(PublicationWriteOperation operation,string scenarioId,string revealId,string productionEntityId,CancellationToken ct)
 {
  HttpClient client=clients.CreateClient(operation.TargetService);string prefix=operation.Route[..(operation.Route.IndexOf("/api/",StringComparison.Ordinal)+4)];string markerRoute=$"{prefix}/internal/publication/records/{operation.EntityId}";
  try
  {
   using(var marker=await client.PutAsJsonAsync(markerRoute+"/stage",new{scenarioId=Guid.Parse(scenarioId),revealId=Guid.Parse(revealId)},CanonicalJson.SerializerOptions,ct))if(!marker.IsSuccessStatusCode)Throw(marker.StatusCode,"PublicationStageMarkerRejected","Ontology publication stage marker was rejected.");using(var preflight=await client.GetAsync(operation.ReadRoute,ct)){if(preflight.IsSuccessStatusCode){string existing=await preflight.Content.ReadAsStringAsync(ct);using JsonDocument expectedPreflight=JsonDocument.Parse(operation.CanonicalPayloadJson);using JsonDocument observedPreflight=JsonDocument.Parse(existing);if(!PublicationJson.BusinessContentMatches(expectedPreflight.RootElement,observedPreflight.RootElement))throw new PublicationUpstreamException(409,"PublicationEntityIdentityConflict",$"{operation.TargetService} already contains different business content for the deterministic publication identity.");}else if(preflight.StatusCode!=HttpStatusCode.NotFound)Throw(preflight.StatusCode,"PublicationPreflightUnavailable",$"{operation.TargetService} publication preflight failed.");}

   string writeRoute=WriteRoute(operation,prefix);
   using var content=new StringContent(operation.CanonicalPayloadJson,Encoding.UTF8,"application/json");using HttpResponseMessage write=await client.PostAsync(writeRoute,content,ct);if(!write.IsSuccessStatusCode&&write.StatusCode!=HttpStatusCode.Conflict)Throw(write.StatusCode,"PublicationWriteRejected",$"{operation.TargetService} rejected staged write.");
   using HttpResponseMessage read=await client.GetAsync(operation.ReadRoute,ct);if(!read.IsSuccessStatusCode)Throw(read.StatusCode,"PublicationReadAfterWriteFailed",$"{operation.TargetService} read-after-write failed.");string actual=await read.Content.ReadAsStringAsync(ct);using JsonDocument expected=JsonDocument.Parse(operation.CanonicalPayloadJson);using JsonDocument observed=JsonDocument.Parse(actual);if(!PublicationJson.BusinessContentMatches(expected.RootElement,observed.RootElement))throw new PublicationUpstreamException(409,"PublicationReadAfterWriteMismatch",$"{operation.TargetService} persisted different business content.");
   string businessJson=PublicationJson.CanonicalBusinessContent(observed.RootElement),businessHash=DeterministicIdentity.Sha256(businessJson);string? productionHash=operation.EntityId==productionEntityId?PublicationJson.MonthlyProductionHash(observed.RootElement):null;return new(businessHash,productionHash,businessJson);
  }
  catch(PublicationUpstreamException){throw;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){throw new PublicationUpstreamException(503,"PublicationWriteTimeout","Ontology publication timed out.");}catch(JsonException e){throw new PublicationUpstreamException(409,"PublicationReadAfterWriteMismatch","Ontology read-back was malformed.",e);}catch(HttpRequestException e){throw new PublicationUpstreamException(503,"PublicationWriteUnavailable","Ontology publication unavailable.",e);}
 }
 public async Task<PublicationReconciliationReceipt> VerifyPersistedAsync(PublicationReconciliationOperation item,CancellationToken ct)
 {
  HttpClient client=clients.CreateClient(item.Operation.TargetService);try{using HttpResponseMessage read=await client.GetAsync(item.Operation.ReadRoute,ct);if(read.StatusCode==HttpStatusCode.NotFound)return new(PublicationReconciliationOutcome.Missing);if(!read.IsSuccessStatusCode)Throw(read.StatusCode,"PublicationReconciliationUnavailable",$"{item.Operation.TargetService} reconciliation read failed.");string actual=await read.Content.ReadAsStringAsync(ct);using JsonDocument observed=JsonDocument.Parse(actual);string business=PublicationJson.CanonicalBusinessContent(observed.RootElement),hash=DeterministicIdentity.Sha256(business);return hash==item.ResultHash&&business==item.ResultBusinessJson?new(PublicationReconciliationOutcome.Present,hash):new(PublicationReconciliationOutcome.Mismatch,hash);}catch(PublicationUpstreamException){throw;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){throw new PublicationUpstreamException(503,"PublicationReconciliationTimeout","Ontology reconciliation timed out.");}catch(JsonException e){throw new PublicationUpstreamException(409,"PublicationReconciliationMismatch","Ontology reconciliation read-back was malformed.",e);}catch(HttpRequestException e){throw new PublicationUpstreamException(503,"PublicationReconciliationUnavailable","Ontology reconciliation is unavailable.",e);}
 }
 public async Task<PublicationWriteReceipt> RestoreMissingAndVerifyAsync(PublicationReconciliationOperation item,string productionEntityId,CancellationToken ct)
 {
  PublicationWriteOperation operation=item.Operation;HttpClient client=clients.CreateClient(operation.TargetService);string prefix=operation.Route[..(operation.Route.IndexOf("/api/",StringComparison.Ordinal)+4)],writeRoute=WriteRoute(operation,prefix);try{using var content=new StringContent(operation.CanonicalPayloadJson,Encoding.UTF8,"application/json");using HttpResponseMessage write=await client.PostAsync(writeRoute,content,ct);if(!write.IsSuccessStatusCode&&write.StatusCode!=HttpStatusCode.Conflict)Throw(write.StatusCode,"PublicationReconciliationWriteRejected",$"{operation.TargetService} rejected restoration.");using HttpResponseMessage read=await client.GetAsync(operation.ReadRoute,ct);if(!read.IsSuccessStatusCode)Throw(read.StatusCode,"PublicationReconciliationReadFailed",$"{operation.TargetService} restoration read-back failed.");string actual=await read.Content.ReadAsStringAsync(ct);using JsonDocument observed=JsonDocument.Parse(actual);string business=PublicationJson.CanonicalBusinessContent(observed.RootElement),hash=DeterministicIdentity.Sha256(business);if(hash!=item.ResultHash||business!=item.ResultBusinessJson)throw new PublicationUpstreamException(409,"PublicationReconciliationMismatch",$"{operation.TargetService} restored different business content.");string? productionHash=operation.EntityId==productionEntityId?PublicationJson.MonthlyProductionHash(observed.RootElement):null;return new(hash,productionHash,business);}catch(PublicationUpstreamException){throw;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){throw new PublicationUpstreamException(503,"PublicationReconciliationTimeout","Ontology restoration timed out.");}catch(JsonException e){throw new PublicationUpstreamException(409,"PublicationReconciliationMismatch","Ontology restoration read-back was malformed.",e);}catch(HttpRequestException e){throw new PublicationUpstreamException(503,"PublicationReconciliationUnavailable","Ontology restoration is unavailable.",e);}
 }
 static string WriteRoute(PublicationWriteOperation operation,string prefix)=>operation.TargetService switch{"TrajectoryService"=>$"{prefix}/internal/publication/Trajectory","GeologicalPropertiesService"=>$"{prefix}/internal/publication/GeologicalProperties",_=>operation.Route};
 public async Task ActivateAsync(PublicationWriteOperation operation,CancellationToken ct)
 {
  HttpClient client=clients.CreateClient(operation.TargetService);string prefix=operation.Route[..(operation.Route.IndexOf("/api/",StringComparison.Ordinal)+4)];try{using HttpResponseMessage response=await client.PutAsync($"{prefix}/internal/publication/records/{operation.EntityId}/activate",null,ct);if(!response.IsSuccessStatusCode)Throw(response.StatusCode,"PublicationActivationUnavailable","Ontology publication activation failed.");}catch(PublicationUpstreamException){throw;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){throw new PublicationUpstreamException(503,"PublicationActivationTimeout","Ontology publication activation timed out.");}catch(HttpRequestException e){throw new PublicationUpstreamException(503,"PublicationActivationUnavailable","Ontology publication activation unavailable.",e);}
 }
 static void Throw(HttpStatusCode status,string code,string message)=>throw new PublicationUpstreamException((int)status>=500?503:409,code,message);
}

public static class PublicationJson
{
 static readonly string[] Forbidden=["truthsample","productiontruth","stageapath","completionbinding","worldid","bindingmetadata","gridcell","ijk","oilSaturation","waterSaturation","gasSaturation","trueVerticalDepthM"];
 public static bool ContainsForbiddenProperty(JsonElement value){if(value.ValueKind==JsonValueKind.Object){foreach(var p in value.EnumerateObject()){if(Forbidden.Any(x=>p.Name.Contains(x,StringComparison.OrdinalIgnoreCase)))return true;if(ContainsForbiddenProperty(p.Value))return true;}}else if(value.ValueKind==JsonValueKind.Array)foreach(var x in value.EnumerateArray())if(ContainsForbiddenProperty(x))return true;return false;}
 public static bool BusinessContentMatches(JsonElement expected,JsonElement actual)=>BusinessContentMatches(expected,actual,null,false);
 static bool BusinessContentMatches(JsonElement expected,JsonElement actual,string? propertyName,bool surveyStation)
 {
  if(expected.ValueKind!=actual.ValueKind)return false;
  if(expected.ValueKind==JsonValueKind.Object)
  {
   if(propertyName?.Equals("ReferencePoint",StringComparison.OrdinalIgnoreCase)==true&&
      expected.EnumerateObject().Count()==2&&TryProperty(expected,"X",out var referenceNorth)&&referenceNorth.ValueKind==JsonValueKind.Number&&
      TryProperty(expected,"Y",out var referenceEast)&&referenceEast.ValueKind==JsonValueKind.Number)
    return HorizontalReferencePointMatches(referenceNorth,referenceEast,actual);
   // A newly projected tie-in is a SurveyStation too; allow only the same checked model aliases.
   // Do not reinterpret sparse legacy tie-ins that never contained the authoritative station fields.
   surveyStation=surveyStation||propertyName?.Equals("TieInPoint",StringComparison.OrdinalIgnoreCase)==true&&
    new[]{"MD","Abscissa","X","Y","TVD","Inclination","Azimuth"}.All(name=>TryProperty(expected,name,out var value)&&value.ValueKind==JsonValueKind.Number);
   var expectedProperties=expected.EnumerateObject().Where(x=>!IsServerOwned(x.Name)).ToDictionary(x=>x.Name,x=>x.Value,StringComparer.OrdinalIgnoreCase);var actualProperties=actual.EnumerateObject().Where(x=>!IsServerOwned(x.Name)).ToDictionary(x=>x.Name,x=>x.Value,StringComparer.OrdinalIgnoreCase);foreach(string name in expectedProperties.Keys.Union(actualProperties.Keys,StringComparer.OrdinalIgnoreCase)){bool hasExpected=expectedProperties.TryGetValue(name,out var expectedValue),hasActual=actualProperties.TryGetValue(name,out var actualValue);if(!hasExpected){if(actualValue.ValueKind==JsonValueKind.Null)continue;if(surveyStation&&IsDerivedStationField(name))continue;return false;}if(!hasActual){if(expectedValue.ValueKind!=JsonValueKind.Null)return false;continue;}if(!BusinessContentMatches(expectedValue,actualValue,name,false))return false;}return !surveyStation||ValidateSurveyStationEnrichment(expected,actual);
  }
  if(expected.ValueKind==JsonValueKind.Array){var e=expected.EnumerateArray().ToArray();var a=actual.EnumerateArray().ToArray();bool stationElements=propertyName?.Equals("SurveyStationList",StringComparison.OrdinalIgnoreCase)==true;return e.Length==a.Length&&e.Zip(a,(left,right)=>BusinessContentMatches(left,right,null,stationElements)).All(x=>x);}
  if(expected.ValueKind==JsonValueKind.Number)return NumbersMatch(expected,actual);
  if(expected.ValueKind==JsonValueKind.String){string? left=expected.GetString(),right=actual.GetString();if(left==right)return true;if(IsTemporalProperty(propertyName)&&TryRoundTripInstant(left,out var leftInstant)&&TryRoundTripInstant(right,out var rightInstant))return leftInstant.UtcTicks==rightInstant.UtcTicks;return TryStrictRoundTripInstant(left,out leftInstant)&&TryStrictRoundTripInstant(right,out rightInstant)&&leftInstant.UtcTicks==rightInstant.UtcTicks;}
  return expected.GetRawText()==actual.GetRawText();
 }
 static bool HorizontalReferencePointMatches(JsonElement north,JsonElement east,JsonElement actual)
 {
  if(actual.EnumerateObject().Select(x=>x.Name).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=actual.EnumerateObject().Count())return false;
  if(!TryProperty(actual,"X",out var x)||!TryProperty(actual,"Y",out var y)||!NumbersMatch(north,x)||!NumbersMatch(east,y))return false;
  foreach(var property in actual.EnumerateObject())
  {
   if(property.Value.ValueKind==JsonValueKind.Null)continue;
   if(property.Name.Equals("X",StringComparison.OrdinalIgnoreCase)||property.Name.Equals("Y",StringComparison.OrdinalIgnoreCase))continue;
   if(property.Name.Equals("RiemannianNorth",StringComparison.OrdinalIgnoreCase)){if(!NumbersMatch(north,property.Value))return false;continue;}
   if(property.Name.Equals("RiemannianEast",StringComparison.OrdinalIgnoreCase)){if(!NumbersMatch(east,property.Value))return false;continue;}
   double bound=property.Name.Equals("Latitude",StringComparison.OrdinalIgnoreCase)?90:
    property.Name.Equals("Longitude",StringComparison.OrdinalIgnoreCase)?180:0;
   if(bound==0||property.Value.ValueKind!=JsonValueKind.Number||!property.Value.TryGetDouble(out double coordinate)||
      !double.IsFinite(coordinate)||Math.Abs(coordinate)>bound)return false;
  }
  return true;
 }
 static bool ValidateSurveyStationEnrichment(JsonElement expected,JsonElement actual)
 {
  string[] authoritative=["MD","Abscissa","X","Y","TVD","Inclination","Azimuth"];foreach(string name in authoritative)if(!TryProperty(expected,name,out var expectedValue)||!TryProperty(actual,name,out var actualValue)||expectedValue.ValueKind!=JsonValueKind.Number||actualValue.ValueKind!=JsonValueKind.Number||!NumbersMatch(expectedValue,actualValue))return false;
  if(IsActualOnly("Z",out var z)&&(!TryProperty(actual,"TVD",out var tvd)||!NumericEquivalent(z,tvd)))return false;
  if(IsActualOnly("RiemannianNorth",out var north)&&(!TryProperty(actual,"X",out var x)||!NumericEquivalent(north,x)))return false;
  if(IsActualOnly("RiemannianEast",out var east)&&(!TryProperty(actual,"Y",out var y)||!NumericEquivalent(east,y)))return false;
  if(IsActualOnly("BoreholeRadius",out var radius)&&(!TryFinite(radius,out double radiusValue)||radiusValue!=0d))return false;
  if(IsActualOnly("Latitude",out var latitude)&&(!TryFinite(latitude,out double latitudeValue)||latitudeValue < -90d||latitudeValue > 90d))return false;
  if(IsActualOnly("Longitude",out var longitude)&&(!TryFinite(longitude,out double longitudeValue)||longitudeValue < -180d||longitudeValue > 180d))return false;
  return true;
  bool IsActualOnly(string name,out JsonElement value){bool inActual=TryProperty(actual,name,out value);return inActual&&!TryProperty(expected,name,out _);}
  static bool NumericEquivalent(JsonElement left,JsonElement right)=>left.ValueKind==JsonValueKind.Number&&right.ValueKind==JsonValueKind.Number&&NumbersMatch(left,right);
  static bool TryFinite(JsonElement value,out double result){result=default;return value.ValueKind==JsonValueKind.Number&&value.TryGetDouble(out result)&&double.IsFinite(result);}
 }
 static bool IsDerivedStationField(string name)=>name.Equals("Z",StringComparison.OrdinalIgnoreCase)||name.Equals("RiemannianNorth",StringComparison.OrdinalIgnoreCase)||name.Equals("RiemannianEast",StringComparison.OrdinalIgnoreCase)||name.Equals("Latitude",StringComparison.OrdinalIgnoreCase)||name.Equals("Longitude",StringComparison.OrdinalIgnoreCase)||name.Equals("BoreholeRadius",StringComparison.OrdinalIgnoreCase);
 static bool IsTemporalProperty(string? name)=>name is not null&&(name.Equals("EffectiveAt",StringComparison.OrdinalIgnoreCase)||name.Equals("FirstSeenAt",StringComparison.OrdinalIgnoreCase)||name.EndsWith("Utc",StringComparison.OrdinalIgnoreCase)||name.Contains("TimeStart",StringComparison.OrdinalIgnoreCase)||name.Contains("TimeEnd",StringComparison.OrdinalIgnoreCase));
 static bool TryStrictRoundTripInstant(string? value,out DateTimeOffset result)=>DateTimeOffset.TryParseExact(value,"O",System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.RoundtripKind,out result);
 static bool TryRoundTripInstant(string? value,out DateTimeOffset result)=>TryStrictRoundTripInstant(value,out result)||DateTimeOffset.TryParseExact(value,"yyyy-MM-dd'T'HH:mm:ssK",System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.RoundtripKind,out result);
 static bool NumbersMatch(JsonElement expected,JsonElement actual)
 {
  string left=expected.GetRawText(),right=actual.GetRawText();if(TryExactInteger(left,out decimal leftInteger)&&TryExactInteger(right,out decimal rightInteger))return leftInteger==rightInteger;if(decimal.TryParse(left,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out decimal leftDecimal)&&decimal.TryParse(right,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out decimal rightDecimal)){decimal scale=Math.Max(1m,Math.Max(Math.Abs(leftDecimal),Math.Abs(rightDecimal)));return Math.Abs(leftDecimal-rightDecimal)<=0.000000000001m*scale;}if(!double.TryParse(left,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out double leftDouble)||!double.TryParse(right,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out double rightDouble)||!double.IsFinite(leftDouble)||!double.IsFinite(rightDouble))return false;double tolerance=1e-12*Math.Max(1d,Math.Max(Math.Abs(leftDouble),Math.Abs(rightDouble)));return Math.Abs(leftDouble-rightDouble)<=tolerance;
  static bool TryExactInteger(string text,out decimal value){if(decimal.TryParse(text,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out value)&&decimal.Truncate(value)==value&&(value>=long.MinValue&&value<=long.MaxValue||value>=0&&value<=ulong.MaxValue))return true;value=0;return false;}
 }
 public static string BusinessContentHash(JsonElement value)=>DeterministicIdentity.Sha256(CanonicalBusinessContent(value));
 public static string MonthlyProductionHash(JsonElement entity){if(!TryProperty(entity,"Dataset",out var dataset)||!TryProperty(dataset,"MonthlyProduction",out var months)||months.ValueKind!=JsonValueKind.Array)throw new PublicationUpstreamException(409,"PublishedProductionMalformed","Published Well does not contain monthly production.");return BusinessContentHash(months);}
 public static string CanonicalBusinessContent(JsonElement value){using var stream=new MemoryStream();using(var writer=new Utf8JsonWriter(stream))Write(value,writer);return Encoding.UTF8.GetString(stream.ToArray());static void Write(JsonElement value,Utf8JsonWriter writer){switch(value.ValueKind){case JsonValueKind.Object:writer.WriteStartObject();foreach(var property in value.EnumerateObject().Where(x=>!IsServerOwned(x.Name)).OrderBy(x=>x.Name,StringComparer.Ordinal)){writer.WritePropertyName(property.Name);Write(property.Value,writer);}writer.WriteEndObject();break;case JsonValueKind.Array:writer.WriteStartArray();foreach(var item in value.EnumerateArray())Write(item,writer);writer.WriteEndArray();break;default:value.WriteTo(writer);break;}}}
 static bool IsServerOwned(string name)=>name.Equals("CreationDate",StringComparison.OrdinalIgnoreCase)||name.Equals("LastModificationDate",StringComparison.OrdinalIgnoreCase);
 public static bool TryProperty(JsonElement element,string name,out JsonElement value){if(element.ValueKind==JsonValueKind.Object)foreach(var p in element.EnumerateObject())if(p.Name.Equals(name,StringComparison.OrdinalIgnoreCase)){value=p.Value;return true;}value=default;return false;}
 public static void ValidateStagedPublication(PublicationStaging plan)
 {
  var groups=new Dictionary<string,IReadOnlyList<JsonElement>>(StringComparer.Ordinal);foreach(var group in plan.Operations.GroupBy(x=>x.RecordKind,StringComparer.Ordinal))groups[group.Key]=group.Select(x=>JsonDocument.Parse(x.CanonicalPayloadJson).RootElement.Clone()).ToArray();
  var operationIdentities=plan.Operations.Select(x=>(x.RecordKind,Id:Guid.Parse(x.EntityId))).ToHashSet();var evidenceIdentities=plan.Evidence.Select(x=>(x.RecordKind,Id:Guid.Parse(x.EvidenceId))).ToHashSet();var verifiedIdentities=plan.VerifiedContents.Select(x=>(x.RecordKind,Id:Guid.Parse(x.EntityId))).ToHashSet();bool invalidCommitment=plan.VerifiedContents.Any(x=>x.ContentSha256.Length!=64||x.ContentSha256.Any(c=>!Uri.IsHexDigit(c))||DeterministicIdentity.Sha256(x.CanonicalBusinessJson)!=x.ContentSha256);if(operationIdentities.Count!=plan.Operations.Count||evidenceIdentities.Count!=plan.Evidence.Count||verifiedIdentities.Count!=plan.VerifiedContents.Count||plan.Evidence.Count!=plan.Operations.Count||plan.VerifiedContents.Count!=plan.Operations.Count||!operationIdentities.SetEquals(evidenceIdentities)||!operationIdentities.SetEquals(verifiedIdentities)||invalidCommitment)throw new PublicationUpstreamException(409,"StagedPublicationCommitmentMismatch","Verified read-back commitments do not exactly cover immutable staged operation identities.");
  foreach(var operation in plan.Operations){PublicationVerifiedContent verified=plan.VerifiedContents.Single(x=>x.EntityId==operation.EntityId&&x.RecordKind==operation.RecordKind);using var expected=JsonDocument.Parse(operation.CanonicalPayloadJson);using var actual=JsonDocument.Parse(verified.CanonicalBusinessJson);if(!BusinessContentMatches(expected.RootElement,actual.RootElement))throw new PublicationUpstreamException(409,"StagedPublicationBusinessMismatch","Verified read-back business content differs materially from the immutable staged payload.");}
  groups=plan.VerifiedContents.GroupBy(x=>x.RecordKind,StringComparer.Ordinal).ToDictionary(x=>x.Key,x=>(IReadOnlyList<JsonElement>)x.Select(v=>JsonDocument.Parse(v.CanonicalBusinessJson).RootElement.Clone()).ToArray(),StringComparer.Ordinal);ValidateGraph(groups,plan,"Staged");
 }
 public static void ValidatePublishedPackage(AnalysisPackageDocument package,PublicationStaging plan)
 {
  if(package.FieldId!=Guid.Parse(plan.ClonedFieldId))throw new PublicationUpstreamException(409,"PublishedPackageIdentityMismatch","Published Analysis package identity did not match the reveal.");
  var groups=new Dictionary<string,IReadOnlyList<JsonElement>>(StringComparer.Ordinal){["Field"]=[package.Field],["Cluster"]=package.Clusters,["Well"]=package.Wells,["WellBore"]=package.WellBores,["WellBoreArchitecture"]=package.WellBoreArchitectures,["Trajectory"]=package.Trajectories,["GeologicalProperties"]=package.GeologicalProperties};
  var expectedCounts=plan.Operations.GroupBy(x=>x.RecordKind,StringComparer.Ordinal).ToDictionary(x=>x.Key,x=>x.Count(),StringComparer.Ordinal);if(groups.Any(x=>!expectedCounts.TryGetValue(x.Key,out int count)||count!=x.Value.Count))throw new PublicationUpstreamException(409,"PublishedPackageCountMismatch","Published package kind counts do not match the immutable publication graph.");var expected=plan.Evidence.Select(x=>(x.RecordKind,Id:Guid.Parse(x.EvidenceId),x.ContentSha256)).ToHashSet();var actual=groups.SelectMany(group=>group.Value.Select(entity=>(RecordKind:group.Key,Id:EntityGuid(entity),ContentSha256:BusinessContentHash(entity)))).ToHashSet();if(expected.Count!=plan.Operations.Count||actual.Count!=plan.Operations.Count||!expected.SetEquals(actual))throw new PublicationUpstreamException(409,"PublishedPackageEvidenceMismatch","Published package business hashes do not exactly match verified evidence.");
  ValidateGraph(groups,plan,"Published");
 }
 public static AnalysisPackageDocument BuildVerifiedPackage(PublicationStaging plan)
 {
  ValidateStagedPublication(plan);
  var verified=plan.VerifiedContents.ToDictionary(x=>(x.RecordKind,x.EntityId));
  var groups=plan.Operations.OrderBy(x=>x.Sequence).Select(x=>verified[(x.RecordKind,x.EntityId)]).GroupBy(x=>x.RecordKind,StringComparer.Ordinal).ToDictionary(x=>x.Key,x=>(IReadOnlyList<JsonElement>)x.Select(item=>JsonDocument.Parse(item.CanonicalBusinessJson).RootElement.Clone()).ToArray(),StringComparer.Ordinal);
  JsonElement field=groups["Field"].Single();IReadOnlyList<JsonElement> clusters=groups["Cluster"],wells=groups["Well"],bores=groups["WellBore"],architectures=groups["WellBoreArchitecture"],trajectories=groups["Trajectory"],geology=groups["GeologicalProperties"];
  var counts=new AnalysisPackageCounts(1,clusters.Count,wells.Count,bores.Count,architectures.Count,trajectories.Count,geology.Count);string[] gaps=ComputeDataGaps(clusters,wells,bores,architectures,trajectories,geology);
  Guid fieldId=Guid.Parse(plan.ClonedFieldId);string hash=ComputeAnalysisPackageHash(fieldId,field,clusters,wells,bores,architectures,trajectories,geology,counts,gaps);
  return new(plan.ValidTimeUtc,fieldId,field,clusters,wells,bores,architectures,trajectories,geology,counts,gaps,hash);
 }
 public static string ComputeAnalysisPackageHash(Guid fieldId,JsonElement field,IReadOnlyList<JsonElement> clusters,IReadOnlyList<JsonElement> wells,IReadOnlyList<JsonElement> wellBores,IReadOnlyList<JsonElement> wellBoreArchitectures,IReadOnlyList<JsonElement> trajectories,IReadOnlyList<JsonElement> geologicalProperties,AnalysisPackageCounts sourceCounts,IReadOnlyList<string> dataGaps)
 {
  JsonNode Node(JsonElement value)=>JsonNode.Parse(value.GetRawText())!;JsonArray Array(IReadOnlyList<JsonElement> values)=>new(values.Select(Node).ToArray());
  var content=new JsonObject{{"fieldId",fieldId},{"field",Node(field)},{"clusters",Array(clusters)},{"wells",Array(wells)},{"wellBores",Array(wellBores)},{"wellBoreArchitectures",Array(wellBoreArchitectures)},{"trajectories",Array(trajectories)},{"geologicalProperties",Array(geologicalProperties)},{"sourceCounts",new JsonObject{{"Fields",sourceCounts.Fields},{"Clusters",sourceCounts.Clusters},{"Wells",sourceCounts.Wells},{"WellBores",sourceCounts.WellBores},{"WellBoreArchitectures",sourceCounts.WellBoreArchitectures},{"Trajectories",sourceCounts.Trajectories},{"GeologicalProperties",sourceCounts.GeologicalProperties}}},{"dataGaps",new JsonArray(dataGaps.Select(x=>(JsonNode?)x).ToArray())}};
  using JsonDocument document=JsonDocument.Parse(content.ToJsonString());return DeterministicIdentity.Sha256(CanonicalJson.Canonicalize(document.RootElement));
 }
 static string[] ComputeDataGaps(IReadOnlyList<JsonElement> clusters,IReadOnlyList<JsonElement> wells,IReadOnlyList<JsonElement> bores,IReadOnlyList<JsonElement> architectures,IReadOnlyList<JsonElement> trajectories,IReadOnlyList<JsonElement> geology)
 {
  var gaps=new List<string>();if(trajectories.Count==0)gaps.Add("No trajectories were returned for the field.");if(clusters.Count==0)gaps.Add("No clusters were returned for the field.");if(clusters.Count>0&&wells.Count==0)gaps.Add("No wells were returned for the field clusters.");if(wells.Count>0&&bores.Count==0)gaps.Add("No wellbores were returned for the field wells.");
  HashSet<Guid> boreIds=bores.Select(EntityGuid).ToHashSet();if(bores.Count>0&&architectures.Count==0)gaps.Add("No wellbore architecture matched the included wellbores.");int withoutArchitecture=boreIds.Count-architectures.Select(x=>GuidProperty(x,"WellBoreID")).Where(boreIds.Contains).Distinct().Count();if(withoutArchitecture>0)gaps.Add($"{withoutArchitecture} included wellbore(s) have no architecture record.");if(bores.Count>0&&geology.Count==0)gaps.Add("No geological properties matched the included wellbores.");HashSet<Guid> geologyBores=geology.Select(x=>GuidProperty(x,"WellBoreID")).ToHashSet();int withoutGeology=boreIds.Count(x=>!geologyBores.Contains(x));if(withoutGeology>0)gaps.Add($"{withoutGeology} included wellbore(s) had no geological-properties record.");HashSet<Guid> trajectoryBores=trajectories.Select(x=>GuidProperty(x,"WellBoreID")).ToHashSet();int withoutTrajectory=boreIds.Count(x=>!trajectoryBores.Contains(x));if(withoutTrajectory>0)gaps.Add($"{withoutTrajectory} included wellbore(s) have no survey trajectory.");return gaps.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
 }
 static void ValidateGraph(IReadOnlyDictionary<string,IReadOnlyList<JsonElement>> groups,PublicationStaging plan,string phase)
 {
  string code=phase+"Package";string message=phase+" publication";string[] kinds=["Field","Cluster","Well","WellBore","WellBoreArchitecture","Trajectory","GeologicalProperties"];if(kinds.Any(x=>!groups.ContainsKey(x)))throw new PublicationUpstreamException(409,code+"KindMissing",message+" is missing a required record kind.");
  if(groups["Field"].Count!=1||groups["Well"].Count!=30||groups["WellBore"].Count!=47)throw new PublicationUpstreamException(409,code+"CountMismatch",message+" must contain one field, 30 wells, and 47 wellbores.");
  foreach(var entity in groups.SelectMany(x=>x.Value))if(ContainsForbiddenProperty(entity))throw new PublicationUpstreamException(409,code+"Unsafe",message+" contained forbidden hidden data.");
  var fields=groups["Field"].Select(EntityGuid).ToHashSet();var clusters=groups["Cluster"].ToDictionary(EntityGuid);var wells=groups["Well"].ToDictionary(EntityGuid);var bores=groups["WellBore"].ToDictionary(EntityGuid);var trajectories=groups["Trajectory"].ToDictionary(EntityGuid);bool invalid=groups["Cluster"].Any(x=>!fields.Contains(GuidProperty(x,"FieldID")))||groups["Well"].Any(x=>!clusters.ContainsKey(GuidProperty(x,"ClusterID")))||groups["WellBore"].Any(x=>!wells.ContainsKey(GuidProperty(x,"WellID")))||groups["WellBoreArchitecture"].Any(x=>!bores.ContainsKey(GuidProperty(x,"WellBoreID")));
  foreach(var trajectory in groups["Trajectory"]){Guid field=GuidProperty(trajectory,"FieldID"),cluster=GuidProperty(trajectory,"ClusterID"),well=GuidProperty(trajectory,"WellID"),bore=GuidProperty(trajectory,"WellBoreID");invalid|=!fields.Contains(field)||!clusters.ContainsKey(cluster)||!wells.ContainsKey(well)||!bores.ContainsKey(bore)||GuidProperty(wells[well],"ClusterID")!=cluster||GuidProperty(bores[bore],"WellID")!=well;}
  foreach(var geology in groups["GeologicalProperties"]){Guid bore=GuidProperty(geology,"WellBoreID");invalid|=!bores.ContainsKey(bore);if(TryProperty(geology,"TrajectoryID",out var trajectoryValue)&&trajectoryValue.ValueKind is not JsonValueKind.Null and not JsonValueKind.Undefined){Guid trajectory=ReadGuid(trajectoryValue,"TrajectoryID");invalid|=!trajectories.TryGetValue(trajectory,out var owner)||GuidProperty(owner,"WellBoreID")!=bore;}}
  Guid productionWell=Guid.Parse(plan.ProductionEntityId);JsonElement[] scenarioBores=groups["WellBore"].Where(x=>GuidProperty(x,"WellID")==productionWell).ToArray();if(scenarioBores.Length!=1)invalid=true;else{Guid scenarioBore=EntityGuid(scenarioBores[0]);JsonElement[] scenarioTrajectories=groups["Trajectory"].Where(x=>GuidProperty(x,"WellBoreID")==scenarioBore).ToArray();JsonElement[] scenarioGeology=groups["GeologicalProperties"].Where(x=>GuidProperty(x,"WellBoreID")==scenarioBore).ToArray();invalid|=!groups["WellBoreArchitecture"].Any(x=>GuidProperty(x,"WellBoreID")==scenarioBore)||scenarioTrajectories.Length==0||scenarioGeology.Length==0||scenarioGeology.Any(x=>!TryProperty(x,"TrajectoryID",out var t)||t.ValueKind==JsonValueKind.Null||!scenarioTrajectories.Any(y=>EntityGuid(y)==ReadGuid(t,"TrajectoryID")));}
  if(invalid)throw new PublicationUpstreamException(409,code+"DanglingReference",message+" contains invalid graph ownership or dangling foreign keys.");
  JsonElement production=groups["Well"].Single(x=>EntityGuid(x)==Guid.Parse(plan.ProductionEntityId));bool productionShapeInvalid=!TryProperty(production,"Dataset",out var dataset)||!TryProperty(dataset,"MonthlyProduction",out var months)||months.ValueKind!=JsonValueKind.Array||months.GetArrayLength()!=60;bool productionCommitmentInvalid=plan.ProductionHash.Length!=64||plan.ProductionHash.Any(c=>!Uri.IsHexDigit(c));if(productionShapeInvalid||productionCommitmentInvalid||phase=="Published"&&MonthlyProductionHash(production)!=plan.ProductionHash)throw new PublicationUpstreamException(409,phase=="Published"?"PublishedProductionMismatch":"StagedProductionCommitmentMismatch",message+" monthly production does not match verified 60-month evidence.");
 }
 static Guid EntityGuid(JsonElement entity){if(!TryProperty(entity,"MetaInfo",out var meta)||!TryProperty(meta,"ID",out var id))throw new PublicationUpstreamException(409,"PublishedPackageIdentityMissing","Publication entity has no identity.");return ReadGuid(id,"MetaInfo.ID");}
 static Guid GuidProperty(JsonElement entity,string name){if(!TryProperty(entity,name,out var value))throw new PublicationUpstreamException(409,"PublishedPackageReferenceMissing",$"Publication entity is missing {name}.");return ReadGuid(value,name);}
 static Guid ReadGuid(JsonElement value,string name){if(value.ValueKind==JsonValueKind.String&&Guid.TryParse(value.GetString(),out var id)&&id!=Guid.Empty)return id;throw new PublicationUpstreamException(409,"PublishedPackageReferenceInvalid",$"Publication {name} is invalid.");}
 public static string? StringProperty(JsonObject value,string name){JsonNode? node=value.FirstOrDefault(x=>x.Key.Equals(name,StringComparison.OrdinalIgnoreCase)).Value;return node is JsonValue scalar&&scalar.TryGetValue<string>(out var text)?text:null;}
 public static Guid RequiredGuid(JsonNode node,string name){if(node is JsonObject value){JsonNode? child=value.FirstOrDefault(x=>x.Key.Equals(name,StringComparison.OrdinalIgnoreCase)).Value;if(child is JsonValue scalar){if(scalar.TryGetValue<Guid>(out var direct)&&direct!=Guid.Empty)return direct;if(scalar.TryGetValue<string>(out var text)&&Guid.TryParse(text,out var id)&&id!=Guid.Empty)return id;}}throw new PublicationUpstreamException(409,"PublishedGraphInvalid",$"Published {name} is missing or invalid.");}
 public static Guid EntityId(JsonNode node){if(node is JsonObject entity){JsonNode? meta=entity.FirstOrDefault(x=>x.Key.Equals("MetaInfo",StringComparison.OrdinalIgnoreCase)).Value;if(meta is JsonObject metaObject){JsonNode? identity=metaObject.FirstOrDefault(x=>x.Key.Equals("ID",StringComparison.OrdinalIgnoreCase)).Value;if(identity is JsonValue value&&value.TryGetValue<string>(out var text)&&Guid.TryParse(text,out var id)&&id!=Guid.Empty)return id;}}throw new PublicationUpstreamException(409,"SourceGraphInvalid","Source entity has no valid MetaInfo.ID.");}
 public static void Set(JsonObject value,string property,JsonNode? node){string? existing=value.Select(x=>x.Key).FirstOrDefault(x=>x.Equals(property,StringComparison.OrdinalIgnoreCase));value[existing??property]=node;}
 public static JsonNode Remap(JsonNode source,IReadOnlyDictionary<Guid,Guid> ids){JsonNode clone=source.DeepClone();Walk(clone);return clone;void Walk(JsonNode? n){if(n is JsonObject o){foreach(var kv in o.ToArray()){if(kv.Value is JsonValue v&&v.TryGetValue<string>(out var s)&&Guid.TryParse(s,out var id)&&ids.TryGetValue(id,out var mapped))o[kv.Key]=mapped.ToString("D");else Walk(kv.Value);}}else if(n is JsonArray a)foreach(var x in a)Walk(x);}}
}
