using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DrillingOperations;

public enum ScoreMetricBasis { HiddenTruth, RevealedObservation, ObservationGap, Baseline }
public enum ScoreMetricStatus { Scored, Unavailable }
public sealed record ScorecardMetric(string Name,ScoreMetricBasis Basis,ScoreMetricStatus Status,double? Value,string? Unit,double? LowerBound,double? UpperBound,string? Limitation);
public sealed record AnalysisScorecardRequest(string ScorecardId,string RunId,string RevealId,string ScoringModelVersion,string InputSha256,string HeadlineMetric,IReadOnlyList<ScorecardMetric> Metrics,DateTimeOffset CreatedValidTimeUtc)
{
 [JsonIgnore(Condition=JsonIgnoreCondition.WhenWritingNull)]
 public ScoreCorrectionProvenance? Correction{get;init;}
}
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record AnalysisScorecardReceipt(Guid ScenarioId,Guid ScorecardId,Guid RevealId,string ScoringModelVersion,string InputSha256,string? HeadlineMetric,IReadOnlyList<ScorecardMetric> Metrics,DateTimeOffset CreatedValidTimeUtc,string? Limitation,string ContentSha256)
{
 [JsonIgnore(Condition=JsonIgnoreCondition.WhenWritingNull)]
 public ScoreCorrectionProvenance? Correction{get;init;}
}
public sealed record ScoreArtifactReference(string Kind,string ArtifactId,string ContentSha256);
public sealed record ScorecardDraft(string ScorecardId,string RunId,string ScenarioId,string RevealId,string ScoringModelVersion,string InputSha256,string CanonicalInputJson,string CanonicalOutputJson,string OutputSha256,string HeadlineMetric,IReadOnlyList<ScorecardMetric> Metrics,DateTimeOffset CreatedValidTimeUtc);
public sealed record ScorecardSummary(string ScorecardId,string RunId,string RevealId,string ScoringModelVersion,string InputSha256,string OutputSha256,string HeadlineMetric,IReadOnlyList<ScorecardMetric> Metrics,DateTimeOffset CreatedValidTimeUtc,string Status,string? ReceiptHash)
{
 [JsonIgnore(Condition=JsonIgnoreCondition.WhenWritingNull)]
 public ScoreCorrectionProvenance? Correction{get;init;}
}
public sealed class ScoringException(int statusCode,string diagnosticCode,string message,Exception? inner=null):Exception(message,inner){public int StatusCode{get;}=statusCode;public string DiagnosticCode{get;}=diagnosticCode;}

public sealed partial class AnalysisScorecardClient(HttpClient client)
{
 public async Task<string> PublishAsync(string scenarioId,AnalysisScorecardRequest request,CancellationToken ct)
 {
  try
  {
   using HttpResponseMessage response=await client.PostAsJsonAsync($"internal/scenarios/{Uri.EscapeDataString(scenarioId)}/scorecard",request,CanonicalJson.SerializerOptions,ct);
   if(!response.IsSuccessStatusCode)throw new ScoringException((int)response.StatusCode>=500?503:409,(int)response.StatusCode>=500?"ScorecardCallbackUnavailable":"ScorecardCallbackMismatch","Analysis rejected the scorecard callback.");
   string json=await response.Content.ReadAsStringAsync(ct);AnalysisScorecardReceipt receipt=JsonSerializer.Deserialize<AnalysisScorecardReceipt>(json,CanonicalJson.SerializerOptions)??throw new ScoringException(409,"ScorecardReceiptMalformed","Analysis returned an empty scorecard receipt.");
   if(!ReceiptMatches(receipt,scenarioId,request))throw new ScoringException(409,"ScorecardReceiptMismatch","Analysis scorecard receipt identity or content did not match the request.");
   using JsonDocument document=JsonDocument.Parse(json);if(PublicationJson.ContainsForbiddenProperty(document.RootElement))throw new ScoringException(409,"ScorecardReceiptMalformed","Analysis scorecard receipt contained forbidden hidden data.");return CanonicalJson.Canonicalize(document.RootElement);
  }
  catch(ScoringException){throw;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){throw new ScoringException(503,"ScorecardCallbackTimeout","Analysis scorecard callback timed out.");}catch(JsonException e){throw new ScoringException(409,"ScorecardReceiptMalformed","Analysis scorecard receipt was malformed.",e);}catch(HttpRequestException e){throw new ScoringException(503,"ScorecardCallbackUnavailable","Analysis scorecard callback is unavailable.",e);}
 }
 static bool MetricsEqual(IReadOnlyList<ScorecardMetric> a,IReadOnlyList<ScorecardMetric> b)=>CanonicalJson.Serialize(a)==CanonicalJson.Serialize(b);
 internal static bool ReceiptMatches(AnalysisScorecardReceipt receipt,string scenarioId,AnalysisScorecardRequest request)=>receipt.ScenarioId.ToString("D")==scenarioId&&receipt.ScorecardId.ToString("D")==request.ScorecardId&&receipt.RevealId.ToString("D")==request.RevealId&&receipt.ScoringModelVersion==request.ScoringModelVersion&&receipt.InputSha256==request.InputSha256&&receipt.HeadlineMetric==request.HeadlineMetric&&receipt.CreatedValidTimeUtc==request.CreatedValidTimeUtc&&MetricsEqual(receipt.Metrics,request.Metrics)&&LowerHash(receipt.ContentSha256)&&receipt.Correction==request.Correction;
 internal static bool LowerHash(string? value)=>value is{Length:64}&&value.All(c=>c is >= '0' and <= '9' or >= 'a' and <= 'f');
}

public static class ScoreArtifactIntegrity
{
 public const string ModelVersion="scoring-model-v1";
 public static void ValidatePrediction(Guid scenarioId,AnalysisPredictionDto prediction,string sealedHash,string sourcePackageHash)
 {
  ConfiguredPredictionIntegrity.ValidateSemantics(prediction);
  AnalysisPredictionBodyDto body=prediction.Body??throw Invalid("Approved prediction body is missing.");if(prediction.ScenarioId!=scenarioId||prediction.Seal is null||prediction.Approval is null||prediction.Baselines is null||prediction.Baselines.Count!=4)throw Invalid("Approved prediction identity, seal, approval, or four baselines are missing.");
  string bodyHash=DeterministicIdentity.Sha256(CanonicalJson.Serialize(body));if(bodyHash!=sealedHash||prediction.Seal.Sha256!=sealedHash||prediction.Approval.SealedSha256!=sealedHash||body.FieldPackageSha256!=sourcePackageHash)throw Invalid("Approved prediction body, seal, approval, or source package hash changed.");
  string[] kinds=["NearestWell","FieldMean","FourNeighborIdw","UncertaintyAwareRank1"];if(!prediction.Baselines.Select(x=>x.Kind).Order(StringComparer.Ordinal).SequenceEqual(kinds.Order(StringComparer.Ordinal))||prediction.Baselines.Any(x=>x.ScenarioId!=scenarioId||x.BaselineId==Guid.Empty))throw Invalid("Exactly one immutable baseline of each required kind is required.");
  foreach(AnalysisBaselineDto baseline in prediction.Baselines){string content=ConfiguredPredictionIntegrity.CanonicalBaselineContent(baseline);if(DeterministicIdentity.Sha256(content)!=baseline.ContentSha256||!AnalysisScorecardClient.LowerHash(baseline.ContentSha256))throw Invalid($"Baseline {baseline.Kind} content hash changed.");if(baseline.AnalysisBinding is not null)ConfiguredPredictionIntegrity.ValidateBaselineIdentity(baseline);}
  string bundle=CanonicalJson.Serialize(prediction.Baselines.OrderBy(x=>Array.IndexOf(kinds,x.Kind)).Select(x=>new{kind=x.Kind,baselineId=x.BaselineId,contentSha256=x.ContentSha256}).ToArray());if(prediction.Seal.BaselinesSha256 is null||DeterministicIdentity.Sha256(bundle)!=prediction.Seal.BaselinesSha256)throw Invalid("Baseline bundle hash changed.");
 }
 static ScoringException Invalid(string message)=>new(409,"ScoringArtifactIntegrityMismatch",message);
}

public static class ScoreMetricContract
{
 public static void ValidateForPublication(IReadOnlyList<ScorecardMetric> metrics)
 {
  Validate(metrics);
  foreach(ScorecardMetric metric in metrics)
  {
   bool invalid=metric.LowerBound.HasValue!=metric.UpperBound.HasValue||
    metric.LowerBound>metric.UpperBound||
    metric.LowerBound is double lower&&Math.Abs(lower)>1e15||
    metric.UpperBound is double upper&&Math.Abs(upper)>1e15||
    metric.Status==ScoreMetricStatus.Scored&&(metric.Value<metric.LowerBound||metric.Value>metric.UpperBound);
   if(invalid)throw new ArgumentException($"Metric {metric.Name} requires paired ordered bounds containing its scored value.");
  }
 }
 public static void Validate(IReadOnlyList<ScorecardMetric> metrics)
 {
  if(metrics.Count==0||metrics.Select(x=>x.Name).Distinct(StringComparer.Ordinal).Count()!=metrics.Count)throw new ArgumentException("Metric names must be nonempty and unique.");
  foreach(ScorecardMetric x in metrics)
  {
   bool commonInvalid=!Enum.IsDefined(x.Basis)||!Enum.IsDefined(x.Status)||string.IsNullOrWhiteSpace(x.Name)||x.Name.Length>200||string.IsNullOrWhiteSpace(x.Unit)||x.Unit.Length>32||x.LowerBound is double l&&!double.IsFinite(l)||x.UpperBound is double u&&!double.IsFinite(u);
   bool scoredInvalid=x.Status==ScoreMetricStatus.Scored&&(x.Value is null||!double.IsFinite(x.Value.Value)||Math.Abs(x.Value.Value)>1e15||x.Limitation is not null);
   bool unavailableInvalid=x.Status==ScoreMetricStatus.Unavailable&&(x.Value is not null||x.LowerBound is not null||x.UpperBound is not null||string.IsNullOrWhiteSpace(x.Limitation));
   if(commonInvalid)throw new ArgumentException($"Metric {x.Name} has invalid common fields.");
   if(scoredInvalid)throw new ArgumentException($"Scored metric {x.Name} requires a finite bounded value and unit with no limitation.");
   if(unavailableInvalid)throw new ArgumentException($"Unavailable metric {x.Name} requires a limitation and no value or bounds.");
  }
 }
}

public static class DeterministicScoringModel
{
 const double FluidPresenceThreshold=.1;
 public static IReadOnlyList<ScorecardMetric> Calculate(string reservoirName,AnalysisPredictionBodyDto prediction,IReadOnlyList<AnalysisBaselineDto> baselines,IReadOnlyList<TruthSampleDto> truth,LogObservationArtifact logs,CompletionDesign completion,SurveyArtifact survey,ProductionRunResponse productionTruth,ProductionSeriesArtifact observedProduction)
  =>CalculateCore(reservoirName,prediction,baselines,truth,logs,completion,survey,productionTruth,observedProduction,false);
 internal static IReadOnlyList<ScorecardMetric> CalculateLegacyEndpointBounds(string reservoirName,AnalysisPredictionBodyDto prediction,IReadOnlyList<AnalysisBaselineDto> baselines,IReadOnlyList<TruthSampleDto> truth,LogObservationArtifact logs,CompletionDesign completion,SurveyArtifact survey,ProductionRunResponse productionTruth,ProductionSeriesArtifact observedProduction)
  =>CalculateCore(reservoirName,prediction,baselines,truth,logs,completion,survey,productionTruth,observedProduction,true);
 static IReadOnlyList<ScorecardMetric> CalculateCore(string reservoirName,AnalysisPredictionBodyDto prediction,IReadOnlyList<AnalysisBaselineDto> baselines,IReadOnlyList<TruthSampleDto> truth,LogObservationArtifact logs,CompletionDesign completion,SurveyArtifact survey,ProductionRunResponse productionTruth,ProductionSeriesArtifact observedProduction,bool legacyBounds)
 {
  if(string.IsNullOrWhiteSpace(reservoirName)||prediction.Formations is null||prediction.ExpectedPaydirtM is null||prediction.FluidClasses is null||prediction.ContactPredictions is null||prediction.ProductionForecasts is null)throw Invalid("Prediction is incomplete for scoring.");if(truth.Count<2||logs.Samples.Count<2||survey.Stations.Count<2)throw Invalid("Truth, log, or survey coverage is insufficient.");
  ValidateQuantiles(prediction.ExpectedPaydirtM,"expected pay");foreach(var x in prediction.Formations){ValidateQuantiles(x.TopTrueVerticalDepthM,"formation top");ValidateQuantiles(x.BaseTrueVerticalDepthM,"formation base");}foreach(var x in prediction.ContactPredictions)ValidateQuantiles(x.TrueVerticalDepthM,"contact");
  AnalysisFormationPredictionDto formation=prediction.Formations.SingleOrDefault(x=>x.FormationName.Equals(reservoirName,StringComparison.OrdinalIgnoreCase))??throw Invalid("Prediction does not contain the selected reservoir formation.");
  var metrics=new List<ScorecardMetric>();double hiddenTop=Median(truth.Select(x=>x.ReservoirTopDepthM)),hiddenBase=Median(truth.Select(x=>x.ReservoirBaseDepthM));AddQuantilePair(metrics,"formationTop",formation.TopTrueVerticalDepthM,hiddenTop,ScoreMetricBasis.HiddenTruth,legacyBounds:legacyBounds);AddQuantilePair(metrics,"formationBase",formation.BaseTrueVerticalDepthM,hiddenBase,ScoreMetricBasis.HiddenTruth,legacyBounds:legacyBounds);
  CompletionDesignOptions completionOptions=JsonSerializer.Deserialize<CompletionDesignOptions>(completion.CanonicalOptionsJson,CanonicalJson.SerializerOptions)??throw Invalid("Completion options are invalid.");completionOptions.Validate();LogObservationSample[] qualifying=logs.Samples.Where(x=>ObservableCompletionDesigner.Qualifies(x,completionOptions)).OrderBy(x=>x.MeasuredDepthM).ToArray();double? observedTop=qualifying.Length==0?null:InterpolateSurveyTvd(survey.Stations,qualifying[0].MeasuredDepthM),observedBase=qualifying.Length==0?null:InterpolateSurveyTvd(survey.Stations,qualifying[^1].MeasuredDepthM);AddQuantilePair(metrics,"formationTop",formation.TopTrueVerticalDepthM,observedTop,ScoreMetricBasis.RevealedObservation,"No valid qualifying GR/RHOB/NPHI/RT sample inferred a formation top.",legacyBounds);AddQuantilePair(metrics,"formationBase",formation.BaseTrueVerticalDepthM,observedBase,ScoreMetricBasis.RevealedObservation,"No valid qualifying GR/RHOB/NPHI/RT sample inferred a formation base.",legacyBounds);
  double hiddenPay=Thickness(truth.Select(x=>(x.MeasuredDepthM,x.IsReservoirQuality)).ToArray()),observedPay=completion.Openings.Where(x=>x.Type!="Isolated").Sum(x=>Math.Max(0,x.BaseMdM-x.TopMdM));AddQuantilePair(metrics,"expectedPaydirt",prediction.ExpectedPaydirtM,hiddenPay,ScoreMetricBasis.HiddenTruth,legacyBounds:legacyBounds);AddQuantilePair(metrics,"expectedPaydirt",prediction.ExpectedPaydirtM,observedPay,ScoreMetricBasis.RevealedObservation,legacyBounds:legacyBounds);
  AddFluidMetrics(metrics,prediction.FluidClasses,TruthPresence(truth),truth.Count,ScoreMetricBasis.HiddenTruth);var observableClasses=logs.Samples.Where(ValidLog).Select(ObservedClass).ToArray();AddFluidMetrics(metrics,prediction.FluidClasses,observableClasses.GroupBy(x=>x,StringComparer.Ordinal).ToDictionary(x=>x.Key,x=>x.Count(),StringComparer.Ordinal),observableClasses.Length,ScoreMetricBasis.RevealedObservation);
  var hiddenContacts=InferContacts(truth.Select(x=>(x.MeasuredDepthM,x.TrueVerticalDepthM,Class:TruthClass(x))).ToArray());bool mdtUsable=logs.PressureTests.Count(x=>x.PressurePa is not null&&x.Qc=="Valid")>=2;var observedContacts=mdtUsable?InferContacts(logs.Samples.Where(ValidLog).Select(x=>(x.MeasuredDepthM,InterpolateSurveyTvd(survey.Stations,x.MeasuredDepthM),Class:ObservedClass(x))).ToArray()):new Dictionary<string,double>();foreach(string contact in new[]{"GOC","GWC","OWC"}){AnalysisContactPredictionDto? predicted=prediction.ContactPredictions.SingleOrDefault(x=>x.ContactType.Equals(contact,StringComparison.Ordinal));AddContact(metrics,contact,predicted,hiddenContacts,ScoreMetricBasis.HiddenTruth,"Truth samples contain no deterministic phase transition for this contact.",legacyBounds);AddContact(metrics,contact,predicted,observedContacts,ScoreMetricBasis.RevealedObservation,mdtUsable?"Valid logs contain no deterministic phase transition for this contact.":"At least two valid MDT pressure observations are required to support a log-derived contact.",legacyBounds);}
  AddProduction(metrics,prediction.ProductionForecasts,productionTruth,observedProduction);
  foreach(AnalysisBaselineDto baseline in baselines.OrderBy(x=>x.Kind,StringComparer.Ordinal)){if(baseline.ExpectedPaydirtM is null)metrics.Add(Unavailable($"expectedPaydirtP50AbsoluteError.Baseline.{baseline.Kind}",ScoreMetricBasis.Baseline,"m",string.IsNullOrWhiteSpace(baseline.Limitation)?"The baseline did not provide expected-pay quantiles.":baseline.Limitation));else{ValidateQuantiles(baseline.ExpectedPaydirtM,"baseline expected pay");var bounds=AbsoluteErrorBounds(baseline.ExpectedPaydirtM,hiddenPay,legacyBounds);metrics.Add(Scored($"expectedPaydirtP50AbsoluteError.Baseline.{baseline.Kind}",ScoreMetricBasis.Baseline,Math.Abs(baseline.ExpectedPaydirtM.P50-hiddenPay),"m",bounds.Lower,bounds.Upper));}}
  ScorecardMetric[] baselineScores=metrics.Where(x=>x.Basis==ScoreMetricBasis.Baseline&&x.Name.StartsWith("expectedPaydirtP50AbsoluteError.Baseline.",StringComparison.Ordinal)&&x.Status==ScoreMetricStatus.Scored).ToArray();if(baselineScores.Length==0){metrics.Add(Unavailable("expectedPaydirtBestBaselineAbsoluteError.Baseline",ScoreMetricBasis.Baseline,"m","No baseline supplied a scoreable expected-pay prediction."));metrics.Add(Unavailable("expectedPaydirtAiMinusBestBaselineAbsoluteError.Baseline",ScoreMetricBasis.Baseline,"m","No baseline supplied a scoreable expected-pay prediction."));}else{double best=baselineScores.Min(x=>x.Value!.Value),ai=Math.Abs(prediction.ExpectedPaydirtM.P50-hiddenPay);metrics.Add(Scored("expectedPaydirtBestBaselineAbsoluteError.Baseline",ScoreMetricBasis.Baseline,best,"m"));metrics.Add(Scored("expectedPaydirtAiMinusBestBaselineAbsoluteError.Baseline",ScoreMetricBasis.Baseline,ai-best,"m"));}
  AddObservationGaps(metrics);
  const string single="Unavailable because only the approved path and single decision were sampled; scoring-model-v1 does not fabricate counterfactual candidate truth.";foreach(string name in new[]{"targetDistanceToBestHiddenCandidate.HiddenTruth","spearmanRankCorrelation.HiddenTruth","rankingRegret.HiddenTruth"})metrics.Add(Unavailable(name,ScoreMetricBasis.HiddenTruth,name.StartsWith("target",StringComparison.Ordinal)?"m":"fraction",single));const string calibration="Unavailable for one run; CRPS, PIT, and empirical calibration coverage require predictive distributions and at least 20 independent worlds.";foreach(string name in new[]{"crps.HiddenTruth","pit.HiddenTruth","empiricalCalibrationCoverage.HiddenTruth"})metrics.Add(Unavailable(name,ScoreMetricBasis.HiddenTruth,"fraction",calibration));
  if(legacyBounds)ScoreMetricContract.Validate(metrics);else ValidateMetrics(metrics);return metrics;
 }
 static void AddQuantilePair(List<ScorecardMetric> metrics,string stem,AnalysisQuantilesDto q,double? actual,ScoreMetricBasis basis,string? unavailable=null,bool legacyBounds=false){string suffix=basis.ToString();if(actual is null){metrics.Add(Unavailable($"{stem}P50AbsoluteError.{suffix}",basis,"m",unavailable!));metrics.Add(Unavailable($"{stem}P90P10Coverage.{suffix}",basis,"fraction",unavailable!));return;}var bounds=AbsoluteErrorBounds(q,actual.Value,legacyBounds);metrics.Add(Scored($"{stem}P50AbsoluteError.{suffix}",basis,Math.Abs(q.P50-actual.Value),"m",bounds.Lower,bounds.Upper));metrics.Add(Scored($"{stem}P90P10Coverage.{suffix}",basis,actual.Value>=q.P90&&actual.Value<=q.P10?1:0,"fraction"));}
 static void AddContact(List<ScorecardMetric> m,string contact,AnalysisContactPredictionDto? prediction,IReadOnlyDictionary<string,double> actual,ScoreMetricBasis basis,string unavailable,bool legacyBounds=false){string name=$"{contact.ToLowerInvariant()}DepthP50AbsoluteError.{basis}";if(prediction is null){m.Add(Unavailable(name,basis,"m","The approved prediction did not include this contact."));return;}if(!actual.TryGetValue(contact,out double depth)){m.Add(Unavailable(name,basis,"m",unavailable));return;}var bounds=AbsoluteErrorBounds(prediction.TrueVerticalDepthM,depth,legacyBounds);m.Add(Scored(name,basis,Math.Abs(prediction.TrueVerticalDepthM.P50-depth),"m",bounds.Lower,bounds.Upper));}
 static (double Lower,double Upper) AbsoluteErrorBounds(AnalysisQuantilesDto quantiles,double actual,bool legacyBounds=false)
 {
  if(legacyBounds)return(Math.Min(Math.Abs(quantiles.P90-actual),Math.Abs(quantiles.P10-actual)),Math.Max(Math.Abs(quantiles.P90-actual),Math.Abs(quantiles.P10-actual)));
  // Absolute error is not monotone across the forecast interval: it reaches zero if the actual lies inside.
  double lower=actual<quantiles.P90?quantiles.P90-actual:actual>quantiles.P10?actual-quantiles.P10:0;
  return (lower,Math.Max(Math.Abs(quantiles.P90-actual),Math.Abs(quantiles.P10-actual)));
 }
 static void AddFluidMetrics(List<ScorecardMetric> m,IReadOnlyList<string> predicted,IReadOnlyDictionary<string,int> actualCounts,int sampleCount,ScoreMetricBasis basis){string[] classes=["Oil","Gas","Water"];if(sampleCount==0){foreach(string metric in new[]{"fluidClassPrecision","fluidClassRecall","fluidClassWeightedF1"})m.Add(Unavailable($"{metric}.{basis}",basis,"fraction","No valid samples were available for fluid interpretation."));return;}var p=predicted.ToHashSet(StringComparer.Ordinal);if(p.Count==0||p.Any(x=>!classes.Contains(x,StringComparer.Ordinal)))throw Invalid("Prediction fluid classes are invalid.");double tp=0,fp=0,fn=0,weighted=0,support=0;foreach(string c in classes){double positives=actualCounts.GetValueOrDefault(c),negatives=sampleCount-positives,classTp=p.Contains(c)?positives:0,classFp=p.Contains(c)?negatives:0,classFn=p.Contains(c)?0:positives;tp+=classTp;fp+=classFp;fn+=classFn;double denom=2*classTp+classFp+classFn;if(positives>0){weighted+=(denom==0?0:2*classTp/denom)*positives;support+=positives;}}m.Add(Ratio("fluidClassPrecision",basis,tp,tp+fp));m.Add(Ratio("fluidClassRecall",basis,tp,tp+fn));m.Add(support==0?Unavailable($"fluidClassWeightedF1.{basis}",basis,"fraction","No interpreted phase support was available."):Scored($"fluidClassWeightedF1.{basis}",basis,weighted/support,"fraction"));}
 static IReadOnlyDictionary<string,int> TruthPresence(IReadOnlyList<TruthSampleDto> samples){var counts=new Dictionary<string,int>(StringComparer.Ordinal){{"Oil",0},{"Gas",0},{"Water",0}};foreach(var x in samples){if(x.OilSaturation>=FluidPresenceThreshold)counts["Oil"]++;if(x.GasSaturation>=FluidPresenceThreshold)counts["Gas"]++;if(x.WaterSaturation>=FluidPresenceThreshold)counts["Water"]++;}return counts;}
 static ScorecardMetric Ratio(string name,ScoreMetricBasis basis,double numerator,double denominator)=>denominator<=0?Unavailable($"{name}.{basis}",basis,"fraction","Metric denominator is zero."):Scored($"{name}.{basis}",basis,numerator/denominator,"fraction");
 static void AddProduction(List<ScorecardMetric> m,IReadOnlyList<AnalysisProductionForecastDto> forecasts,ProductionRunResponse truth,ProductionSeriesArtifact observed){if(!forecasts.Select(x=>x.Year).Order().SequenceEqual(new[]{1,3,5}))throw Invalid("Production forecasts must contain years 1, 3, and 5.");MonthlyProductionTruth[] truthMonths=truth.MonthlyTruth.Where(x=>x.Month>0).OrderBy(x=>x.Month).Take(60).ToArray();if(truthMonths.Length!=60)throw Invalid("Production truth must contain 60 scored months.");foreach(string phase in new[]{"Oil","Gas","Water"}){double[] predicted=PredictedMonthly(forecasts,phase),actualTruth=MonthlyVolumes(truthMonths,phase);AddProductionBasis(m,phase,predicted,actualTruth,ScoreMetricBasis.HiddenTruth,60);var observedValues=observed.Months.OrderBy(x=>x.Month).Select(x=>Corrected(x,phase)).ToArray();AddProductionBasis(m,phase,predicted,observedValues,ScoreMetricBasis.RevealedObservation,observedValues.Count(x=>x is not null));foreach(int year in new[]{1,3,5}){double p=Forecast(forecasts,year,phase),t=Checkpoint(truth.Checkpoints,year,phase);m.Add(Relative($"cumulative{phase}RelativeError.Y{year}.HiddenTruth",ScoreMetricBasis.HiddenTruth,p,t,$"Stage A year-{year} cumulative {phase.ToLowerInvariant()} denominator is zero."));ProductionObservableCheckpoint checkpoint=observed.Checkpoints.Single(x=>x.Year==year);double? o=ObservedCheckpoint(checkpoint,phase);m.Add(o is null?Unavailable($"cumulative{phase}RelativeError.Y{year}.RevealedObservation",ScoreMetricBasis.RevealedObservation,"fraction",$"Corrected year-{year} cumulative {phase.ToLowerInvariant()} is unavailable."):Relative($"cumulative{phase}RelativeError.Y{year}.RevealedObservation",ScoreMetricBasis.RevealedObservation,p,o.Value,$"Corrected year-{year} cumulative {phase.ToLowerInvariant()} denominator is zero."));}}
 }
 static void AddProductionBasis(List<ScorecardMetric> m,string phase,double[] predicted,IReadOnlyList<double> actual,ScoreMetricBasis basis,int count){double initialActual=actual[0],initialPredicted=predicted[0];m.Add(Relative($"initial{phase}RateRelativeError.{basis}",basis,initialPredicted,initialActual,$"Initial {phase.ToLowerInvariant()} denominator is zero."));double rmse=Math.Sqrt(predicted.Zip(actual,(p,a)=>(p-a)*(p-a)).Average());double mean=actual.Select(Math.Abs).Average();m.Add(Scored($"monthly{phase}Rmse.{basis}",basis,rmse,"m3/month"));m.Add(mean==0?Unavailable($"monthly{phase}Nrmse.{basis}",basis,"fraction","Mean observed monthly volume is zero; normalization is undefined."):Scored($"monthly{phase}Nrmse.{basis}",basis,rmse/mean,"fraction"));m.Add(Scored($"monthly{phase}ScoredMonthCount.{basis}",basis,count,"count"));}
 static void AddProductionBasis(List<ScorecardMetric> m,string phase,double[] predicted,IReadOnlyList<double?> actual,ScoreMetricBasis basis,int count){var pairs=predicted.Zip(actual,(p,a)=>(p,a)).Where(x=>x.a is not null).Select(x=>(x.p,a:x.a!.Value)).ToArray();if(pairs.Length==0){foreach(string stem in new[]{"initial"+phase+"RateRelativeError","monthly"+phase+"Rmse","monthly"+phase+"Nrmse"})m.Add(Unavailable($"{stem}.{basis}",basis,stem.Contains("Rmse",StringComparison.Ordinal)&&!stem.Contains("Nrmse",StringComparison.Ordinal)?"m3/month":"fraction","No corrected monthly values were available."));m.Add(Scored($"monthly{phase}ScoredMonthCount.{basis}",basis,0,"count"));return;}var first=pairs[0];m.Add(Relative($"initial{phase}RateRelativeError.{basis}",basis,first.p,first.a,$"First available corrected {phase.ToLowerInvariant()} denominator is zero."));double rmse=Math.Sqrt(pairs.Average(x=>(x.p-x.a)*(x.p-x.a))),mean=pairs.Average(x=>Math.Abs(x.a));m.Add(Scored($"monthly{phase}Rmse.{basis}",basis,rmse,"m3/month"));m.Add(mean==0?Unavailable($"monthly{phase}Nrmse.{basis}",basis,"fraction","Mean corrected monthly volume is zero; normalization is undefined."):Scored($"monthly{phase}Nrmse.{basis}",basis,rmse/mean,"fraction"));m.Add(Scored($"monthly{phase}ScoredMonthCount.{basis}",basis,count,"count"));}
 static ScorecardMetric Relative(string name,ScoreMetricBasis basis,double predicted,double actual,string zero)=>Math.Abs(actual)<=1e-12?Unavailable(name,basis,"fraction",zero):Scored(name,basis,Math.Abs(predicted-actual)/Math.Abs(actual),"fraction");
 static double[] PredictedMonthly(IReadOnlyList<AnalysisProductionForecastDto> f,string phase){double[] cumulative=new double[61];for(int month=1;month<=60;month++){double years=month/12d;int lower=years<=1?0:years<=3?1:3,upper=years<=1?1:years<=3?3:5;double low=lower==0?0:Forecast(f,lower,phase),high=Forecast(f,upper,phase),ratio=(years-lower)/(upper-lower);cumulative[month]=low+(high-low)*ratio;}return Enumerable.Range(1,60).Select(i=>cumulative[i]-cumulative[i-1]).ToArray();}
 static double[] MonthlyVolumes(IReadOnlyList<MonthlyProductionTruth> months,string phase){double prior=0;return months.Select(x=>{double current=phase switch{"Oil"=>x.CumulativeOilM3,"Gas"=>x.CumulativeGasM3,_=>x.CumulativeWaterM3};double value=current-prior;prior=current;return value;}).ToArray();}
 static double Forecast(IReadOnlyList<AnalysisProductionForecastDto> f,int year,string phase){var x=f.Single(y=>y.Year==year);return phase switch{"Oil"=>x.OilM3,"Gas"=>x.GasM3,_=>x.WaterM3};}static double Checkpoint(IReadOnlyList<ProductionCheckpoint> c,int year,string phase){var x=c.Single(y=>y.Year==year).CumulativeProducedM3;return phase switch{"Oil"=>x.Oil,"Gas"=>x.Gas,_=>x.Water};}static double? Corrected(MeterMonth x,string phase)=>phase switch{"Oil"=>x.CorrectedOilM3,"Gas"=>x.CorrectedGasM3,_=>x.CorrectedWaterM3};static double? ObservedCheckpoint(ProductionObservableCheckpoint x,string phase)=>phase switch{"Oil"=>x.CumulativeCorrectedOilM3,"Gas"=>x.CumulativeCorrectedGasM3,_=>x.CumulativeCorrectedWaterM3};
 static void AddObservationGaps(List<ScorecardMetric> metrics){var snapshot=metrics.Where(x=>x.Status==ScoreMetricStatus.Scored&&x.Value is not null).ToArray();foreach(var hidden in snapshot.Where(x=>x.Basis==ScoreMetricBasis.HiddenTruth&&IsGapError(x.Name))){string stem=hidden.Name[..hidden.Name.LastIndexOf('.')];ScorecardMetric? observed=snapshot.SingleOrDefault(x=>x.Basis==ScoreMetricBasis.RevealedObservation&&x.Name==stem+".RevealedObservation");if(observed is not null)metrics.Add(Scored(stem+".ObservationGap",ScoreMetricBasis.ObservationGap,Math.Abs(hidden.Value!.Value-observed.Value!.Value),hidden.Unit!));}}
 static bool IsGapError(string name)=>name.Contains("AbsoluteError",StringComparison.Ordinal)||name.Contains("RelativeError",StringComparison.Ordinal)||name.Contains("Rmse",StringComparison.OrdinalIgnoreCase);
 static Dictionary<string,double> InferContacts(IReadOnlyList<(double Md,double Tvd,string Class)> values){var found=new Dictionary<string,List<double>>(StringComparer.Ordinal);for(int i=1;i<values.Count;i++){string? type=Contact(values[i-1].Class,values[i].Class);if(type is null)continue;if(!found.TryGetValue(type,out var list))found[type]=list=[];list.Add((values[i-1].Tvd+values[i].Tvd)/2);}return found.ToDictionary(x=>x.Key,x=>Median(x.Value),StringComparer.Ordinal);}
 static string? Contact(string a,string b){if(a==b)return null;var set=new HashSet<string>([a,b],StringComparer.Ordinal);if(set.SetEquals(["Gas","Oil"]))return "GOC";if(set.SetEquals(["Gas","Water"]))return "GWC";if(set.SetEquals(["Oil","Water"]))return "OWC";return null;}
 static string TruthClass(TruthSampleDto x)=>x.GasSaturation>=x.OilSaturation&&x.GasSaturation>=x.WaterSaturation?"Gas":x.OilSaturation>=x.WaterSaturation?"Oil":"Water";
 static bool ValidLog(LogObservationSample x)=>x.GrApi is not null&&x.RhobKgM3 is not null&&x.NphiFraction is not null&&x.DeepResistivityOhmM is not null&&!x.QcFlags.Contains("BadHole")&&!x.QcFlags.Contains("MissingInterval");
 static string ObservedClass(LogObservationSample x)=>x.NphiFraction<.12&&x.RhobKgM3<2200&&x.DeepResistivityOhmM>=2?"Gas":x.DeepResistivityOhmM>=2?"Oil":"Water";
 static double Thickness(IReadOnlyList<(double Md,bool Quality)> x){double sum=0;for(int i=1;i<x.Count;i++)sum+=(x[i].Md-x[i-1].Md)*((x[i-1].Quality?1:0)+(x[i].Quality?1:0))/2d;return sum;}
 static double InterpolateSurveyTvd(IReadOnlyList<SurveyStation> p,double md){if(md<=p[0].MeasuredDepthM)return p[0].ObservedTrueVerticalDepthM;if(md>=p[^1].MeasuredDepthM)return p[^1].ObservedTrueVerticalDepthM;int i=1;while(p[i].MeasuredDepthM<md)i++;double f=(md-p[i-1].MeasuredDepthM)/(p[i].MeasuredDepthM-p[i-1].MeasuredDepthM);return p[i-1].ObservedTrueVerticalDepthM+(p[i].ObservedTrueVerticalDepthM-p[i-1].ObservedTrueVerticalDepthM)*f;}
 static double Median(IEnumerable<double> values){double[] x=values.Order().ToArray();return x.Length%2==1?x[x.Length/2]:(x[x.Length/2-1]+x[x.Length/2])/2;}
 static void ValidateQuantiles(AnalysisQuantilesDto q,string name){if(!double.IsFinite(q.P90)||!double.IsFinite(q.P50)||!double.IsFinite(q.P10)||q.P90>q.P50||q.P50>q.P10)throw Invalid($"{name} quantiles are invalid.");}
 static ScorecardMetric Scored(string name,ScoreMetricBasis basis,double value,string unit,double? lower=null,double? upper=null)=>new(name,basis,ScoreMetricStatus.Scored,value,unit,lower,upper,null);
 static ScorecardMetric Unavailable(string name,ScoreMetricBasis basis,string unit,string limitation)=>new(name,basis,ScoreMetricStatus.Unavailable,null,unit,null,null,limitation);
 static void ValidateMetrics(IReadOnlyList<ScorecardMetric> metrics){try{ScoreMetricContract.ValidateForPublication(metrics);}catch(ArgumentException e){throw Invalid(e.Message);}}
 static ScoringException Invalid(string message)=>new(409,"ScoringInputInvalid",message);
}
