using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Options;
namespace DrillingOperations;

public sealed class SurveyObservationOptions
{
 public const string SectionName="SurveyObservation"; public string ModelVersion{get;init;}="synthetic-survey-v1";public string CalibrationVersion{get;init;}="survey-calibration-default-v1";public double StationSpacingM{get;init;}=30;public double EastBiasM{get;init;}=0.4;public double NorthBiasM{get;init;}=-0.3;public double TvdBiasM{get;init;}=0.25;public double ScaleFactor{get;init;}=1;public double MisalignmentDegrees{get;init;}=0;public double RandomWalkStdDevM{get;init;}=0.03;public double NoiseStdDevM{get;init;}=0.08;public double CovarianceFloorM2{get;init;}=0.0025;
 public void Validate(){Token(ModelVersion,nameof(ModelVersion));Token(CalibrationVersion,nameof(CalibrationVersion));Bound(StationSpacingM,1,500,nameof(StationSpacingM));Bound(ScaleFactor,0.98,1.02,nameof(ScaleFactor));Bound(MisalignmentDegrees,-15,15,nameof(MisalignmentDegrees));Bound(RandomWalkStdDevM,0,5,nameof(RandomWalkStdDevM));Bound(NoiseStdDevM,0,10,nameof(NoiseStdDevM));Bound(CovarianceFloorM2,1e-8,100,nameof(CovarianceFloorM2));foreach(double x in new[]{EastBiasM,NorthBiasM,TvdBiasM})if(!double.IsFinite(x)||Math.Abs(x)>100)throw Error("Biases must be finite and bounded.");}
 public string Hash(){Validate();return DeterministicIdentity.Sha256(CanonicalJson.Serialize(this));}
 private static void Bound(double x,double min,double max,string n){if(!double.IsFinite(x)||x<min||x>max)throw Error($"{n} is outside [{min},{max}].");}private static void Token(string x,string n){if(string.IsNullOrWhiteSpace(x)||x.Length>128||x.Any(c=>!(char.IsAsciiLetterOrDigit(c)||"-_.:".Contains(c))))throw Error($"{n} is invalid.");}private static OptionsValidationException Error(string m)=>new(nameof(SurveyObservationOptions),typeof(SurveyObservationOptions),[m]);
}
public sealed record SurveyCovariance(double EastEast,double EastNorth,double EastTvd,double NorthEast,double NorthNorth,double NorthTvd,double TvdEast,double TvdNorth,double TvdTvd);
public sealed record SurveyStation(double MeasuredDepthM,double ObservedEastingM,double ObservedNorthingM,double ObservedTrueVerticalDepthM,double InclinationDegrees,double AzimuthDegrees,SurveyCovariance Covariance,string QcFlag,double HorizontalUncertainty95M,double VerticalUncertainty95M);
public sealed record SurveyArtifact(string SurveyArtifactId,string RunId,string ExecutionId,string ModelVersion,string CalibrationVersion,string OptionsHash,IReadOnlyList<SurveyStation> Stations,string PathHash,string InputHash,string OutputHash,double StartSimulatedSeconds,double EndSimulatedSeconds,DateTimeOffset CreatedUtc){public string TrajectoryRole=>TrajectoryMetadata.DefinitiveSyntheticSurvey;public string VerticalDirection=>TrajectoryMetadata.VerticalDirection;public string ReferenceFrame=>TrajectoryMetadata.ReferenceFrame;}
public static class DeterministicSurveyModel
{
 public static IReadOnlyList<SurveyStation> Generate(string runId,IReadOnlyList<DrilledPathStation> source,SurveyObservationOptions options){options.Validate();var p=source.Select(x=>new PlanPathStation(x.MeasuredDepthM,x.TrueVerticalDepthM,x.EastingM,x.NorthingM)).ToArray();var dense=DeterministicDrillingModel.Densify(p,options.StationSpacingM);var rng=new HashNormal(runId+"\n"+options.Hash());double we=0,wn=0,wt=0;var result=new List<SurveyStation>(dense.Count);PlanPathStation collar=dense[0];for(int i=0;i<dense.Count;i++){var x=dense[i];if(i>0){double f=Math.Sqrt((x.MeasuredDepthM-dense[i-1].MeasuredDepthM)/options.StationSpacingM);we+=rng.Next()*options.RandomWalkStdDevM*f;wn+=rng.Next()*options.RandomWalkStdDevM*f;wt+=rng.Next()*options.RandomWalkStdDevM*f;}double angle=options.MisalignmentDegrees*Math.PI/180,dx=(x.EastingM-collar.EastingM)*options.ScaleFactor+options.EastBiasM,dy=(x.NorthingM-collar.NorthingM)*options.ScaleFactor+options.NorthBiasM;double e=collar.EastingM+dx*Math.Cos(angle)-dy*Math.Sin(angle)+we+rng.Next()*options.NoiseStdDevM;double n=collar.NorthingM+dx*Math.Sin(angle)+dy*Math.Cos(angle)+wn+rng.Next()*options.NoiseStdDevM;double tvd=Math.Max(0,collar.TrueVerticalDepthM+(x.TrueVerticalDepthM-collar.TrueVerticalDepthM)*options.ScaleFactor+options.TvdBiasM+wt+rng.Next()*options.NoiseStdDevM);double depth=Math.Max(0,x.MeasuredDepthM-dense[0].MeasuredDepthM);double variance=options.CovarianceFloorM2+options.NoiseStdDevM*options.NoiseStdDevM+options.RandomWalkStdDevM*options.RandomWalkStdDevM*depth/options.StationSpacingM;var cov=new SurveyCovariance(variance,0,0,0,variance,0,0,0,variance);double inc=0,azi=0;if(i>0){double dz=tvd-result[^1].ObservedTrueVerticalDepthM,de=e-result[^1].ObservedEastingM,dn=n-result[^1].ObservedNorthingM;double length=Math.Sqrt(de*de+dn*dn+dz*dz);if(length>1e-9){inc=Math.Acos(Math.Clamp(dz/length,-1,1))*180/Math.PI;azi=(Math.Atan2(de,dn)*180/Math.PI+360)%360;}}result.Add(new(x.MeasuredDepthM,e,n,tvd,inc,azi,cov,"SyntheticCalibrated",1.96*Math.Sqrt(2*variance),1.96*Math.Sqrt(variance)));}return result;}
 private sealed class HashNormal(string seed){private long i;public double Next(){byte[] h=SHA256.HashData(Encoding.UTF8.GetBytes(seed+"\n"+(i++).ToString(System.Globalization.CultureInfo.InvariantCulture)));double u1=(BitConverter.ToUInt64(h,0)+1d)/(ulong.MaxValue+2d),u2=(BitConverter.ToUInt64(h,8)+1d)/(ulong.MaxValue+2d);return Math.Sqrt(-2*Math.Log(u1))*Math.Cos(Math.Tau*u2);}}
}

public sealed class TruthSamplingOptions
{
 public const string SectionName="TruthSampling";public string PropertySetVersion{get;init;}="stage-b-truth-v1";public double MaximumSpacingM{get;init;}=10;public int MaximumSamples{get;init;}=10_000;public string CallerLabel{get;init;}="drilling-operations";
 public void Validate(){if(PropertySetVersion!="stage-b-truth-v1"||!double.IsFinite(MaximumSpacingM)||MaximumSpacingM<1||MaximumSpacingM>500||MaximumSamples<1||MaximumSamples>10_000||string.IsNullOrWhiteSpace(CallerLabel)||CallerLabel.Length>100)throw new OptionsValidationException(nameof(TruthSamplingOptions),typeof(TruthSamplingOptions),["Truth sampling options are invalid."]);}public string Hash(){Validate();return DeterministicIdentity.Sha256(CanonicalJson.Serialize(this));}
}
public sealed record StageAPathBindingDto(string BindingId,string WorldId,Guid ScenarioId,Guid RunId,string PathKind,string ApprovedSealedPredictionSha256,string CanonicalHash,int StationCount);
public sealed record TruthSampleDto(double MeasuredDepthM,double EastingM,double NorthingM,double TrueVerticalDepthM,double ReservoirTopDepthM,double ReservoirBaseDepthM,double Porosity,double PermeabilityM2,double NetToGross,bool IsReservoirQuality,double PressurePa,double OilSaturation,double WaterSaturation,double GasSaturation);
public sealed record StageATruthResultDto(string BindingId,string WorldId,Guid ScenarioId,Guid RunId,string PropertySetVersion,int SampleCount,IReadOnlyList<TruthSampleDto> Samples);
public sealed record TruthSamplingEnvelope(StageAPathBindingDto Binding,StageATruthResultDto Result,string CanonicalBindingRequestJson,string BindingRequestHash,string CanonicalSamplingOptionsJson,string SamplingOptionsHash);
public sealed record TruthSampleBatch(string BatchId,string RunId,string ScenarioId,string WorldId,string StageAPathBindingId,string PropertySetVersion,int SampleCount,string BindingHash,string CanonicalBindingJson,string CanonicalBindingRequestJson,string BindingRequestHash,string CanonicalSamplingOptionsJson,string SamplingOptionsHash,string CanonicalResponseJson,string ResponseHash,DateTimeOffset CreatedUtc);
public sealed class StageASamplingException(int status,string diagnostic,string message):Exception(message){public int StatusCode{get;}=status;public string DiagnosticCode{get;}=diagnostic;}

public sealed class ReservoirSamplingClient(HttpClient client)
{
 public async Task<TruthSamplingEnvelope> SampleAsync(TruthBindingResponse binding,DrillingExecutionArtifact execution,TruthSamplingOptions options,CancellationToken ct){options.Validate();if(!Guid.TryParse(binding.ScenarioId,out Guid scenario)||!Guid.TryParse(execution.RunId,out Guid run))throw new StageASamplingException(409,"SamplingIdentityMismatch","Stored IDs are invalid.");var bindingRequest=new{scenarioId=scenario,runId=run,pathKind="AsDrilled",approvedSealedPredictionSha256=binding.ApprovedSealedPredictionHash,stations=execution.Stations.Select(x=>new{x.MeasuredDepthM,x.EastingM,x.NorthingM,x.TrueVerticalDepthM})};string stageCanonical=System.Text.Json.JsonSerializer.Serialize(new{worldId=binding.WorldId,scenarioId=scenario,runId=run,pathKind=1,approvedSealedPredictionSha256=binding.ApprovedSealedPredictionHash,stations=execution.Stations.Select(x=>new{x.MeasuredDepthM,x.EastingM,x.NorthingM,x.TrueVerticalDepthM})},new System.Text.Json.JsonSerializerOptions{PropertyNamingPolicy=System.Text.Json.JsonNamingPolicy.CamelCase});string requestHash=DeterministicIdentity.Sha256(stageCanonical);string expectedBindingId="rpb_"+DeterministicIdentity.Sha256("approved-path-binding-v1\n"+stageCanonical);StageAPathBindingDto metadata=await Post<StageAPathBindingDto>($"reservoirsimulation/api/worlds/{Uri.EscapeDataString(binding.WorldId)}/path-bindings",bindingRequest,ct);if(metadata.BindingId!=expectedBindingId||metadata.CanonicalHash!=requestHash||metadata.WorldId!=binding.WorldId||metadata.ScenarioId!=scenario||metadata.RunId!=run||metadata.PathKind!="AsDrilled"||metadata.ApprovedSealedPredictionSha256!=binding.ApprovedSealedPredictionHash||metadata.StationCount!=execution.Stations.Count)Mismatch("Path binding metadata mismatch.");var samplingRequest=new{bindingId=metadata.BindingId,maximumSpacingM=options.MaximumSpacingM,maximumSamples=options.MaximumSamples,propertySetVersion=options.PropertySetVersion,callerLabel=options.CallerLabel};StageATruthResultDto result=await Post<StageATruthResultDto>($"reservoirsimulation/api/worlds/{Uri.EscapeDataString(binding.WorldId)}/samples",samplingRequest,ct);Validate(result,metadata,binding,execution,options);string samplingOptionsJson=CanonicalJson.Serialize(options);return new(metadata,result,stageCanonical,requestHash,samplingOptionsJson,DeterministicIdentity.Sha256(samplingOptionsJson));}
 private async Task<T> Post<T>(string path,object body,CancellationToken ct){try{using HttpResponseMessage response=await client.PostAsJsonAsync(path,body,CanonicalJson.SerializerOptions,ct);if(!response.IsSuccessStatusCode){int s=(int)response.StatusCode;throw new StageASamplingException(s>=500?502:409,s>=500?"StageAUnavailable":"StageADataMismatch","Stage A rejected sampling.");}return await response.Content.ReadFromJsonAsync<T>(CanonicalJson.SerializerOptions,ct)??throw new StageASamplingException(502,"StageAMalformedResponse","Stage A returned empty JSON.");}catch(StageASamplingException){throw;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){throw new StageASamplingException(503,"StageATimeout","Stage A timed out.");}catch(System.Text.Json.JsonException){throw new StageASamplingException(409,"StageAMalformedResponse","Stage A returned malformed JSON.");}catch(HttpRequestException){throw new StageASamplingException(503,"StageAUnavailable","Stage A is unavailable.");}}
 private static void Validate(StageATruthResultDto r,StageAPathBindingDto m,TruthBindingResponse b,DrillingExecutionArtifact e,TruthSamplingOptions o){if(r.BindingId!=m.BindingId||r.WorldId!=b.WorldId||r.ScenarioId.ToString("D")!=b.ScenarioId||r.RunId.ToString("D")!=e.RunId||r.PropertySetVersion!=o.PropertySetVersion||r.SampleCount!=r.Samples?.Count||r.SampleCount<1||r.SampleCount>o.MaximumSamples)Mismatch("Truth result identity, property set, or count mismatch.");double prior=-1;foreach(TruthSampleDto x in r.Samples!){if(!IsPhysicallyValid(x)||x.MeasuredDepthM<0||x.MeasuredDepthM<=prior)Mismatch("Truth sample values are invalid.");DrilledPathStation expected=Interpolate(e.Stations,x.MeasuredDepthM);if(Math.Abs(expected.EastingM-x.EastingM)>1e-4||Math.Abs(expected.NorthingM-x.NorthingM)>1e-4||Math.Abs(expected.TrueVerticalDepthM-x.TrueVerticalDepthM)>1e-4)Mismatch("Truth sample coordinates are outside the approved path.");prior=x.MeasuredDepthM;}}
 internal static bool IsPhysicallyValid(TruthSampleDto x)=>AllFinite(x)&&x.Porosity is >=0 and <=1&&x.NetToGross is >=0 and <=1&&x.PermeabilityM2>0&&x.PressurePa>0&&x.ReservoirTopDepthM<x.ReservoirBaseDepthM&&x.TrueVerticalDepthM>=x.ReservoirTopDepthM-1e-6&&x.TrueVerticalDepthM<=x.ReservoirBaseDepthM+1e-6&&x.OilSaturation is >=0 and <=1&&x.WaterSaturation is >=0 and <=1&&x.GasSaturation is >=0 and <=1&&Math.Abs(x.OilSaturation+x.WaterSaturation+x.GasSaturation-1)<=1e-6;
 private static bool ValidHash(string x)=>x.Length==64&&x.All(c=>(c>=48&&c<=57)||(c>=97&&c<=102)); private static bool ValidToken(string x,int max)=>!string.IsNullOrWhiteSpace(x)&&x.Length<=max;
 private static bool AllFinite(TruthSampleDto x)=>new[]{x.MeasuredDepthM,x.EastingM,x.NorthingM,x.TrueVerticalDepthM,x.ReservoirTopDepthM,x.ReservoirBaseDepthM,x.Porosity,x.PermeabilityM2,x.NetToGross,x.PressurePa,x.OilSaturation,x.WaterSaturation,x.GasSaturation}.All(double.IsFinite);
 private static DrilledPathStation Interpolate(IReadOnlyList<DrilledPathStation> p,double md){if(md<p[0].MeasuredDepthM-1e-8||md>p[^1].MeasuredDepthM+1e-8)Mismatch("Sample MD is outside path.");int i=1;while(i<p.Count&&p[i].MeasuredDepthM<md)i++;if(i==p.Count)return p[^1];var a=p[i-1];var z=p[i];double f=(md-a.MeasuredDepthM)/(z.MeasuredDepthM-a.MeasuredDepthM);return new(md,a.TrueVerticalDepthM+(z.TrueVerticalDepthM-a.TrueVerticalDepthM)*f,a.EastingM+(z.EastingM-a.EastingM)*f,a.NorthingM+(z.NorthingM-a.NorthingM)*f);}
 private static void Mismatch(string m)=>throw new StageASamplingException(409,"StageADataMismatch",m);
}










