<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileBuildArguments>--build-arg NORCE_NUGET_USER --build-arg NORCE_NUGET_APIKEY</DockerfileBuildArguments>
		<UserSecretsId>d4693808-78e9-47c7-919b-bed83a86870d</UserSecretsId>
		<RootNamespace>OSDC.Drilling.Rig.Service</RootNamespace>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
		<Nullable>enable</Nullable>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
		<PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.17.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Model\Model.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\json-schema\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE" Pack="true" PackagePath="" />
		<None Include="README.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<PropertyGroup>
		<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
		<OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)\..\ModelSharedOut\json-schemas</OpenApiDocumentsDirectory>
		<OpenApiGenerateDocumentsOptions>--document-name v1 --file-name RigFullName --openapi-version OpenApi3_0</OpenApiGenerateDocumentsOptions>
	</PropertyGroup>

</Project>
