import assert from 'node:assert/strict'
import { pathToFileURL } from 'node:url'
import { installSimulationFixture, newScenarioId } from './simulation-fixture.mjs'

if (!process.env.DRILLSIM_PLAYWRIGHT_MODULE) throw new Error('Set DRILLSIM_PLAYWRIGHT_MODULE to an existing playwright/index.mjs.')
const { chromium } = await import(pathToFileURL(process.env.DRILLSIM_PLAYWRIGHT_MODULE).href)
const browser = await chromium.launch({ channel: 'msedge', headless: true })
let diagnostics = async () => ({})
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
  const fixture = await installSimulationFixture(context, { failFirstCreate: true, failFirstSetup: true })
  const page = await context.newPage(), errors = []
  page.setDefaultTimeout(25000)
  page.on('pageerror', error => errors.push(error.message))
  diagnostics = async () => ({
    headings: await page.locator('h2,h3,h4').allTextContents(),
    alerts: await page.getByRole('alert').allTextContents(),
    tutorial: await page.locator('.tutorial-status').allTextContents(),
    pending: await page.locator('.operator-pending').allTextContents(),
    unexpected: fixture.state.unexpected, errors,
  })
  await page.goto(process.env.DRILLSIM_TEST_URL ?? 'http://localhost:5173')
  await page.locator('.sequencer').waitFor()
  await page.getByRole('button', { name: 'Guided tutorial', exact: true }).click()
  const panel = page.getByRole('complementary', { name: 'Guided tutorial', exact: true })
  await panel.getByLabel('Chapter', { exact: true }).selectOption('3')
  await panel.getByRole('button', { name: 'Start chapter', exact: true }).click()
  const next = async () => {
    const title = await panel.locator('.tutorial-header h2').innerText()
    await panel.getByRole('button', { name: 'Next →', exact: true }).click()
    await panel.getByRole('heading', { name: title, exact: true }).waitFor({ state: 'detached' })
  }
  assert.equal(fixture.state.mutations.length, 0, 'Opening Chapter 4 never mutates anything.')
  await next()
  const form = page.locator('[data-tutorial="scenario-create"]')
  await form.waitFor()
  assert.equal(fixture.state.mutations.length, 0, 'Opening a lifecycle task without a scenario only opens setup.')
  await form.getByLabel('Scenario name', { exact: true }).fill('Guided browser-only simulation')
  await form.getByLabel('Evidence cutoff (UTC)', { exact: true }).fill('2026-09-16T12:00:00Z')
  await form.getByRole('checkbox').check()
  await form.getByRole('button', { name: 'Create scenario', exact: true }).click()
  await form.getByRole('alert').filter({ hasText: /unchanged/ }).waitFor()
  assert.equal(await form.getByLabel('Scenario name', { exact: true }).isDisabled(), true)
  assert.equal(fixture.state.createBodies.length, 1)
  await form.getByRole('checkbox').check()
  await form.getByRole('button', { name: 'Retry same scenario creation', exact: true }).click()
  await page.locator('[data-tutorial="prediction-source"]').waitFor()
  assert.equal(fixture.state.createBodies.length, 2)
  assert.equal(fixture.state.createBodies[0], fixture.state.createBodies[1], 'Uncertain create retries keep the exact UTC cutoff and payload.')
  assert.equal(fixture.state.created.scenario.scenarioId, newScenarioId)
  await next()
  await page.locator('[data-tutorial="analyze-frozen-source"]').click()
  await panel.getByText('Verified frozen-source analysis is available.', { exact: true }).waitFor()
  await next()
  const target = page.locator('[data-tutorial="prediction-target"]')
  const candidateId = await target.locator('option').nth(1).getAttribute('value')
  await target.selectOption(candidateId)
  await next()
  await page.getByRole('button', { name: 'Use editable demo forecast', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Year 1 oil cumulative (m³)', exact: true }).fill('12345')
  await page.getByRole('button', { name: 'Use editable demo forecast', exact: true }).click()
  assert.equal(await page.getByRole('spinbutton', { name: 'Year 1 oil cumulative (m³)', exact: true }).inputValue(), '12345',
    'Reapplying examples never overwrites an edited volume.')
  assert.equal(fixture.state.mutations.length, 3, 'Only two creates and the explicit frozen analysis have been requested.')
  await page.getByText('Advanced · prediction JSON and binding', { exact: true }).click()
  const json = page.locator('#prediction-json'), originalText = await json.inputValue(), edited = JSON.parse(originalText)
  edited.proposedWellPath[1].eastingM += 100
  await json.fill(JSON.stringify(edited, null, 2))
  assert.equal(await page.getByRole('button', { name: 'Save draft', exact: true }).isDisabled(), true)
  await page.getByRole('button', { name: 'Use editable demo forecast', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: /never flatten/ }).waitFor()
  assert.deepEqual(JSON.parse(await json.inputValue()).proposedWellPath, edited.proposedWellPath)
  await json.fill(originalText)
  await page.getByText('Advanced · prediction JSON and binding', { exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Guided forms must not overflow the mobile page.')
  assert.equal(await page.getByRole('spinbutton', { name: 'Year 1 oil cumulative (m³)', exact: true }).inputValue(), '12345')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await next()
  assert.equal(await panel.getByRole('button', { name: 'Next →', exact: true }).isDisabled(), true)
  await page.locator('[data-tutorial="save-prediction"]').click()
  await panel.getByText('A saved prediction revision is available.', { exact: true }).waitFor()
  assert.equal(fixture.state.created.prediction.body.productionForecasts[0].oilM3, 12345)
  assert.ok(fixture.state.created.prediction.body.uncertaintyAssumptions.some(text => text.includes('DEMONSTRATION ESTIMATES')))
  await next()
  await page.locator('[data-tutorial="prediction-ledger"]').waitFor()
  await next()
  await page.locator('[data-tutorial="review-prediction-seal"]').check()
  await page.getByRole('button', { name: 'Seal reviewed revision', exact: true }).click()
  await panel.getByText('The reviewed prediction is sealed.', { exact: true }).waitFor()
  assert.equal(fixture.state.created.prediction.approval, undefined, 'Seal is not approval.')
  await next()
  await page.getByRole('button', { name: 'Use demo operator label', exact: true }).click()
  await page.locator('[data-tutorial="review-prediction-approval"]').check()
  await page.getByRole('button', { name: 'Approve reviewed prediction', exact: true }).click()
  await panel.getByText('The exact sealed prediction has been approved.', { exact: true }).waitFor()
  assert.equal(fixture.state.created.prepared, false, 'Approval does not prepare a simulator.')
  await next()
  await page.getByRole('combobox', { name: 'Model preset', exact: true }).selectOption('troll-demo')
  await page.getByRole('spinbutton', { name: 'Realization seed', exact: true }).fill('41')
  const setupReview = page.locator('[data-tutorial="review-simulator-setup"]')
  await setupReview.check()
  await page.getByRole('combobox', { name: 'Simulation resolution', exact: true }).selectOption('Standard')
  assert.equal(await setupReview.isChecked(), false, 'Changing settings invalidates the exact setup review.')
  await page.getByRole('combobox', { name: 'Simulation resolution', exact: true }).selectOption('Preview')
  await setupReview.check()
  await page.locator('[data-tutorial="prepare-simulator"]').click()
  await page.locator('.operator-pending').waitFor()
  assert.equal(fixture.state.created.run, undefined, 'Prepare cannot chain Start, even when its response is lost.')
  await page.getByRole('checkbox', { name: 'I checked current operator state before retrying or retiring this attempt.', exact: true }).check()
  await page.getByRole('button', { name: 'Retry same attempt', exact: true }).click()
  await page.locator('.operator-pending').waitFor({ state: 'detached' })
  assert.equal(fixture.state.setupBodies.length, 2)
  assert.deepEqual(fixture.state.setupBodies[0], fixture.state.setupBodies[1], 'Retry retains the reviewed seed, preset, actor, seal and key.')
  assert.equal(await page.getByRole('combobox', { name: 'Model preset', exact: true }).count(), 0, 'Prepared model settings are immutable.')
  await next()
  await page.getByRole('button', { name: 'Start simulation', exact: true }).click()
  await panel.getByText('A run exists for this scenario. Continue with that run.', { exact: true }).waitFor()
  await next()
  await panel.getByText('The completion review is available or has already been approved.', { exact: true }).waitFor()
  assert.equal(fixture.state.created.completionApproved, false)
  await next()
  await page.locator('[data-tutorial="review-completion"]').check()
  await page.getByRole('button', { name: 'Approve reviewed completion', exact: true }).click()
  await panel.getByText('Completion approval is recorded for this run.', { exact: true }).waitFor()
  await next()
  await panel.getByText('Production checkpoints are complete.', { exact: true }).waitFor()
  assert.equal(fixture.state.created.reveal, undefined, 'Production does not itself publish evidence.')
  await next()
  await page.locator('[data-tutorial="review-publication"]').check()
  await page.getByRole('button', { name: 'Publish reveal and evaluate', exact: true }).click()
  await panel.getByText('A verified publication receipt is available.', { exact: true }).waitFor()
  await next()
  await panel.getByText('New evidence and production metadata are available.', { exact: true }).waitFor()
  await page.locator('.production-pane').waitFor()
  await next()
  await page.locator('[data-tutorial="simulation-scorecard"]').waitFor()
  assert.equal(await page.getByRole('button', { name: 'Run / retry evaluation', exact: true }).count(), 0)
  await next()
  await panel.getByRole('button', { name: 'Finish chapter', exact: true }).click()
  await panel.getByRole('heading', { name: 'Chapter complete', exact: true }).waitFor()
  await panel.getByRole('button', { name: 'Close guided tutorial', exact: true }).click()
  await page.locator('[data-tutorial="task-simulation"]').click()
  await page.getByRole('heading', { name: 'Simulation and evaluation complete', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Start simulation', exact: true }).count(), 0)
  assert.equal(await page.getByRole('button', { name: 'Prepare simulator', exact: true }).count(), 0)
  assert.equal(await page.getByText('Scenario is not in HumanApproved state', { exact: true }).count(), 0)
  await page.locator('[data-tutorial="task-new-evidence"]').click()
  assert.equal(await page.locator('[data-tutorial="review-publication"]').count(), 0, 'Published scenarios do not show a disabled publish checkbox.')
  await page.getByRole('button', { name: 'Guided tutorial', exact: true }).click()
  await panel.getByLabel('Chapter', { exact: true }).selectOption('3')
  await panel.getByRole('button', { name: 'Inspect this completed scenario', exact: true }).click()
  await panel.getByRole('heading', { name: 'Inspect the new well and production', exact: true }).waitFor()
  await panel.getByRole('button', { name: 'Close guided tutorial', exact: true }).click()
  const mutationsBeforeNew = fixture.state.mutations.length
  await page.locator('[data-tutorial="new-simulation-from-results"]').click()
  assert.match(await page.locator('[data-tutorial="scenario-create"]').innerText(), /Original field: TROLL FORCE-SODIR Field/)
  assert.equal(fixture.state.mutations.length, mutationsBeforeNew)
  assert.equal(fixture.referenceUnchanged(), true)
  assert.deepEqual(fixture.state.unexpected, [])
  assert.deepEqual(errors, [])
  assert.equal(fixture.state.mutations.filter(item => item.pathname.endsWith('/runs')).length, 1)
  assert.equal(fixture.state.mutations.filter(item => item.pathname.endsWith('/publish')).length, 1)
  assert.equal(fixture.state.mutations.length, 11)
  console.log(JSON.stringify({ status: 'passed', fullyMockedApis: true, guidedChapter4: true, stableCreateAndSetupRetries: true,
    explicitSaveSealApprovePrepareStartCompletionPublish: true, editableExamplesPreserved: true,
    directionalEditsNeverFlattened: true, immutableCompletedResults: true, historicalFixtureUnchanged: true, responsiveForms: true }))
} catch (error) {
  console.error(JSON.stringify(await diagnostics(), null, 2))
  throw error
} finally { await browser.close() }
