import assert from 'node:assert/strict'
import { pathToFileURL } from 'node:url'
import path from 'node:path'
import { installSimulationFixture } from './simulation-fixture.mjs'

if (!process.env.DRILLSIM_PLAYWRIGHT_MODULE) throw new Error('Set DRILLSIM_PLAYWRIGHT_MODULE to an existing playwright/index.mjs.')
const { chromium } = await import(pathToFileURL(process.env.DRILLSIM_PLAYWRIGHT_MODULE).href)
const browser = await chromium.launch({ channel: 'msedge', headless: true })
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
  const fixture = await installSimulationFixture(context)
  const page = await context.newPage()
  page.setDefaultTimeout(20000)
  const mutations = [], errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => {
    if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method())) mutations.push(request)
  })
  await page.goto(process.env.DRILLSIM_TEST_URL ?? 'http://localhost:5173')
  await page.locator('.sequencer').waitFor({ timeout: 60000 })
  const launch = page.getByRole('button', { name: 'Guided tutorial', exact: true })
  const panel = page.getByRole('complementary', { name: 'Guided tutorial', exact: true })
  assert.equal(await panel.count(), 0, 'Tutorial is never forced on page load.')
  const taskBefore = await page.locator('.step-key[aria-pressed="true"]').getAttribute('data-tutorial')
  await launch.click()
  assert.equal(await panel.isVisible(), true)
  assert.equal(await page.locator('.step-key[aria-pressed="true"]').getAttribute('data-tutorial'), taskBefore)
  const chapter = panel.getByLabel('Chapter', { exact: true })
  await panel.getByRole('button', { name: 'Start chapter', exact: true }).click()
  await panel.getByRole('button', { name: 'Next →', exact: true }).click()
  await panel.getByRole('heading', { name: 'Inspect the available data', exact: true }).waitFor()
  await page.locator('.tutorial-highlight').waitFor()
  assert.equal(await page.getByRole('heading', { name: 'Evidence', exact: true }).count(), 1)
  await panel.getByRole('button', { name: '← Prev', exact: true }).click()
  assert.equal(await panel.getByRole('heading', { name: 'Select the Troll field', exact: true }).count(), 1)
  assert.equal(mutations.length, 0)
  await chapter.selectOption('1')
  await panel.getByRole('button', { name: 'Start chapter', exact: true }).click()
  await panel.getByRole('button', { name: 'Next →', exact: true }).click()
  const grid = page.getByRole('spinbutton', { name: /Grid points per axis/ })
  assert.equal(await grid.inputValue(), '15')
  assert.equal(await panel.getByRole('button', { name: 'Next →', exact: true }).isDisabled(), true)
  await panel.getByRole('button', { name: 'Go to highlighted control', exact: true }).click()
  assert.equal(await grid.evaluate(element => element === document.activeElement), true)
  await grid.fill('9')
  await panel.getByRole('button', { name: 'Next →', exact: true }).click()
  assert.equal(await panel.getByRole('button', { name: 'Next →', exact: true }).isDisabled(), true, 'Pending 9 does not satisfy applied 81.')
  assert.equal(mutations.length, 0)
  const appliedResponse = page.waitForResponse(response => /\/api\/fields\/[^/]+\/analysis$/.test(response.url()) && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Apply analysis settings', exact: true }).click()
  const result = await (await appliedResponse).json()
  assert.equal(result.candidateGrid.length, 81)
  await panel.getByText('Analysis updated: 81 candidate cells.', { exact: true }).waitFor()
  await panel.getByRole('button', { name: 'Next →', exact: true }).click()
  await page.locator('[data-tutorial="task-targets"]').click()
  await panel.getByText(/You opened another task/).waitFor()
  assert.equal(await page.locator('.tutorial-highlight').count(), 0, 'No highlight points to stale task content.')
  await panel.getByRole('button', { name: 'Return to this step', exact: true }).click()
  await panel.getByRole('button', { name: 'Next →', exact: true }).click()
  await panel.getByRole('button', { name: 'Next →', exact: true }).click()
  assert.equal(await panel.getByRole('button', { name: 'Next →', exact: true }).isDisabled(), true)
  await page.getByRole('button', { name: 'Load defaults into form', exact: true }).click()
  assert.equal(await panel.getByRole('button', { name: 'Next →', exact: true }).isDisabled(), true)
  await page.getByRole('button', { name: 'Apply analysis settings', exact: true }).click()
  await panel.getByText('Defaults applied: 225 candidate cells.', { exact: true }).waitFor()
  await panel.getByRole('button', { name: 'Next →', exact: true }).click()
  await panel.getByRole('button', { name: 'Finish chapter', exact: true }).click()
  await panel.getByRole('heading', { name: 'Chapter complete', exact: true }).waitFor()
  assert.equal(mutations.length, 2)
  assert.ok(mutations.every(request => /\/api\/fields\/[^/]+\/analysis$/.test(request.url())), 'Only the two user Apply actions recalculate.')

  await chapter.selectOption('2')
  await panel.getByRole('button', { name: 'Draft a formation interpretation', exact: true }).click()
  const notes = page.locator('[data-tutorial="correlation-notes"]')
  await notes.getByText('Example correlation note', { exact: true }).click()
  await notes.getByRole('button', { name: 'Use example note', exact: true }).click()
  const exampleText = await notes.getByRole('textbox', { name: 'Correlation notes', exact: true }).inputValue()
  assert.match(exampleText, /^Check whether differences in formation depth/)
  assert.equal(mutations.length, 2, 'The example only fills local notes.')
  await panel.getByRole('button', { name: 'Next →', exact: true }).click()
  assert.equal(await page.getByRole('textbox', { name: 'Correlation notes', exact: true }).inputValue(), exampleText,
    'The note survives navigation to the save step.')
  await chapter.selectOption('2')
  await panel.getByRole('button', { name: 'Create an alternative', exact: true }).click()
  await panel.getByText(/Load or save an exact revision in Alternatives/).waitFor()
  assert.equal(await panel.getByRole('button', { name: 'Go to highlighted control', exact: true }).isDisabled(), true)
  await panel.getByRole('button', { name: 'Skip unavailable step', exact: true }).click()
  await panel.getByRole('heading', { name: 'Review a hypothesis', exact: true }).waitFor()
  // No global Arrow/Enter handlers steal editing keys; closing with Escape only affects the tutorial.
  await panel.getByRole('button', { name: 'Close guided tutorial', exact: true }).click()
  assert.equal(await panel.count(), 0)
  assert.equal(await launch.evaluate(element => element === document.activeElement), true)
  await launch.click()
  await chapter.selectOption('0')
  await panel.getByRole('button', { name: 'Open the 2D section', exact: true }).click()
  assert.equal(await panel.getByRole('button', { name: 'Next →', exact: true }).isDisabled(), true)
  await page.locator('[data-tutorial="lens-section"]').click()
  await panel.getByText('The 2D section is open.', { exact: true }).waitFor()
  assert.equal(await page.locator('[data-tutorial="task-pay"]').getAttribute('aria-pressed'), 'true')
  if (process.env.DRILLSIM_TEST_SCREENSHOTS) await page.screenshot({ path: path.join(process.env.DRILLSIM_TEST_SCREENSHOTS, 'tutorial-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await panel.getByRole('button', { name: 'Collapse instructions', exact: true }).waitFor()
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No page horizontal overflow on mobile.')
  assert.equal(await panel.getByRole('button', { name: 'Next →', exact: true }).isVisible(), true)
  await panel.getByRole('button', { name: 'Collapse instructions', exact: true }).click()
  await panel.getByRole('button', { name: 'Show instructions', exact: true }).click()
  if (process.env.DRILLSIM_TEST_SCREENSHOTS) await page.screenshot({ path: path.join(process.env.DRILLSIM_TEST_SCREENSHOTS, 'tutorial-mobile.png') })
  await page.keyboard.press('Escape')
  assert.equal(await panel.count(), 0)
  assert.equal(await page.locator('.tutorial-highlight').count(), 0)
  assert.equal(mutations.length, 2)
  const fieldPicker = page.getByRole('combobox', { name: 'FIELD', exact: true })
  await fieldPicker.click()
  const fieldList = page.getByRole('listbox', { name: 'Field options', exact: true })
  assert.equal(await fieldList.isVisible(), true)
  const trolls = fieldList.getByRole('option').filter({ hasText: 'TROLL FORCE-SODIR Field' })
  assert.equal(await trolls.count(), 3)
  assert.equal(await trolls.filter({ hasText: 'Original data' }).count(), 1)
  assert.equal(await trolls.filter({ hasText: 'Simulated results' }).count(), 2)
  const descriptions = await trolls.locator('p').allTextContents()
  assert.equal(new Set(descriptions).size, 3)
  await page.keyboard.press('End')
  await page.keyboard.press('Home')
  assert.ok(await fieldPicker.getAttribute('aria-activedescendant'))
  await page.keyboard.press('Escape')
  await page.waitForFunction(element => element.getAttribute('aria-expanded') === 'false', await fieldPicker.elementHandle())
  assert.equal(await fieldPicker.getAttribute('aria-expanded'), 'false')
  const scenarioPicker = page.getByRole('combobox', { name: 'SCENARIO', exact: true })
  await scenarioPicker.click()
  const scenarioList = page.getByRole('listbox', { name: 'Scenario options', exact: true })
  const scored = scenarioList.getByRole('option').filter({ hasText: 'AUTOMATED WORKFLOW FIXTURE 2026-09-11 9f64865b' })
  assert.equal(await scored.locator('.selection-badge').innerText(), 'Scored')
  assert.match(await scored.locator('p').innerText(), /Evaluation complete/)
  await scored.click()
  await page.waitForFunction(() => !document.querySelector('[role="combobox"][aria-controls]')?.disabled)
  await page.locator('.sequencer').waitFor({ timeout: 60000 })
  await scenarioPicker.click()
  await page.keyboard.press('Home')
  await page.keyboard.press('Enter')
  await page.locator('.sequencer').waitFor({ timeout: 60000 })
  assert.match(await scenarioPicker.innerText(), /Live evidence/)
  assert.equal(mutations.length, 2, 'Dataset selection only reads data.')
  assert.deepEqual(errors, [])
  assert.deepEqual(fixture.state.unexpected, [], 'All API requests are isolated fixture responses; no live mutations are permitted.')
  console.log(JSON.stringify({ status: 'passed', optionalTutorial: true, scopedExerciseChecks: true,
    manualApplyRequests: 2, mutationFreeNavigation: true, noPersistenceOrAi: true,
    missingTargetSkip: true, focusAndEscape: true, mobileAndReducedMotion: true }))
} finally { await browser.close() }
