<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
		<Version>3.4.1</Version>
		<Authors>Energy Modelling and Automation group</Authors>
		<Company>NORCE</Company>
		<Title>Distributed shared model for client applications of the UnitConversion microservice</Title>
		<PackageId>OSDC.UnitConversion.$(AssemblyName)</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.31" />
		<PackageReference Include="NSwag.CodeGeneration.CSharp" Version="14.7.1" />
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="json-schemas\3.0.0\" />
		<Folder Include="json-schemas\3.2.1\" />
	</ItemGroup>

</Project>
