replicaCount: 1
nameOverride: "osdcdrillingearthmagneticfieldwebappclient"
fullnameOverride: osdcearthmagneticfieldwebappclient
image:
  repository: docker.io/digiwells/osdcdrillingearthmagneticfieldwebappclient
  tag: "stable"
  pullPolicy: Always
imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  sessionAffinity: ClientIP
  annotations:
    description: "A web application for stateless WMM2025 and IGRF14 geomagnetic-field evaluation"
configuration:
  earthMagneticFieldHostURL: http://osdcearthmagneticfieldservice/
  unitConversionHostURL: http://osdcunitconversionservice/
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: true
  className: public
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: localhost
      paths:
        - path: /(?i)earthmagneticfield/webapp
          pathType: ImplementationSpecific
    - host: dev.digiwells.no
      paths:
        - path: /(?i)earthmagneticfield/webapp
          pathType: ImplementationSpecific
    - host: app.digiwells.no
      paths:
        - path: /(?i)earthmagneticfield/webapp
          pathType: ImplementationSpecific
    - host: awe.web.intra.norceresearch.no
      paths:
        - path: /(?i)earthmagneticfield/webapp
          pathType: ImplementationSpecific
  tls: []
probes:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
